namespace CofreDeSenhas
{
    internal static partial class Idioma
    {
        private static IReadOnlyDictionary<string, string> CriarIt() => Mesclar(new (string, string)[]
        {
            ("App.Title", "Cassaforte password"),
            ("Common.Save", "Salva"), ("Common.Apply", "Applica"), ("Common.Cancel", "Annulla"), ("Common.Change", "Cambia"),
            ("Common.Connect", "Connetti"), ("Common.Export", "Esporta"), ("Common.Import", "Importa"),
            ("Common.Exit", "Esci"), ("Common.Close", "Chiudi"),
            ("Common.Warning", "Avviso"), ("Common.Error", "Errore"), ("Common.Success", "Successo"),
            ("Common.Validation", "Validazione"), ("Common.Yes", "Sì"), ("Common.No", "No"),
            ("Common.AllFiles", "Tutti i file"), ("Common.ExportedVaultFile", "Cassaforte esportata"),
            ("Common.CsvFile", "File CSV"), ("Common.PngImage", "Immagine PNG"),
            ("Common.AndMore", "+altri {0}"),
            ("Common.SQLiteDatabase", "Database SQLite"),
            ("Settings.Tooltip", "Impostazioni"), ("Settings.SectionSecurity", "SICUREZZA"),
            ("Settings.ChangeMasterPassword", "Cambia password principale..."),
            ("Settings.RegenerateQr", "Rigenera codice QR..."), ("Settings.Backup", "Backup e ripristino..."),
            ("Settings.AutoLock", "Blocco automatico"),
            ("Settings.Disabled", "Disattivato"), ("Settings.AfterOneMinute", "Dopo 1 minuto"),
            ("Settings.AfterMinutes5", "Dopo 5 minuti"), ("Settings.AfterMinutes15", "Dopo 15 minuti"),
            ("Settings.AfterMinutes30", "Dopo 30 minuti"),
            ("Settings.SectionAppearance", "ASPETTO"), ("Settings.Language", "Lingua"),
            ("Settings.ClipboardClear", "Pulizia degli appunti"),
            ("Settings.ClipboardClear.After15", "Dopo 15 secondi"),
            ("Settings.ClipboardClear.After30", "Dopo 30 secondi"),
            ("Settings.ClipboardClear.After60", "Dopo 60 secondi"),
            ("Settings.SectionData", "DATI"),
            ("Settings.ImportCsv", "Importa da CSV / altro gestore..."),
            ("Settings.ConnectDatabase", "Connetti database..."),
            ("Settings.ConnectDatabaseTooltip", "Funzione self-hosted/condivisa — per sincronizzare solo i tuoi dispositivi, usa la Sincronizzazione tramite cartella."),
            ("Settings.DisconnectDatabase", "Disconnetti database"),
            ("Settings.EnableWindowsHello", "Attiva Windows Hello..."),
            ("Settings.DisableWindowsHello", "Disattiva Windows Hello"),
            ("Settings.OnlineIcons", "Icone online dei servizi"),
            ("Settings.OnlineIconsTooltip", "Scarica da internet l'icona reale di ogni servizio. Disattivato, la cassaforte mostra solo le iniziali e non accede mai alla rete."),
            ("Settings.TrackUsageHistory", "Registra cronologia di utilizzo"),
            ("Settings.TrackUsageHistoryTooltip", "Registra la data dell'ultima copia di password, nome utente e codice TOTP di ogni credenziale. Disattiva per smettere di registrare nuove date — quelle già salvate restano visibili."),
            ("Settings.CheckUpdates", "Verifica aggiornamenti"),
            ("Settings.CheckUpdatesTooltip", "Controlla le release di GitHub per segnalare una versione più recente. Disattivato per impostazione predefinita; non viene scaricato nulla automaticamente e non viene inviato nulla oltre a questa verifica."),
            ("Update.Available", "Nuova versione disponibile: {0}"),
            ("Update.Now", "Aggiorna ora"),
            ("Update.Downloading", "Scaricamento..."),
            ("Update.Failed", "Non è stato possibile aggiornare automaticamente. Apertura della pagina delle release per scaricarlo manualmente."),
            ("Update.Dismiss", "Ignora avviso di aggiornamento"),
            ("Icons.ConsentMessage", "Per mostrare l'icona reale di ogni servizio, l'app interroga il servizio di icone di Google inviando solo il dominio del sito (ad esempio, github.com). Nessuna password, nome utente o altro dato lascia il tuo computer, e le icone scaricate vengono salvate nella cache su disco per evitare nuove richieste.\n\nAttivare il recupero delle icone online?"),
            ("Privacy.Enable", "Attiva modalità privacy"), ("Privacy.Disable", "Disattiva modalità privacy"),
            ("Settings.LockNow", "Blocca ora"),
            ("Settings.SectionHelp", "AIUTO"),
            ("Settings.KeyboardShortcuts", "Scorciatoie da tastiera..."),
            ("Settings.SectionDanger", "ZONA PERICOLOSA"),
            ("Settings.ClearVault", "Pulisci cassaforte..."),
            ("Settings.DeleteVault", "Elimina cassaforte..."),
            ("Shortcuts.Title", "Scorciatoie da tastiera"),
            ("Shortcuts.Search", "Cerca"),
            ("Shortcuts.NewPassword", "Nuova password"),
            ("Shortcuts.OpenGenerator", "Apri il generatore"),
            ("Shortcuts.LockNow", "Blocca ora"),
            ("Shortcuts.PrivacyMode", "Attiva/disattiva modalità privacy"),
            ("Shortcuts.CopyUser", "Copia l'utente della riga selezionata"),
            ("Shortcuts.CopyPassword", "Copia la password della riga selezionata"),
            ("Shortcuts.CloseDialog", "Chiudi la finestra o annulla"),
            ("Shortcuts.SelectedRowHint", "La \"riga selezionata\" è quella con il focus da tastiera; se nessuna è selezionata, le scorciatoie di copia usano la prima riga dell'elenco."),
            ("Backup.Title", "Backup della cassaforte"),
            ("Backup.Frequency", "Frequenza del backup automatico"),
            ("Backup.Manual", "Solo manuale"), ("Backup.Daily", "Giornaliero"), ("Backup.Weekly", "Settimanale"),
            ("Backup.MaxKept", "Numero massimo di backup conservati"),
            ("Backup.Now", "Esegui backup ora"),
            ("Backup.NeverDone", "Nessun backup ancora eseguito."),
            ("Backup.LastDone", "Ultimo backup: {0}"),
            ("Backup.Available", "Backup disponibili"),
            ("Backup.None", "Nessun backup ancora disponibile."),
            ("Backup.Restore", "Ripristina"),
            ("Backup.RestoreFrom", "Ripristina il backup del {0}"),
            ("Backup.RestoreTitle", "Ripristina backup"),
            ("Backup.RestoreConfirm", "Questo sostituirà tutte le password della cassaforte con quelle del backup del {0}. Le modifiche fatte dopo quella data andranno perse. Continuare?"),
            ("Backup.RestoreSuccess", "Backup ripristinato con successo."),
            ("Backup.RestoreDisabledDbConnected", "Disconnetti il database per ripristinare un backup."),
            ("Backup.Success", "Backup creato con successo."),
            ("Backup.Error", "Errore durante l'elaborazione del backup: {0}"),

            ("Settings.Sync", "Sincronizzazione..."),
            ("Sync.Title", "Sincronizzazione tra dispositivi"),
            ("Sync.Explanation", "Sincronizza la cassaforte con altri dispositivi tramite una cartella condivisa (es.: Dropbox, OneDrive, Google Drive). I dati sono cifrati end-to-end con la password principale prima di lasciare questo dispositivo — il provider cloud non vede mai il testo in chiaro."),
            ("Sync.Enable", "Scegli cartella e attiva"),
            ("Sync.Folder", "Cartella di sincronizzazione"),
            ("Sync.Frequency", "Sincronizza automaticamente"),
            ("Sync.EveryMinutes", "Ogni {0} minuti"),
            ("Sync.Now", "Sincronizza ora"),
            ("Sync.LastDone", "Ultima sincronizzazione: {0}"),
            ("Sync.NeverDone", "Non ancora sincronizzato."),
            ("Sync.ChooseFolder", "Scegli la cartella di sincronizzazione"),
            ("Sync.EnableError", "Errore durante l'attivazione della sincronizzazione: {0}"),
            ("Sync.Error.WriteFailed", "Impossibile scrivere il file di sincronizzazione. Verifica che la cartella sia accessibile."),
            ("Sync.Success", "Sincronizzazione completata con successo."),
            ("Sync.AlreadyInProgress", "C'è già una sincronizzazione in corso. Aspetta che termini prima di tentare di nuovo."),
            ("Sync.Error", "Errore di sincronizzazione. Verifica che la cartella sia accessibile."),
            ("Sync.Disable", "Disattiva sincronizzazione"),
            ("Sync.DisableConfirm", "Disattivare la sincronizzazione? I dispositivi smettono di scambiare dati tra loro, ma nulla viene eliminato."),
            ("Sync.ConfirmMasterTitle", "Conferma password principale"),
            ("Sync.ConfirmMasterInstruction", "Inserisci la password principale di questa cassaforte per attivare la sincronizzazione. Usa la stessa password principale su tutti i dispositivi che condividono questa cartella."),
            ("Sync.Confirm", "Conferma"),
            ("Sync.ConflictsTooltip", "Visualizza l'attività di sincronizzazione"),
            ("Sync.ConflictsTitle", "Attività di sincronizzazione"),
            ("Sync.ConflictsExplanation", "Voci aggiornate da un altro dispositivo/client durante l'ultima sincronizzazione con il database, rifiutate per un errore nella verifica di integrità, oppure senza firma di integrità registrata."),
            ("Sync.ConflictType.ConcurrentEdit", "Aggiornato da un altro dispositivo"),
            ("Sync.ConflictType.IntegrityViolated", "Dato rifiutato: verifica di integrità non riuscita"),
            ("Sync.ConflictType.IntegrityMissing", "Nessuna firma di integrità — verificare che non sia stato alterato"),
            ("Vault.Header", "Cassaforte password"), ("Vault.ImportTooltip", "Importa password da un file"),
            ("Vault.ExportTooltip", "Esporta password in un file cifrato"),
            ("Vault.NewPassword", "Nuova password"),
            ("Vault.SearchWatermark", "Cerca per servizio, utente o categoria"),
            ("Vault.BreachTooltip", "Verifica password trapelate (Have I Been Pwned)"),
            ("Vault.AuditTooltip", "Controlla password deboli, riutilizzate o vecchie"),
            ("Vault.SecurityReportTooltip", "Rapporto di sicurezza del caveau"),
            ("Vault.FavoritesOnlyTooltip", "Solo preferite"),
            ("Vault.TagFilter", "Filtra per etichetta"),
            ("Vault.Table.Service", "SERVIZIO"), ("Vault.Table.User", "UTENTE"),
            ("Vault.Table.Category", "CATEGORIA"),
            ("Vault.Table.Actions", "AZIONI"),
            ("Vault.Table.Strength", "FORZA"),
            ("Vault.SortTooltip", "Ordina"),
            ("Nav.Vault", "Cassaforte"),
            ("Nav.Favorites", "Preferite"),
            ("Nav.Recent", "Recenti"),
            ("Nav.Categories", "CATEGORIE"),
            ("Nav.Toggle", "Attiva/disattiva navigazione"),
            ("Details.Title", "Dettagli"),
            ("Details.Close", "Chiudi dettagli"),
            ("Details.Save", "Salva modifiche"),
            ("Details.Delete", "Elimina"),
            ("Details.FullEdit", "Modifica completa..."),
            ("Generator.Close", "Chiudi generatore"),
            ("Row.CopyUrl", "Copia URL"),
            ("Footer.AutoLockOff", "Blocco automatico disattivato"),
            ("Footer.AutoLockCountdown", "{0} min al blocco automatico"),
            ("Vault.Empty", "Nessuna password nella cassaforte.\nFai clic su \"Nuova password\" per iniziare."),
            ("Vault.Filter.All", "Tutte"), ("Vault.Counter.ItemSingular", "{0} elemento"),
            ("Vault.Counter.ItemPlural", "{0} elementi"),
            ("Batch.CountSingular", "{0} selezionato"),
            ("Batch.CountPlural", "{0} selezionati"),
            ("Batch.Favorite", "Aggiungi ai preferiti"),
            ("Batch.AddTag", "Aggiungi etichetta"),
            ("Batch.AddTagWatermark", "Nome dell'etichetta"),
            ("Batch.Trash", "Sposta nel cestino"),
            ("Batch.TrashConfirm", "Spostare {0} credenziali nel cestino? Potrai ripristinarle o eliminarle definitivamente da lì."),
            ("Batch.CancelSelection", "Annulla selezione"),
            ("Vault.Status", "{0} {1} • {2} {3}"),
            ("Vault.Status.PasswordSingular", "password"), ("Vault.Status.PasswordPlural", "password"),
            ("Vault.Status.FavoriteSingular", "preferita"), ("Vault.Status.FavoritePlural", "preferite"),
            ("Vault.Status.AuditOk", "audit OK"), ("Vault.Status.WithAlert", "{0} con avviso"),
            ("Vault.Connection.Local", "Cassaforte cifrata"),
            ("Vault.Connection.Connected", "Connesso: {0}"),
            ("Vault.Connection.DatabaseUnavailable", "Database non disponibile - uso cassaforte locale"),
            ("Generator.Title", "Generatore di password"), ("Generator.Mode", "Modalità"),
            ("Generator.Mode.Password", "Password"), ("Generator.Mode.Passphrase", "Frase password"),
            ("Generator.Strength", "Forza"), ("Generator.Quantity", "Quantità"),
            ("Generator.Length", "Lunghezza"), ("Generator.Uppercase", "Lettere maiuscole (A-Z)"),
            ("Generator.Lowercase", "Lettere minuscole (a-z)"), ("Generator.Numbers", "Numeri (0-9)"),
            ("Generator.Special", "Caratteri speciali (!@#)"), ("Generator.Words", "Parole"),
            ("Generator.Separator", "Separatore"), ("Generator.Separator.Space", "spazio"),
            ("Generator.Capitalize", "Iniziali maiuscole"), ("Generator.AddNumber", "Aggiungi numero"),
            ("Generator.GeneratePassword", "Genera nuova password"),
            ("Generator.GeneratePassphrase", "Genera frase password"),
            ("Generator.SaveToVault", "Salva nella cassaforte"), ("Generator.Clear", "Pulisci"),
            ("Generator.CopyAll", "Copia tutte"),
            ("Generator.PasswordsGenerated", "Password generate ({0})"),
            ("Generator.PassphrasesGenerated", "Frasi password generate ({0})"),
            ("Generator.StrengthWeak", "Debole"), ("Generator.StrengthMedium", "Media"),
            ("Generator.StrengthStrong", "Forte"), ("Generator.StrengthExcellent", "Eccellente"),
            ("Generator.Item.Password", "password"), ("Generator.Item.Passphrase", "frase password"),
            ("Generator.GenerateFirst", "Genera prima una {0}"),
            ("Generator.PasswordCopied", "Password copiata!"),
            ("Generator.PassphraseCopied", "Frase password copiata!"),
            ("Generator.PasswordCopiedClearing", "Password copiata! Sarà cancellata dagli appunti tra {0} secondi."),
            ("Generator.PassphraseCopiedClearing", "Frase password copiata! Sarà cancellata dagli appunti tra {0} secondi."),
            ("Login.SubtitleCreate", "Crea una password principale per proteggere la cassaforte"),
            ("Login.SubtitleUnlock", "Inserisci la password principale per sbloccare"),
            ("Login.MasterPassword", "Password principale"), ("Login.ConfirmPassword", "Conferma password"),
            ("Login.CreateVault", "Crea cassaforte"), ("Login.Unlock", "Sblocca"),
            ("Login.WindowsHello", "Sblocca con Windows Hello"),
            ("Login.EnableWindowsHello", "Attiva Windows Hello"),
            ("Login.WindowsHelloHint", "Usa impronta, volto o PIN per sbloccare più rapidamente."),
            ("Login.FirstRunNotice", "Conserva bene questa password: non viene mai inviata né salvata su alcun server e non esiste modo di recuperare la cassaforte se la dimentichi. La prossima schermata offre un backup di emergenza tramite codice QR."),
            ("Login.Error.PasswordLength", "La password deve avere almeno 8 caratteri."),
            ("Login.Error.PasswordMismatch", "Le password non coincidono."),
            ("Login.Error.MasterPasswordRequired", "Inserisci la password principale."),
            ("Login.Error.TooManyAttempts", "Troppi tentativi. Attendi 5 secondi."),
            ("Login.Error.WrongPassword", "Password errata. Tentativo {0} di 5."),
            ("Login.RestoreFromDatabase", "Ripristina da un database"),
            ("Login.RestoreTitle", "Ripristina cassaforte"),
            ("Login.RestoreInstruction", "Inserisci la password principale di questa cassaforte per ripristinarla dal database:"),
            ("Login.RestoreConfirm", "Ripristina"),

            ("Entry.NewTitle", "Nuova password"), ("Entry.EditTitle", "Modifica password"),
            ("Entry.EditTitleWithService", "Modifica password - {0}"),
            ("Entry.ServiceName", "Nome del servizio"), ("Entry.UserEmail", "Utente / E-mail"),
            ("Entry.Password", "Password"),
            ("Entry.PasswordKeepCurrent", "Password  (lascia vuoto per mantenere l'attuale)"),
            ("Entry.PasswordKeepCurrentFormat", "{0}  (lascia vuoto per mantenere l'attuale)"),
            ("Entry.TotpOptional", "Autenticazione a due fattori (2FA)  (opzionale)"),
            ("Entry.TotpRemove", "Autenticazione a due fattori (2FA)  (vuoto rimuove)"),
            ("Entry.TotpLabel", "Codice di verifica (2FA)"),
            ("Entry.TotpWatermark", "Incolla la chiave segreta o il link otpauth://"),
            ("Entry.TotpExpiresIn", "scade tra {0}s"), ("Entry.Category", "Categoria"),
            ("Entry.TagsOptional", "Etichette  (opzionale)"),
            ("Entry.TagsWatermark", "Es.: lavoro, importante, cliente-x"),
            ("Entry.UrlOptional", "URL  (opzionale)"), ("Entry.NotesOptional", "Note  (opzionale)"),
            ("Entry.Usage.Created", "Creata il {0}"), ("Entry.Usage.Updated", "Modificata il {0}"),
            ("Entry.Usage.CopyPasswordLabel", "Password copiata: {0}"), ("Entry.Usage.CopyUserLabel", "Nome utente copiato: {0}"),
            ("Entry.Usage.CopyTotpLabel", "TOTP copiato: {0}"), ("Entry.Usage.Never", "mai"),
            ("Entry.CreateRequired", "Compila i campi obbligatori (nome, utente e password)."),
            ("Entry.EditRequired", "Compila i campi obbligatori."),
            ("Entry.TotpInvalid", "La chiave di autenticazione a due fattori non è valida. Incolla la chiave segreta (Base32) o un link otpauth://."),
            ("Entry.CreateError", "Errore durante la creazione della password: {0}"),
            ("Entry.UpdateError", "Errore durante l'aggiornamento della password: {0}"),
            ("Entry.RecoverCurrentPasswordError", "Impossibile recuperare la password attuale. Inserisci una nuova password."),
            ("Entry.Detail.DiscardChangesTitle", "Scartare le modifiche?"),
            ("Entry.Detail.DiscardChangesConfirm", "Ci sono modifiche non salvate in questa credenziale. Continuando, verranno scartate."),
            ("Entry.Detail.ConcurrentChangeTitle", "Modificata altrove"),
            ("Entry.Detail.ConcurrentChangeConfirm", "Questa credenziale è stata modificata (dalla sincronizzazione o da un altro dispositivo) mentre la stavi modificando. Salvare ora sovrascriverà quella modifica. Continuare comunque?"),
            ("Entry.HistoryHeader", "Cronologia delle password ({0})"),
            ("Entry.HistoryReplacedOn", "Sostituita il {0}"),
            ("Entry.HistoryUse", "Usa"),
            ("Entry.HistoryUseTooltip", "Compila il campo con questa password"),
            ("A11y.PreviousPassword", "Password precedente"),

            ("Entry.RecoveryCodes", "Codici di ripristino"),
            ("Entry.RecoveryCodesWatermark", "Incolla un codice per riga"),
            ("Entry.RecoveryCodesAdd", "Aggiungi"),
            ("Entry.RecoveryCodeMarkUsed", "Segna come usato"),
            ("Entry.RecoveryCodeUnmark", "Rimuovi contrassegno"),
            ("Entry.RecoveryCodeRemove", "Rimuovi"),
            ("Entry.RecoveryCodeRemoveConfirm", "Rimuovere questo codice di ripristino? Questa azione non può essere annullata."),
            ("Entry.RecoveryCodesAddError", "Errore durante l'aggiunta dei codici di ripristino: {0}"),
            ("Entry.RecoveryCodeMarkError", "Errore durante l'aggiornamento del codice di ripristino: {0}"),
            ("Entry.RecoveryCodeRemoveError", "Errore durante la rimozione del codice di ripristino: {0}"),
            ("Entry.Attachments", "Allegati"),
            ("Entry.AttachmentsAdd", "Aggiungi allegato..."),
            ("Entry.AttachmentDownload", "Scarica"),
            ("Entry.AttachmentRemove", "Rimuovi"),
            ("Entry.AttachmentRemoveConfirm", "Rimuovere l'allegato \"{0}\"? Questa azione non può essere annullata."),
            ("Entry.AttachmentAddError", "Errore durante l'aggiunta dell'allegato: {0}"),
            ("Entry.AttachmentDownloadError", "Errore durante il download dell'allegato: {0}"),
            ("Entry.AttachmentRemoveError", "Errore durante la rimozione dell'allegato: {0}"),
            ("A11y.RecoveryCode", "Codice di ripristino"),

            ("Entry.Type", "Tipo di credenziale"),
            ("CredType.Login", "Accesso"),
            ("CredType.Cartao", "Carta"),
            ("CredType.ChaveLicenca", "Chiave di licenza"),
            ("CredType.WiFi", "Wi-Fi"),
            ("CredType.Servidor", "Server"),
            ("CredType.BancoDados", "Database"),
            ("CredField.CardHolder", "Intestatario della carta"),
            ("CredField.CardNumber", "Numero della carta"),
            ("CredField.Product", "Prodotto / Software"),
            ("CredField.LicenseKey", "Chiave di licenza"),
            ("CredField.Ssid", "Nome della rete (SSID)"),
            ("CredField.WifiPassword", "Password della rete"),
            ("CredField.Validade", "Scadenza"),
            ("CredField.Cvv", "CVV"),
            ("CredField.Bandeira", "Circuito della carta"),
            ("CredField.Seguranca", "Sicurezza"),
            ("CredField.Banda", "Banda"),
            ("CredField.Host", "Host"),
            ("CredField.Porta", "Porta"),
            ("CredField.Protocolo", "Protocollo"),
            ("CredField.NomeBanco", "Nome del database"),
            ("CredField.Motor", "Motore"),
            ("ExportDialog.ExportTitle", "Esporta password"),
            ("ExportDialog.ImportTitle", "Importa password"),
            ("ExportDialog.ExportPassword", "Password di esportazione"),
            ("ExportDialog.Password", "Password"),
            ("ExportDialog.InfoExport", "Definisci una password per proteggere il file. Sarà richiesta durante l'importazione - conservala bene, perché senza di essa il file non può essere aperto."),
            ("ExportDialog.OnlyFiltered", "Esporta solo gli elementi filtrati nella lista ({0} di {1})"),
            ("ExportDialog.InfoImport", "Inserisci la password definita quando il file è stato esportato."),
            ("ExportDialog.PasswordRequired", "Inserisci la password."),
            ("ExportDialog.PasswordLength", "La password deve avere almeno 8 caratteri."),
            ("ExportDialog.PasswordMismatch", "Le password non coincidono."),
            ("Master.ChangeTitle", "Cambia password principale"),
            ("Master.KdfUpgradeTitle", "Rafforzamento della sicurezza"),
            ("Master.CurrentPassword", "Password principale attuale"),
            ("Master.NewPassword", "Nuova password principale"),
            ("Master.ConfirmNewPassword", "Conferma nuova password"),
            ("Master.ErrorCurrentRequired", "Inserisci la password principale attuale."),
            ("Master.ErrorNewLength", "La nuova password deve avere almeno 8 caratteri."),
            ("Master.ErrorConfirmMismatch", "La conferma non coincide con la nuova password."),
            ("Master.ChangeError", "Errore durante il cambio della password principale: {0}"),
            ("Master.ChangedRestart", "Password principale cambiata con successo.\n\nL'applicazione verrà riavviata per applicare la nuova password."),
            ("Master.ItemsDiscardedWarning", "Alcuni elementi con dati danneggiati (cronologia, campo extra, codice di recupero o allegato) non sono stati recuperabili e sono stati scartati durante il cambio."),
            ("Master.OtherDevicesWarning", "Se questo cofre è connesso a un database o a una cartella di sincronizzazione condivisa con altri dispositivi, aggiorna la password principale anche su di essi dopo il riavvio — altrimenti non riusciranno più a leggere ciò che viene sincronizzato da questo dispositivo da ora in poi."),
            ("Biometric.Title", "Windows Hello"),
            ("Biometric.EnableOffer", "Vuoi attivare lo sblocco con Windows Hello su questo dispositivo?\n\nLa password principale continuerà a funzionare come alternativa."),
            ("Biometric.Enabled", "Lo sblocco con Windows Hello è attivo su questo dispositivo."),
            ("Biometric.Disabled", "Lo sblocco con Windows Hello è disattivato su questo dispositivo."),
            ("Biometric.DisableConfirm", "Disattivare lo sblocco con Windows Hello su questo dispositivo?"),
            ("Biometric.DisabledAfterMasterChange", "Lo sblocco con Windows Hello è stato disattivato e potrà essere riattivato dopo il riavvio."),
            ("Biometric.DisabledAfterKdfUpgrade", "La tua cassaforte ha ricevuto un rafforzamento di sicurezza nella derivazione della chiave. Lo sblocco con Windows Hello è stato disattivato e può essere riattivato ora dal menu delle impostazioni."),
            ("Biometric.NotEnabled", "Lo sblocco con Windows Hello non è attivo."),
            ("Biometric.InvalidVaultKey", "La chiave della cassaforte non è valida per attivare Windows Hello."),
            ("Biometric.InvalidRegistration", "La registrazione di Windows Hello non corrisponde più a questa cassaforte. Accedi con la password principale e riattivala."),
            ("Biometric.EnableError", "Errore durante l'attivazione di Windows Hello: {0}"),
            ("Biometric.UnlockError", "Errore durante lo sblocco con Windows Hello: {0}"),
            ("Biometric.UnsupportedPlatform", "Windows Hello è disponibile solo su Windows 10 o versioni successive."),
            ("Biometric.AvailabilityError", "Impossibile verificare la disponibilità di Windows Hello: {0}"),
            ("Biometric.NotConfigured", "Configura un PIN, la biometria o Windows Hello nelle impostazioni di Windows."),
            ("Biometric.RetriesExhausted", "Troppi tentativi di verifica. Riprova più tardi."),
            ("Biometric.Unavailable", "Windows Hello non è disponibile al momento."),
            ("Qr.RegenerateTitle", "Rigenera codice QR"),
            ("Qr.RegenerateInstruction", "Conferma la password principale per generare un nuovo codice QR di backup."),
            ("Qr.GenerateButton", "Genera codice QR"),
            ("Qr.ErrorMasterRequired", "Inserisci la password principale."),
            ("Qr.ErrorMasterIncorrect", "Password principale errata."),
            ("Qr.BackupTitle", "Backup della password principale"),
            ("Qr.BackupTitleWithType", "Backup della password principale (codice QR)"),
            ("Qr.Offer", "Vuoi salvare un codice QR di backup della password principale?\n\nATTENZIONE: il codice QR contiene la versione frase password della tua password principale. Chiunque scansioni l'immagine potrà ricostruire la password e accedere alla cassaforte.\n\nConserva il file in un luogo sicuro e offline (o stampato) - mai in cloud, e-mail o cartelle condivise."),
            ("Qr.SavePickerTitle", "Salva codice QR della password principale"),
            ("Qr.SaveSuccess", "Codice QR salvato con successo. Conservalo in un luogo sicuro."),
            ("Qr.SaveError", "Impossibile salvare il codice QR: {0}"),
            ("Qr.CloudFolderWarning", "Questa cartella è sincronizzata con {0}. Salvare il codice QR qui invia la password principale (in forma ricostruibile) al cloud. Continuare comunque?"),
            ("Qr.SheetSubtitle", "Backup della password principale"),
            ("Qr.SheetWarning1", "Contiene la versione frase password della password principale."),
            ("Qr.SheetWarning2", "Conserva in un luogo sicuro e offline."),
            ("Db.SelectTitle", "Connetti database"), ("Db.ChooseType", "Scegli il tipo di database da connettere."),
            ("Db.SelectExplanation", "Una funzione per uso self-hosted o condiviso: collega la cassaforte a un proprio database, utile per un server personale o per condividere l'accesso con altre persone di fiducia. Per sincronizzare solo i propri dispositivi senza mantenere un database, usa la Sincronizzazione tramite cartella condivisa nel menu delle impostazioni."),
            ("Db.ConnectionTitle", "Connessione"), ("Db.ConnectProviderTitle", "Connetti - {0}"),
            ("Db.TestConnection", "Test connessione"), ("Db.DatabaseFile", "File database (.db)"),
            ("Db.Browse", "Sfoglia..."), ("Db.Host", "Host"), ("Db.Port", "Porta"),
            ("Db.Database", "Database"), ("Db.User", "Utente"), ("Db.Password", "Password"),
            ("Db.RequireValidCertificate", "Richiedi certificato del server valido"),
            ("Db.RequireValidCertificateHelp", "Disattivato (predefinito): la connessione è sempre cifrata, ma accetta un certificato autofirmato — comune per un database locale o sulla rete interna. Attiva per richiedere un certificato validato da un'autorità affidabile, consigliato per un database fuori dalla tua rete."),
            ("Db.SQLitePickerTitle", "File database SQLite"),
            ("Db.ConnectionSuccess", "Connessione riuscita."),
            ("Db.CreateTableTitle", "Crea tabella"),
            ("Db.TableMissing", "La tabella \"{0}\" non esiste in questo database.\n\nVuoi crearla ora?"),
            ("Db.ConnectionCanceledNoTable", "Connessione annullata: la tabella non esiste."),
            ("Db.RestoreTableMissing", "Questo database non ha la cassaforte prevista — la tabella non esiste. Controlla i dati di connessione."),
            ("Db.RestoreNoAuthPublished", "Questo database non ha ancora una password principale pubblicata per il ripristino. Collega prima, a questo database, un dispositivo che abbia già questa cassaforte sbloccata — la pubblicazione avviene da sola alla prossima connessione."),
            ("Db.ErrorFileRequired", "Indica il file del database."),
            ("Db.ErrorFieldsRequired", "Compila host, database e utente."),
            ("Db.ErrorInvalidPort", "Porta non valida."),
            ("Db.ConnectionFailed", "Connessione non riuscita: {0}"),
            ("Db.CannotConnect", "Impossibile connettersi: {0}"),
            ("Db.Error.ConnectionFailed", "Impossibile connettersi al database. Controlla host, porta e credenziali."),
            ("Db.Error.SchemaFailed", "Impossibile creare o aggiornare la tabella della cassaforte nel database."),
            ("Db.FeatureUnavailable", "Funzione non disponibile in questa sessione."),
            ("Db.ConnectedMessage", "Connesso al database — i dati ora vengono rispecchiati con questo database condiviso.\n\n{0}"),
            ("Db.ConnectError", "Errore durante la connessione: {0}"),
            ("Message.LoadError", "Errore durante il caricamento: {0}"),
            ("Message.FavoriteError", "Errore durante la modifica del preferito: {0}"),
            ("Message.PinError", "Errore durante l'aggiunta ai fissati: {0}"),
            ("Message.DeleteTitle", "Elimina password"),
            ("Message.MoveToTrash", "La credenziale sarà spostata nel cestino. Da lì potrai ripristinarla o eliminarla definitivamente."),
            ("Message.DeletePrompt", "Eliminare \"{0}\"?\n\n{1}"),
            ("Message.DeleteError", "Errore durante l'eliminazione della password: {0}"),
            ("Nav.Trash", "Cestino"),
            ("Trash.Empty", "Il cestino è vuoto."),
            ("Trash.DeletedOn", "Eliminata il {0}"),
            ("Trash.Restore", "Ripristina"),
            ("Trash.RestoreError", "Errore durante il ripristino: {0}"),
            ("Trash.DeleteForever", "Elimina definitivamente"),
            ("Trash.DeleteForeverConfirm", "Eliminare definitivamente \"{0}\"?\n\nQuesta azione non può essere annullata."),
            ("Trash.DeleteForeverError", "Errore durante l'eliminazione definitiva: {0}"),
            ("Trash.EmptyButton", "Svuota cestino"),
            ("Trash.EmptyConfirmTitle", "Svuota cestino"),
            ("Trash.EmptyConfirm", "Eliminare definitivamente tutti gli elementi nel cestino?\n\nQuesta azione non può essere annullata."),
            ("Trash.EmptyError", "Errore durante lo svuotamento del cestino: {0}"),

            ("Vault.ClearTitle", "Pulisci cassaforte"),
            ("Vault.ClearConfirm", "Spostare tutte le password della cassaforte nel cestino?\n\nPotrai ripristinarle dal cestino in seguito, se necessario."),
            ("Vault.ClearError", "Errore durante la pulizia della cassaforte: {0}"),
            ("Vault.DeleteTitle", "Elimina cassaforte"),
            ("Vault.DeleteReauthInstruction", "Inserisci la password principale attuale per continuare."),
            ("Vault.DeleteReauthButton", "Continua"),
            ("Vault.DeleteConfirm", "Eliminare definitivamente la cassaforte?\n\nTutte le password, la password principale, i backup e gli allegati verranno cancellati, e lo sblocco con Windows Hello verrà disattivato. Questa azione non può essere annullata."),
            ("Vault.DeleteError", "Errore durante l'eliminazione della cassaforte: {0}"),
            ("Vault.DeletedRestart", "Cassaforte eliminata. L'applicazione verrà riavviata."),
            ("Message.RenameDecryptError", "Impossibile decifrare la password per salvare la modifica."),
            ("Message.RenameError", "Errore durante la rinomina del servizio: {0}"),
            ("Message.AuditTitle", "Audit della cassaforte"),
            ("Message.AuditNoPasswords", "Non ci sono password nella cassaforte da controllare."),
            ("Message.AuditSuccess", "Audit completato: nessuna password debole, riutilizzata o vecchia tra {0} password."),
            ("Message.AuditIncomplete", "{0} password non sono state analizzate completamente."),
            ("Message.AuditFoundHeader", "Trovate {0} voce/i con avviso in {1} password:"),
            ("Message.AuditWeakLine", "- {0} deboli"),
            ("Message.AuditRepeatedLine", "- {0} riutilizzate"),
            ("Message.AuditOldLine", "- {0} vecchie"),
            ("Message.AuditUnreadableLine", "- {0} non controllate per errore di lettura"),
            ("Message.AuditMarked", "Le voci interessate sono state marcate con ⚠ nell'elenco."),
            ("Message.AuditOldDefinition", "Le password vecchie non sono state aggiornate da {0} giorni o più."),
            ("Message.AuditError", "Errore durante l'audit della cassaforte: {0}"),

            ("SecurityReport.Title", "Rapporto di sicurezza"),
            ("SecurityReport.ScoreLabel", "Punteggio del caveau"),
            ("SecurityReport.TrendLabel", "Andamento del punteggio"),
            ("SecurityReport.ScoreWeak", "Richiede attenzione"),
            ("SecurityReport.ScoreMedium", "Discreto"),
            ("SecurityReport.ScoreStrong", "Buono"),
            ("SecurityReport.ScoreExcellent", "Eccellente"),
            ("SecurityReport.Weak", "Password deboli"),
            ("SecurityReport.Repeated", "Password riutilizzate"),
            ("SecurityReport.Old", "Password vecchie"),
            ("SecurityReport.Compromised", "Password compromesse"),
            ("SecurityReport.NoTotp", "Senza autenticazione a due fattori"),
            ("SecurityReport.NoUrl", "Senza URL salvato"),
            ("SecurityReport.NoCategory", "Senza categoria definita"),
            ("SecurityReport.CertNotRequired", "La connessione al database non richiede un certificato del server valido. Il traffico resta cifrato, ma resta vulnerabile a un attacco man-in-the-middle. Attiva \"Richiedi certificato valido del server\" nella schermata di connessione al database."),
            ("SecurityReport.RowAutomationName", "{0}: {1}"),
            ("SecurityReport.CheckBreaches", "Verifica violazioni ora"),
            ("SecurityReport.BreachesNotChecked", "Non ancora verificato in questa sessione"),
            ("SecurityReport.AllGood", "Nessun problema trovato. Continua così!"),
            ("SecurityReport.ClearFilter", "Rimuovi filtro"),
            ("SecurityReport.FilterActive", "Filtrato per: {0}"),
            ("SecurityReport.BreachCheckError", "Errore durante la verifica delle violazioni: {0}"),
            ("Message.BreachTitle", "Verifica fughe"),
            ("Message.BreachNoPasswords", "Non ci sono password nella cassaforte da verificare."),
            ("Message.BreachDoneTitle", "Verifica completata"),
            ("Message.BreachSuccess", "Buone notizie! Nessuna delle {0} password verificate è stata trovata in fughe note."),
            ("Message.BreachWarning", "Attenzione: {0} di {1} password compaiono in fughe note. Valuta di cambiarle (marcate con ⚠)."),
            ("Message.NetworkErrorTitle", "Errore di rete"),
            ("Message.BreachNetworkError", "Impossibile verificare le fughe.\nControlla la connessione a internet.\n\nDettaglio: {0}"),
            ("Message.ExportEmpty", "La cassaforte è vuota. Non c'è nulla da esportare."),
            ("Message.ExportSuccess", "{0} password esportate con successo.\n\nConserva bene la password di esportazione - senza di essa il file non può essere aperto."),
            ("Message.ExportError", "Errore durante l'esportazione: {0}"),
            ("Message.ImportEmpty", "Nessuna password trovata nel file."),
            ("Message.ImportSuccess", "{0} password importate con successo."),
            ("Message.ImportIgnored", "{0} ignorate (dati incompleti o non validi)."),
            ("Message.ImportDuplicates", "{0} erano già presenti nella cassaforte."),
            ("Message.ImportError", "Errore durante l'importazione: {0}"),
            ("Message.CsvEmpty", "Nessuna credenziale trovata nel file."),
            ("Message.CsvConfirm", "Rilevato un file in formato {0} con {1} credenziale/i.\n\nLe password saranno aggiunte alla cassaforte (gli elementi esistenti vengono ignorati). Continuare?"),
            ("Message.CsvIgnored", "{0} ignorate (riga incompleta o non valida)."),
            ("Message.CsvDuplicates", "{0} erano già presenti nella cassaforte."),
            ("Message.CsvSecurity", "Per sicurezza, elimina il file CSV - conserva le password in testo semplice."),
            ("Import.Progress", "Importazione di {0} di {1}…"),
            ("Export.Progress", "Esportazione di {0} di {1}…"),
            ("Row.FavoriteRemove", "Rimuovi dai preferiti"), ("Row.FavoriteAdd", "Aggiungi ai preferiti"),
            ("Row.PinEntry", "Fissa in alto"), ("Row.UnpinEntry", "Rimuovi fissaggio"),
            ("Row.CopyUser", "Copia utente"), ("Row.EditService", "Modifica servizio"),
            ("Row.RevealPassword", "Mostra password"), ("Row.HidePassword", "Nascondi password"),
            ("Row.CopyPassword", "Copia password"), ("Row.EditEntry", "Modifica voce"),
            ("Row.DeleteEntry", "Elimina voce"), ("Row.CopyTotp", "Copia codice 2FA"),
            ("Row.CopyRecoveryCode", "Copia codice di ripristino"),
            ("Row.UserCopied", "Utente copiato"),
            ("Row.PasswordCopiedClearing", "Password copiata — cancellazione tra {0}s"),
            ("Row.CategoryTooltip", "Categoria: {0}"), ("Row.TagsTooltip", "Etichette: {0}\nCategoria: {1}"),
            ("Row.PasswordCompromised", "Password compromessa - trovata in {0:N0} fuga/fughe. Cambiala!"),
            ("Row.AuditPrefix", "Audit: {0}"), ("Row.NotFoundInBreaches", " (non trovata in fughe)"),
            ("Row.PasswordWeak", "Password debole"), ("Row.PasswordMedium", "Password media"),
            ("Row.PasswordStrong", "Password forte"), ("Row.AuditWeak", "password debole"),
            ("Row.AuditRepeatedWithCount", "password riutilizzata in {0} voci"),
            ("Row.AuditRepeated", "password riutilizzata"),
            ("Row.AuditOld", "non aggiornata da {0} giorni"), ("Row.AuditAlert", "avviso"),
            ("Category.Work", "Lavoro"), ("Category.Personal", "Personale"),
            ("Category.Finance", "Finanze"), ("Category.Social", "Social"), ("Category.Other", "Altro"),
            ("Access.Title", "Accessibilità"), ("Access.Colorblind", "Daltonismo"), ("Access.None", "Nessuno"),
            ("Access.Protanopia", "Protanopia"), ("Access.Deuteranopia", "Deuteranopia"), ("Access.Tritanopia", "Tritanopia"),
            ("Access.Monochromacy", "Monocromia"),
            ("Access.HighContrast", "Contrasto elevato"), ("Access.TextSize", "Dimensione del testo"),
            ("Access.TextNormal", "Normale"), ("Access.TextLarge", "Grande"), ("Access.TextLarger", "Più grande"),
            ("Access.ReduceMotion", "Riduci animazioni"), ("Access.ScreenReader", "Lettore schermo"),
            ("Access.ScreenReaderHelp", "Modalità più descrittiva per lettori schermo"), ("Access.Minimize", "Riduci a icona"),
            ("Access.Maximize", "Ingrandisci"), ("Access.Restore", "Ripristina"), ("Access.Close", "Chiudi finestra"),

            ("A11y.PasswordFieldHelp", "Campo protetto. Rivela la password solo in un luogo sicuro."),
            ("A11y.GeneratedPassword", "Password generata"),
            ("A11y.GeneratedPasswordHelp", "Il valore non viene annunciato automaticamente. Usa copia per inviarlo negli appunti."),
            ("A11y.GeneratedReady", "{0} {1}(e) generata(e). Usa copia per inviarle negli appunti."),
            ("A11y.GeneratedList", "Elenco password generate"),
            ("A11y.CopyGenerated", "Copia elemento generato"),
            ("A11y.CopyAllGenerated", "Copia tutti gli elementi generati"),
            ("A11y.Copied", "{0} copiato negli appunti."),
            ("A11y.CopiedWillClear", "{0} copiato. Verrà cancellato dagli appunti tra {1} secondi."),
            ("A11y.PasswordVisible", "Password visibile sullo schermo."),
            ("A11y.PasswordHidden", "Password nascosta."),
            ("A11y.PrivacyModeOn", "Modalità privacy attivata. Servizio, utente e categoria nascosti nell'elenco."),
            ("A11y.PrivacyModeOff", "Modalità privacy disattivata."),
            ("A11y.RowHelp", "Usa Tab per accedere alle azioni di questa voce."),
            ("A11y.SortByColumn", "Fai clic per ordinare in base a questa colonna."),
            ("A11y.EditServiceHelp", "Premi Invio per modificare il nome del servizio."),
            ("A11y.EditServiceMode", "Modifica del servizio in corso. Premi Invio per salvare o Esc per annullare."),
            ("A11y.SliderHelp", "Usa le frecce per regolare. Home e Fine vanno al minimo e al massimo."),
            ("A11y.ToggleOn", "Attivato"),
            ("A11y.ToggleOff", "Disattivato"),
            ("A11y.VaultStatus", "Stato della cassaforte"),
            ("A11y.ConnectionStatus", "Stato della connessione"),
            ("A11y.ResultsList", "Elenco password"),
            ("A11y.EmptyList", "Elenco vuoto"),
            ("A11y.OptionalField", "Campo facoltativo"),
            ("A11y.TotpPreview", "Anteprima del codice 2FA"),
            ("A11y.FilterOn", "Filtro attivato"),
            ("A11y.FilterOff", "Filtro disattivato"),
            ("A11y.ScreenReaderEnabled", "Lettore di schermo attivato."),
            ("A11y.ScreenReaderDisabled", "Lettore di schermo disattivato."),

            ("Entry.FieldDecryptError", "(impossibile decifrare questo campo)"),
            ("Entry.Error.ServiceRequired", "Il nome del servizio non può essere vuoto"),
            ("Entry.Error.UserRequired", "L'utente non può essere vuoto"),
            ("Entry.Error.PasswordRequired", "La password non può essere vuota"),
            ("Entry.Error.ServiceTooLong", "Il nome del servizio non può superare {0} caratteri"),
            ("Entry.Error.UserTooLong", "L'utente non può superare {0} caratteri"),
            ("Entry.Error.PasswordTooLong", "La password non può superare {0} caratteri"),
            ("Auth.Error.PasswordRequired", "La password principale non può essere vuota."),
            ("Auth.Error.PasswordTooShort", "La password principale deve avere almeno {0} caratteri."),
            ("Master.Error.NewPasswordTooShort", "La nuova password principale deve avere almeno {0} caratteri."),
            ("Master.Error.CurrentPasswordWrong", "La password principale attuale non è corretta."),
            ("Master.Error.CorruptedEntry", "La credenziale \"{0}\" è corrotta e non è stato possibile decifrarla — la modifica della password principale è stata annullata."),
            ("Export.Error.PasswordTooShort", "La password di esportazione deve avere almeno {0} caratteri."),
            ("Export.Error.FileNotFound", "File di importazione non trovato."),
            ("Export.Error.PasswordRequired", "Inserisci la password di esportazione."),
            ("Export.Error.InvalidFile", "File di importazione non valido o danneggiato."),
            ("Export.Error.WrongPassword", "Password di esportazione errata o file danneggiato."),
            ("Export.Error.InvalidContent", "Contenuto del file di importazione non valido."),
            ("Import.Error.FileNotFound", "File di importazione non trovato."),
            ("Import.Error.CannotRead", "Impossibile leggere il file di importazione."),
            ("Import.Error.EmptyFile", "Il file è vuoto."),
            ("Import.Error.NoCredentials", "Il file non contiene credenziali da importare."),
            ("Import.Error.NoPasswordColumn", "Impossibile identificare la colonna della password. Verifica che il file abbia una riga di intestazione con i nomi delle colonne."),
            ("Attachment.Error.NameRequired", "Il nome del file non può essere vuoto"),
            ("Attachment.Error.EmptyFile", "File vuoto"),
            ("Attachment.Error.FileTooLarge", "File più grande del limite di {0} MB per allegato"),
            ("Attachment.Error.MaxPerCredential", "Questa credenziale ha già il massimo di {0} allegati"),
            ("Attachment.Error.VaultLimit", "La cassaforte raggiungerebbe il limite di {0} MB di allegati"),
            ("Generator.Error.LengthRange", "La lunghezza della password deve essere tra 4 e 1000 caratteri."),
            ("Generator.Error.NoCharacterType", "Seleziona almeno un tipo di carattere."),
            ("Generator.Error.PassphraseWordsRange", "La passphrase deve avere tra 3 e 12 parole."),
            ("Generator.Error.SeparatorTooLong", "Il separatore può avere al massimo 3 caratteri."),
            ("Generator.Error.NotEnoughWords", "Fornisci un elenco con almeno due parole."),
            ("Generator.Error.QuantityRange", "La quantità deve essere tra 1 e 50."),
            ("Vault.Error.WrongKeyOrCorrupt", "Impossibile aprire la cassaforte: la chiave è errata o il file è stato danneggiato."),
            ("Vault.Error.CorruptData", "Il contenuto della cassaforte è danneggiato."),
            ("Vault.Error.IOFailure", "Impossibile accedere al file della cassaforte."),
            ("Vault.Error.BackupFailed", "Impossibile creare il backup della cassaforte.")
        });
    }
}
