namespace CofreDeSenhas
{
    internal static partial class Idioma
    {
        private static IReadOnlyDictionary<string, string> CriarDe() => Mesclar(new (string, string)[]
        {
            ("App.Title", "Passwort-Tresor"),
            ("Common.Save", "Speichern"), ("Common.Cancel", "Abbrechen"), ("Common.Change", "Ändern"),
            ("Common.Connect", "Verbinden"), ("Common.Export", "Exportieren"), ("Common.Import", "Importieren"),
            ("Common.Exit", "Beenden"), ("Common.Close", "Schließen"),
            ("Common.Warning", "Warnung"), ("Common.Error", "Fehler"), ("Common.Success", "Erfolg"),
            ("Common.Validation", "Validierung"), ("Common.Yes", "Ja"), ("Common.No", "Nein"),
            ("Common.AllFiles", "Alle Dateien"), ("Common.ExportedVaultFile", "Exportierter Tresor"),
            ("Common.CsvFile", "CSV-Datei"), ("Common.PngImage", "PNG-Bild"),
            ("Common.AndMore", "+{0} weitere"),
            ("Common.SQLiteDatabase", "SQLite-Datenbank"),
            ("Settings.Tooltip", "Einstellungen"), ("Settings.SectionSecurity", "SICHERHEIT"),
            ("Settings.ChangeMasterPassword", "Master-Passwort ändern..."),
            ("Settings.RegenerateQr", "QR-Code neu erzeugen..."), ("Settings.Backup", "Sicherung und Wiederherstellung..."),
            ("Settings.AutoLock", "Automatische Sperre"),
            ("Settings.Disabled", "Deaktiviert"), ("Settings.AfterOneMinute", "Nach 1 Minute"),
            ("Settings.AfterMinutes5", "Nach 5 Minuten"), ("Settings.AfterMinutes15", "Nach 15 Minuten"),
            ("Settings.AfterMinutes30", "Nach 30 Minuten"),
            ("Settings.SectionAppearance", "DARSTELLUNG"), ("Settings.Language", "Sprache"),
            ("Settings.ClipboardClear", "Zwischenablage leeren"),
            ("Settings.ClipboardClear.After15", "Nach 15 Sekunden"),
            ("Settings.ClipboardClear.After30", "Nach 30 Sekunden"),
            ("Settings.ClipboardClear.After60", "Nach 60 Sekunden"),
            ("Settings.SectionData", "DATEN"),
            ("Settings.ImportCsv", "Aus CSV / anderem Manager importieren..."),
            ("Settings.ConnectDatabase", "Datenbank verbinden..."),
            ("Settings.ConnectDatabaseTooltip", "Self-Hosted-/Freigabefunktion — verwenden Sie zur Synchronisierung Ihrer eigenen Geräte die Ordnersynchronisierung."),
            ("Settings.DisconnectDatabase", "Datenbank trennen"),
            ("Settings.EnableWindowsHello", "Windows Hello aktivieren..."),
            ("Settings.DisableWindowsHello", "Windows Hello deaktivieren"),
            ("Settings.OnlineIcons", "Online-Symbole der Dienste"),
            ("Settings.OnlineIconsTooltip", "Lädt das echte Symbol jedes Dienstes aus dem Internet. Deaktiviert zeigt der Tresor nur Initialen und greift nie auf das Netzwerk zu."),
            ("Settings.TrackUsageHistory", "Nutzungsverlauf aufzeichnen"),
            ("Settings.TrackUsageHistoryTooltip", "Zeichnet das Datum des letzten Kopierens von Passwort, Benutzername und TOTP-Code jeder Anmeldedaten auf. Deaktivieren, um keine neuen Einträge mehr aufzuzeichnen — bereits gespeicherte Daten bleiben sichtbar."),
            ("Settings.CheckUpdates", "Nach Updates suchen"),
            ("Settings.CheckUpdatesTooltip", "Fragt die GitHub-Releases ab, um auf eine neuere Version hinzuweisen. Standardmäßig deaktiviert; es wird nichts automatisch heruntergeladen und nichts außer dieser Abfrage gesendet."),
            ("Update.Available", "Neue Version verfügbar: {0}"),
            ("Update.Dismiss", "Update-Hinweis ausblenden"),
            ("Icons.ConsentMessage", "Um das echte Symbol jedes Dienstes anzuzeigen, fragt die App den Favicon-Dienst von Google ab und sendet dabei nur die Domain der Website (zum Beispiel github.com). Kein Passwort, Benutzername oder sonstige Daten verlassen Ihren Computer, und heruntergeladene Symbole werden auf der Festplatte zwischengespeichert, um erneute Abfragen zu vermeiden.\n\nOnline-Symbole aktivieren?"),
            ("Privacy.Enable", "Privatsphärenmodus aktivieren"), ("Privacy.Disable", "Privatsphärenmodus deaktivieren"),
            ("Settings.LockNow", "Jetzt sperren"),
            ("Settings.SectionHelp", "HILFE"),
            ("Settings.KeyboardShortcuts", "Tastenkürzel..."),
            ("Settings.SectionDanger", "GEFAHRENZONE"),
            ("Settings.ClearVault", "Tresor bereinigen..."),
            ("Settings.DeleteVault", "Tresor löschen..."),
            ("Shortcuts.Title", "Tastenkürzel"),
            ("Shortcuts.Search", "Suchen"),
            ("Shortcuts.NewPassword", "Neues Passwort"),
            ("Shortcuts.OpenGenerator", "Generator öffnen"),
            ("Shortcuts.LockNow", "Jetzt sperren"),
            ("Shortcuts.PrivacyMode", "Privatsphärenmodus umschalten"),
            ("Shortcuts.CopyUser", "Benutzername der ausgewählten Zeile kopieren"),
            ("Shortcuts.CopyPassword", "Passwort der ausgewählten Zeile kopieren"),
            ("Shortcuts.CloseDialog", "Dialog schließen oder abbrechen"),
            ("Shortcuts.SelectedRowHint", "Die \"ausgewählte Zeile\" ist die mit Tastaturfokus; ist keine fokussiert, verwenden die Kopier-Tastenkürzel die erste Zeile der Liste."),
            ("Backup.Title", "Tresor-Sicherung"),
            ("Backup.Frequency", "Häufigkeit der automatischen Sicherung"),
            ("Backup.Manual", "Nur manuell"), ("Backup.Daily", "Täglich"), ("Backup.Weekly", "Wöchentlich"),
            ("Backup.MaxKept", "Maximale Anzahl aufbewahrter Sicherungen"),
            ("Backup.Now", "Jetzt sichern"),
            ("Backup.NeverDone", "Es wurde noch keine Sicherung erstellt."),
            ("Backup.LastDone", "Letzte Sicherung: {0}"),
            ("Backup.Available", "Verfügbare Sicherungen"),
            ("Backup.None", "Noch keine Sicherung verfügbar."),
            ("Backup.Restore", "Wiederherstellen"),
            ("Backup.RestoreFrom", "Sicherung vom {0} wiederherstellen"),
            ("Backup.RestoreTitle", "Sicherung wiederherstellen"),
            ("Backup.RestoreConfirm", "Dadurch werden alle Passwörter im Tresor durch die aus der Sicherung vom {0} ersetzt. Änderungen nach diesem Datum gehen verloren. Fortfahren?"),
            ("Backup.RestoreSuccess", "Sicherung erfolgreich wiederhergestellt."),
            ("Backup.RestoreDisabledDbConnected", "Trennen Sie die Datenbankverbindung, um eine Sicherung wiederherzustellen."),
            ("Backup.Success", "Sicherung erfolgreich erstellt."),
            ("Backup.Error", "Fehler bei der Verarbeitung der Sicherung: {0}"),

            ("Settings.Sync", "Synchronisierung..."),
            ("Sync.Title", "Synchronisierung zwischen Geräten"),
            ("Sync.Explanation", "Synchronisiert den Tresor mit anderen Geräten über einen gemeinsamen Ordner (z. B. Dropbox, OneDrive, Google Drive). Die Daten werden mit Ihrem Master-Passwort Ende-zu-Ende verschlüsselt, bevor sie dieses Gerät verlassen — der Cloud-Anbieter sieht niemals Klartext."),
            ("Sync.Enable", "Ordner wählen und aktivieren"),
            ("Sync.Folder", "Synchronisierungsordner"),
            ("Sync.Frequency", "Automatisch synchronisieren"),
            ("Sync.EveryMinutes", "Alle {0} Minuten"),
            ("Sync.Now", "Jetzt synchronisieren"),
            ("Sync.LastDone", "Letzte Synchronisierung: {0}"),
            ("Sync.NeverDone", "Noch nicht synchronisiert."),
            ("Sync.ChooseFolder", "Wählen Sie den Synchronisierungsordner"),
            ("Sync.EnableError", "Fehler beim Aktivieren der Synchronisierung: {0}"),
            ("Sync.Success", "Synchronisierung erfolgreich abgeschlossen."),
            ("Sync.Error", "Fehler bei der Synchronisierung. Prüfen Sie, ob der Ordner erreichbar ist."),
            ("Sync.Disable", "Synchronisierung deaktivieren"),
            ("Sync.DisableConfirm", "Synchronisierung deaktivieren? Die Geräte tauschen keine Daten mehr aus, aber nichts wird gelöscht."),
            ("Sync.ConfirmMasterTitle", "Master-Passwort bestätigen"),
            ("Sync.ConfirmMasterInstruction", "Geben Sie das Master-Passwort dieses Tresors ein, um die Synchronisierung zu aktivieren. Verwenden Sie auf allen Geräten, die diesen Ordner teilen, dasselbe Master-Passwort."),
            ("Sync.Confirm", "Bestätigen"),
            ("Vault.Header", "Passwort-Tresor"), ("Vault.ImportTooltip", "Passwörter aus Datei importieren"),
            ("Vault.ExportTooltip", "Passwörter in eine verschlüsselte Datei exportieren"),
            ("Vault.NewPassword", "Neues Passwort"),
            ("Vault.SearchWatermark", "Nach Dienst, Benutzer oder Kategorie suchen"),
            ("Vault.BreachTooltip", "Geleakte Passwörter prüfen (Have I Been Pwned)"),
            ("Vault.AuditTooltip", "Schwache, wiederverwendete oder alte Passwörter prüfen"),
            ("Vault.SecurityReportTooltip", "Sicherheitsbericht des Tresors"),
            ("Vault.FavoritesOnlyTooltip", "Nur Favoriten"),
            ("Vault.TagFilter", "Nach Tag filtern"),
            ("Vault.Table.Service", "DIENST"), ("Vault.Table.User", "BENUTZER"),
            ("Vault.Table.Category", "KATEGORIE"),
            ("Vault.Table.Actions", "AKTIONEN"),
            ("Vault.Table.Strength", "STÄRKE"),
            ("Vault.SortTooltip", "Sortieren"),
            ("Nav.Vault", "Tresor"),
            ("Nav.Favorites", "Favoriten"),
            ("Nav.Recent", "Zuletzt verwendet"),
            ("Nav.Categories", "KATEGORIEN"),
            ("Nav.Toggle", "Navigation umschalten"),
            ("Details.Title", "Details"),
            ("Details.Close", "Details schließen"),
            ("Details.Save", "Änderungen speichern"),
            ("Details.Delete", "Löschen"),
            ("Details.FullEdit", "Vollständig bearbeiten..."),
            ("Generator.Close", "Generator schließen"),
            ("Row.CopyUrl", "URL kopieren"),
            ("Footer.AutoLockOff", "Automatische Sperre deaktiviert"),
            ("Footer.AutoLockCountdown", "{0} Min. bis zur automatischen Sperre"),
            ("Vault.Empty", "Keine Passwörter im Tresor.\nKlicken Sie auf \"Neues Passwort\", um zu beginnen."),
            ("Vault.Filter.All", "Alle"), ("Vault.Counter.ItemSingular", "{0} Eintrag"),
            ("Vault.Counter.ItemPlural", "{0} Einträge"),
            ("Vault.Status.PasswordSingular", "Passwort"), ("Vault.Status.PasswordPlural", "Passwörter"),
            ("Vault.Status.FavoriteSingular", "Favorit"), ("Vault.Status.FavoritePlural", "Favoriten"),
            ("Vault.Status.AuditOk", "Audit OK"), ("Vault.Status.WithAlert", "{0} mit Warnung"),
            ("Vault.Connection.Local", "Verschlüsselter Tresor"),
            ("Vault.Connection.Connected", "Verbunden: {0}"),
            ("Vault.Connection.DatabaseUnavailable", "Datenbank nicht verfügbar - lokaler Tresor wird verwendet"),
            ("Generator.Title", "Passwortgenerator"), ("Generator.Mode", "Modus"),
            ("Generator.Mode.Password", "Passwort"), ("Generator.Mode.Passphrase", "Passphrase"),
            ("Generator.Strength", "Stärke"), ("Generator.Quantity", "Anzahl"),
            ("Generator.Length", "Länge"), ("Generator.Uppercase", "Großbuchstaben (A-Z)"),
            ("Generator.Lowercase", "Kleinbuchstaben (a-z)"), ("Generator.Numbers", "Zahlen (0-9)"),
            ("Generator.Special", "Sonderzeichen (!@#)"), ("Generator.Words", "Wörter"),
            ("Generator.Separator", "Trennzeichen"), ("Generator.Separator.Space", "Leerzeichen"),
            ("Generator.Capitalize", "Wörter großschreiben"), ("Generator.AddNumber", "Zahl hinzufügen"),
            ("Generator.GeneratePassword", "Neues Passwort erzeugen"),
            ("Generator.GeneratePassphrase", "Passphrase erzeugen"),
            ("Generator.SaveToVault", "Im Tresor speichern"), ("Generator.Clear", "Leeren"),
            ("Generator.CopyAll", "Alle kopieren"),
            ("Generator.PasswordsGenerated", "Erzeugte Passwörter ({0})"),
            ("Generator.PassphrasesGenerated", "Erzeugte Passphrasen ({0})"),
            ("Generator.StrengthWeak", "Schwach"), ("Generator.StrengthMedium", "Mittel"),
            ("Generator.StrengthStrong", "Stark"), ("Generator.StrengthExcellent", "Ausgezeichnet"),
            ("Generator.Item.Password", "Passwort"), ("Generator.Item.Passphrase", "Passphrase"),
            ("Generator.GenerateFirst", "Erzeugen Sie zuerst ein(e) {0}"),
            ("Generator.PasswordCopied", "Passwort kopiert!"),
            ("Generator.PassphraseCopied", "Passphrase kopiert!"),
            ("Generator.PasswordCopiedClearing", "Passwort kopiert! Wird in {0} Sekunden aus der Zwischenablage gelöscht."),
            ("Generator.PassphraseCopiedClearing", "Passphrase kopiert! Wird in {0} Sekunden aus der Zwischenablage gelöscht."),
            ("Login.SubtitleCreate", "Erstellen Sie ein Master-Passwort zum Schutz des Tresors"),
            ("Login.SubtitleUnlock", "Geben Sie Ihr Master-Passwort zum Entsperren ein"),
            ("Login.MasterPassword", "Master-Passwort"), ("Login.ConfirmPassword", "Passwort bestätigen"),
            ("Login.CreateVault", "Tresor erstellen"), ("Login.Unlock", "Entsperren"),
            ("Login.WindowsHello", "Mit Windows Hello entsperren"),
            ("Login.EnableWindowsHello", "Windows Hello aktivieren"),
            ("Login.WindowsHelloHint", "Mit Fingerabdruck, Gesicht oder PIN schneller entsperren."),
            ("Login.FirstRunNotice", "Bewahren Sie dieses Passwort gut auf: Es wird nie an einen Server gesendet oder dort gespeichert, und es gibt keine Möglichkeit, den Tresor wiederherzustellen, wenn Sie es vergessen. Der nächste Bildschirm bietet ein Notfall-Backup per QR-Code."),
            ("Login.Error.PasswordLength", "Das Passwort muss mindestens 8 Zeichen lang sein."),
            ("Login.Error.PasswordMismatch", "Die Passwörter stimmen nicht überein."),
            ("Login.Error.MasterPasswordRequired", "Geben Sie das Master-Passwort ein."),
            ("Login.Error.TooManyAttempts", "Zu viele Versuche. Warten Sie 5 Sekunden."),
            ("Login.Error.WrongPassword", "Falsches Passwort. Versuch {0} von 5."),
            ("Entry.NewTitle", "Neues Passwort"), ("Entry.EditTitle", "Passwort bearbeiten"),
            ("Entry.EditTitleWithService", "Passwort bearbeiten - {0}"),
            ("Entry.ServiceName", "Dienstname"), ("Entry.UserEmail", "Benutzer / E-Mail"),
            ("Entry.Password", "Passwort"),
            ("Entry.PasswordKeepCurrent", "Passwort  (leer lassen, um das aktuelle zu behalten)"),
            ("Entry.PasswordKeepCurrentFormat", "{0}  (leer lassen, um das aktuelle zu behalten)"),
            ("Entry.TotpOptional", "Zwei-Faktor-Authentifizierung (2FA)  (optional)"),
            ("Entry.TotpRemove", "Zwei-Faktor-Authentifizierung (2FA)  (leer entfernt sie)"),
            ("Entry.TotpLabel", "Bestätigungscode (2FA)"),
            ("Entry.TotpWatermark", "Geheimen Schlüssel oder otpauth://-Link einfügen"),
            ("Entry.TotpExpiresIn", "läuft in {0}s ab"), ("Entry.Category", "Kategorie"),
            ("Entry.TagsOptional", "Tags  (optional)"),
            ("Entry.TagsWatermark", "Z. B.: arbeit, wichtig, kunde-x"),
            ("Entry.UrlOptional", "URL  (optional)"), ("Entry.NotesOptional", "Notizen  (optional)"),
            ("Entry.Usage.Created", "Erstellt am {0}"), ("Entry.Usage.Updated", "Bearbeitet am {0}"),
            ("Entry.Usage.CopyPasswordLabel", "Passwort kopiert: {0}"), ("Entry.Usage.CopyUserLabel", "Benutzername kopiert: {0}"),
            ("Entry.Usage.CopyTotpLabel", "TOTP kopiert: {0}"), ("Entry.Usage.Never", "nie"),
            ("Entry.CreateRequired", "Füllen Sie die Pflichtfelder aus (Name, Benutzer und Passwort)."),
            ("Entry.EditRequired", "Füllen Sie die Pflichtfelder aus."),
            ("Entry.TotpInvalid", "Der 2FA-Schlüssel ist ungültig. Fügen Sie den geheimen Schlüssel (Base32) oder einen otpauth://-Link ein."),
            ("Entry.CreateError", "Fehler beim Erstellen des Passworts: {0}"),
            ("Entry.UpdateError", "Fehler beim Aktualisieren des Passworts: {0}"),
            ("Entry.RecoverCurrentPasswordError", "Das aktuelle Passwort konnte nicht wiederhergestellt werden. Geben Sie ein neues Passwort ein."),
            ("Entry.HistoryHeader", "Passwortverlauf ({0})"),
            ("Entry.HistoryReplacedOn", "Ersetzt am {0}"),
            ("Entry.HistoryUse", "Verwenden"),
            ("Entry.HistoryUseTooltip", "Feld mit diesem Passwort ausfüllen"),
            ("A11y.PreviousPassword", "Vorheriges Passwort"),

            ("Entry.RecoveryCodes", "Wiederherstellungscodes"),
            ("Entry.RecoveryCodesWatermark", "Einen Code pro Zeile einfügen"),
            ("Entry.RecoveryCodesAdd", "Hinzufügen"),
            ("Entry.RecoveryCodeMarkUsed", "Als verwendet markieren"),
            ("Entry.RecoveryCodeUnmark", "Markierung aufheben"),
            ("Entry.RecoveryCodeRemove", "Entfernen"),
            ("Entry.RecoveryCodeRemoveConfirm", "Diesen Wiederherstellungscode entfernen? Diese Aktion kann nicht rückgängig gemacht werden."),
            ("Entry.RecoveryCodesAddError", "Fehler beim Hinzufügen der Wiederherstellungscodes: {0}"),
            ("Entry.RecoveryCodeMarkError", "Fehler beim Aktualisieren des Wiederherstellungscodes: {0}"),
            ("Entry.RecoveryCodeRemoveError", "Fehler beim Entfernen des Wiederherstellungscodes: {0}"),
            ("Entry.Attachments", "Anhänge"),
            ("Entry.AttachmentsAdd", "Anhang hinzufügen..."),
            ("Entry.AttachmentDownload", "Herunterladen"),
            ("Entry.AttachmentRemove", "Entfernen"),
            ("Entry.AttachmentRemoveConfirm", "Anhang \"{0}\" entfernen? Das kann nicht rückgängig gemacht werden."),
            ("Entry.AttachmentAddError", "Fehler beim Hinzufügen des Anhangs: {0}"),
            ("Entry.AttachmentDownloadError", "Fehler beim Herunterladen des Anhangs: {0}"),
            ("A11y.RecoveryCode", "Wiederherstellungscode"),

            ("Entry.Type", "Anmeldedatentyp"),
            ("CredType.Login", "Login"),
            ("CredType.Cartao", "Karte"),
            ("CredType.ChaveLicenca", "Lizenzschlüssel"),
            ("CredType.WiFi", "WLAN"),
            ("CredType.Servidor", "Server"),
            ("CredType.BancoDados", "Datenbank"),
            ("CredField.CardHolder", "Karteninhaber"),
            ("CredField.CardNumber", "Kartennummer"),
            ("CredField.Product", "Produkt / Software"),
            ("CredField.LicenseKey", "Lizenzschlüssel"),
            ("CredField.Ssid", "Netzwerkname (SSID)"),
            ("CredField.WifiPassword", "Netzwerkpasswort"),
            ("CredField.Validade", "Ablaufdatum"),
            ("CredField.Cvv", "CVV"),
            ("CredField.Bandeira", "Kartenmarke"),
            ("CredField.Seguranca", "Sicherheit"),
            ("CredField.Banda", "Frequenzband"),
            ("CredField.Host", "Host"),
            ("CredField.Porta", "Port"),
            ("CredField.Protocolo", "Protokoll"),
            ("CredField.NomeBanco", "Datenbankname"),
            ("CredField.Motor", "Engine"),
            ("ExportDialog.ExportTitle", "Passwörter exportieren"),
            ("ExportDialog.ImportTitle", "Passwörter importieren"),
            ("ExportDialog.ExportPassword", "Export-Passwort"),
            ("ExportDialog.Password", "Passwort"),
            ("ExportDialog.InfoExport", "Legen Sie ein Passwort zum Schutz der Datei fest. Es wird beim Import benötigt - bewahren Sie es gut auf, denn ohne es kann die Datei nicht geöffnet werden."),
            ("ExportDialog.InfoImport", "Geben Sie das Passwort ein, das beim Export festgelegt wurde."),
            ("ExportDialog.PasswordRequired", "Geben Sie das Passwort ein."),
            ("ExportDialog.PasswordLength", "Das Passwort muss mindestens 8 Zeichen lang sein."),
            ("ExportDialog.PasswordMismatch", "Die Passwörter stimmen nicht überein."),
            ("Master.ChangeTitle", "Master-Passwort ändern"),
            ("Master.CurrentPassword", "Aktuelles Master-Passwort"),
            ("Master.NewPassword", "Neues Master-Passwort"),
            ("Master.ConfirmNewPassword", "Neues Passwort bestätigen"),
            ("Master.ErrorCurrentRequired", "Geben Sie das aktuelle Master-Passwort ein."),
            ("Master.ErrorNewLength", "Das neue Passwort muss mindestens 8 Zeichen lang sein."),
            ("Master.ErrorConfirmMismatch", "Die Bestätigung stimmt nicht mit dem neuen Passwort überein."),
            ("Master.ChangeError", "Fehler beim Ändern des Master-Passworts: {0}"),
            ("Master.ChangedRestart", "Master-Passwort erfolgreich geändert.\n\nDie Anwendung wird neu gestartet, um das neue Passwort anzuwenden."),
            ("Biometric.Title", "Windows Hello"),
            ("Biometric.EnableOffer", "Möchten Sie die Entsperrung mit Windows Hello auf diesem Gerät aktivieren?\n\nDas Master-Passwort funktioniert weiterhin als Fallback."),
            ("Biometric.Enabled", "Die Entsperrung mit Windows Hello ist auf diesem Gerät aktiviert."),
            ("Biometric.Disabled", "Die Entsperrung mit Windows Hello ist auf diesem Gerät deaktiviert."),
            ("Biometric.DisableConfirm", "Entsperrung mit Windows Hello auf diesem Gerät deaktivieren?"),
            ("Biometric.DisabledAfterMasterChange", "Die Entsperrung mit Windows Hello wurde deaktiviert und kann nach dem Neustart erneut aktiviert werden."),
            ("Biometric.DisabledAfterKdfUpgrade", "Ihr Tresor hat eine Sicherheitsverbesserung der Schlüsselableitung erhalten. Die Entsperrung mit Windows Hello wurde deaktiviert und kann jetzt im Einstellungsmenü wieder aktiviert werden."),
            ("Biometric.NotEnabled", "Die Entsperrung mit Windows Hello ist nicht aktiviert."),
            ("Biometric.InvalidVaultKey", "Der Tresorschlüssel ist nicht gültig, um Windows Hello zu aktivieren."),
            ("Biometric.InvalidRegistration", "Die Windows Hello-Registrierung passt nicht mehr zu diesem Tresor. Melden Sie sich mit dem Master-Passwort an und aktivieren Sie sie erneut."),
            ("Biometric.EnableError", "Fehler beim Aktivieren von Windows Hello: {0}"),
            ("Biometric.UnlockError", "Fehler beim Entsperren mit Windows Hello: {0}"),
            ("Biometric.UnsupportedPlatform", "Windows Hello ist nur unter Windows 10 oder höher verfügbar."),
            ("Biometric.AvailabilityError", "Windows Hello-Verfügbarkeit konnte nicht geprüft werden: {0}"),
            ("Biometric.NotConfigured", "Richten Sie eine PIN, Biometrie oder Windows Hello in den Windows-Einstellungen ein."),
            ("Biometric.RetriesExhausted", "Zu viele Verifizierungsversuche. Versuchen Sie es später erneut."),
            ("Biometric.Unavailable", "Windows Hello ist derzeit nicht verfügbar."),
            ("Qr.RegenerateTitle", "QR-Code neu erzeugen"),
            ("Qr.RegenerateInstruction", "Bestätigen Sie Ihr Master-Passwort, um einen neuen Backup-QR-Code zu erzeugen."),
            ("Qr.GenerateButton", "QR-Code erzeugen"),
            ("Qr.ErrorMasterRequired", "Geben Sie Ihr Master-Passwort ein."),
            ("Qr.ErrorMasterIncorrect", "Falsches Master-Passwort."),
            ("Qr.BackupTitle", "Master-Passwort-Backup"),
            ("Qr.BackupTitleWithType", "Master-Passwort-Backup (QR-Code)"),
            ("Qr.Offer", "Möchten Sie einen Backup-QR-Code für Ihr Master-Passwort speichern?\n\nWARNUNG: Der QR-Code enthält die Passphrasen-Version Ihres Master-Passworts. Jeder, der das Bild scannt, kann das Passwort rekonstruieren und auf den Tresor zugreifen.\n\nBewahren Sie die Datei sicher und offline auf (oder ausgedruckt) - niemals in Cloud-Speichern, E-Mail oder freigegebenen Ordnern."),
            ("Qr.SavePickerTitle", "QR-Code des Master-Passworts speichern"),
            ("Qr.SaveSuccess", "QR-Code erfolgreich gespeichert. Bewahren Sie ihn sicher auf."),
            ("Qr.SaveError", "QR-Code konnte nicht gespeichert werden: {0}"),
            ("Qr.SheetSubtitle", "Master-Passwort-Backup"),
            ("Qr.SheetWarning1", "Enthält die Passphrasen-Version des Master-Passworts."),
            ("Qr.SheetWarning2", "Sicher und offline aufbewahren."),
            ("Db.SelectTitle", "Datenbank verbinden"), ("Db.ChooseType", "Wählen Sie den Datenbanktyp für die Verbindung."),
            ("Db.SelectExplanation", "Eine Funktion für Self-Hosting oder gemeinsame Nutzung: verbindet den Tresor mit einer eigenen Datenbank, nützlich für einen persönlichen Server oder um den Zugriff mit anderen vertrauenswürdigen Personen zu teilen. Um nur Ihre eigenen Geräte zu synchronisieren, ohne eine Datenbank zu pflegen, verwenden Sie die Synchronisierung über einen gemeinsamen Ordner im Einstellungsmenü."),
            ("Db.ConnectionTitle", "Verbindung"), ("Db.ConnectProviderTitle", "Verbinden - {0}"),
            ("Db.TestConnection", "Verbindung testen"), ("Db.DatabaseFile", "Datenbankdatei (.db)"),
            ("Db.Browse", "Suchen..."), ("Db.Host", "Host"), ("Db.Port", "Port"),
            ("Db.Database", "Datenbank"), ("Db.User", "Benutzer"), ("Db.Password", "Passwort"),
            ("Db.SQLitePickerTitle", "SQLite-Datenbankdatei"),
            ("Db.ConnectionSuccess", "Verbindung erfolgreich."),
            ("Db.CreateTableTitle", "Tabelle erstellen"),
            ("Db.TableMissing", "Die Tabelle \"{0}\" existiert in dieser Datenbank nicht.\n\nJetzt erstellen?"),
            ("Db.ConnectionCanceledNoTable", "Verbindung abgebrochen: Die Tabelle existiert nicht."),
            ("Db.ErrorFileRequired", "Geben Sie die Datenbankdatei an."),
            ("Db.ErrorFieldsRequired", "Füllen Sie Host, Datenbank und Benutzer aus."),
            ("Db.ErrorInvalidPort", "Ungültiger Port."),
            ("Db.ConnectionFailed", "Verbindung fehlgeschlagen: {0}"),
            ("Db.CannotConnect", "Verbindung nicht möglich: {0}"),
            ("Db.FeatureUnavailable", "Funktion in dieser Sitzung nicht verfügbar."),
            ("Db.ConnectedMessage", "Mit der Datenbank verbunden — die Daten werden jetzt mit dieser gemeinsamen Datenbank gespiegelt.\n\n{0}"),
            ("Db.ConnectError", "Fehler beim Verbinden: {0}"),
            ("Message.LoadError", "Fehler beim Laden: {0}"),
            ("Message.FavoriteError", "Fehler beim Favorisieren: {0}"),
            ("Message.PinError", "Fehler beim Anheften: {0}"),
            ("Message.DeleteTitle", "Passwort löschen"),
            ("Message.MoveToTrash", "Die Anmeldedaten werden in den Papierkorb verschoben. Sie können sie dort wiederherstellen oder endgültig löschen."),
            ("Message.DeletePrompt", "\"{0}\" löschen?\n\n{1}"),
            ("Message.DeleteError", "Fehler beim Löschen des Passworts: {0}"),
            ("Nav.Trash", "Papierkorb"),
            ("Trash.Empty", "Der Papierkorb ist leer."),
            ("Trash.DeletedOn", "Gelöscht am {0}"),
            ("Trash.Restore", "Wiederherstellen"),
            ("Trash.RestoreError", "Fehler bei der Wiederherstellung: {0}"),
            ("Trash.DeleteForever", "Endgültig löschen"),
            ("Trash.DeleteForeverConfirm", "\"{0}\" endgültig löschen?\n\nDiese Aktion kann nicht rückgängig gemacht werden."),
            ("Trash.DeleteForeverError", "Fehler beim endgültigen Löschen: {0}"),
            ("Trash.EmptyButton", "Papierkorb leeren"),
            ("Trash.EmptyConfirmTitle", "Papierkorb leeren"),
            ("Trash.EmptyConfirm", "Alle Elemente im Papierkorb endgültig löschen?\n\nDiese Aktion kann nicht rückgängig gemacht werden."),
            ("Trash.EmptyError", "Fehler beim Leeren des Papierkorbs: {0}"),

            ("Vault.ClearTitle", "Tresor bereinigen"),
            ("Vault.ClearConfirm", "Alle Passwörter im Tresor in den Papierkorb verschieben?\n\nSie können sie bei Bedarf später aus dem Papierkorb wiederherstellen."),
            ("Vault.ClearError", "Fehler beim Bereinigen des Tresors: {0}"),
            ("Vault.DeleteTitle", "Tresor löschen"),
            ("Vault.DeleteReauthInstruction", "Geben Sie Ihr aktuelles Master-Passwort ein, um fortzufahren."),
            ("Vault.DeleteReauthButton", "Weiter"),
            ("Vault.DeleteConfirm", "Tresor endgültig löschen?\n\nAlle Passwörter, das Master-Passwort, Backups und Anhänge werden gelöscht, und die Entsperrung mit Windows Hello wird deaktiviert. Diese Aktion kann nicht rückgängig gemacht werden."),
            ("Vault.DeleteError", "Fehler beim Löschen des Tresors: {0}"),
            ("Vault.DeletedRestart", "Tresor gelöscht. Die App wird neu gestartet."),
            ("Message.RenameDecryptError", "Das Passwort konnte nicht entschlüsselt werden, um die Änderung zu speichern."),
            ("Message.RenameError", "Fehler beim Umbenennen des Dienstes: {0}"),
            ("Message.AuditTitle", "Tresor-Audit"),
            ("Message.AuditNoPasswords", "Keine Passwörter im Tresor zum Prüfen."),
            ("Message.AuditSuccess", "Audit abgeschlossen: keine schwachen, wiederverwendeten oder alten Passwörter unter {0} Passwort/Passwörtern."),
            ("Message.AuditIncomplete", "{0} Passwort/Passwörter konnten nicht vollständig analysiert werden."),
            ("Message.AuditFoundHeader", "{0} Eintrag/Einträge mit Warnung unter {1} Passwort/Passwörtern gefunden:"),
            ("Message.AuditWeakLine", "- {0} schwach"),
            ("Message.AuditRepeatedLine", "- {0} wiederverwendet"),
            ("Message.AuditOldLine", "- {0} alt"),
            ("Message.AuditUnreadableLine", "- {0} wegen Lesefehler nicht geprüft"),
            ("Message.AuditMarked", "Betroffene Einträge wurden in der Liste mit ⚠ markiert."),
            ("Message.AuditOldDefinition", "Alte Passwörter wurden seit {0} Tagen oder länger nicht aktualisiert."),
            ("Message.AuditError", "Fehler beim Audit des Tresors: {0}"),

            ("SecurityReport.Title", "Sicherheitsbericht"),
            ("SecurityReport.ScoreLabel", "Tresor-Bewertung"),
            ("SecurityReport.ScoreWeak", "Braucht Aufmerksamkeit"),
            ("SecurityReport.ScoreMedium", "Mittelmäßig"),
            ("SecurityReport.ScoreStrong", "Gut"),
            ("SecurityReport.ScoreExcellent", "Ausgezeichnet"),
            ("SecurityReport.Weak", "Schwache Passwörter"),
            ("SecurityReport.Repeated", "Wiederverwendete Passwörter"),
            ("SecurityReport.Old", "Alte Passwörter"),
            ("SecurityReport.Compromised", "Kompromittierte Passwörter"),
            ("SecurityReport.NoTotp", "Ohne Zwei-Faktor-Authentifizierung"),
            ("SecurityReport.NoUrl", "Ohne gespeicherte URL"),
            ("SecurityReport.NoCategory", "Ohne festgelegte Kategorie"),
            ("SecurityReport.RowAutomationName", "{0}: {1}"),
            ("SecurityReport.CheckBreaches", "Jetzt auf Datenlecks prüfen"),
            ("SecurityReport.BreachesNotChecked", "In dieser Sitzung noch nicht geprüft"),
            ("SecurityReport.AllGood", "Keine Probleme gefunden. Weiter so!"),
            ("SecurityReport.ClearFilter", "Filter entfernen"),
            ("SecurityReport.FilterActive", "Gefiltert nach: {0}"),
            ("SecurityReport.BreachCheckError", "Fehler beim Prüfen auf Datenlecks: {0}"),
            ("Message.BreachTitle", "Leaks prüfen"),
            ("Message.BreachNoPasswords", "Keine Passwörter im Tresor zum Prüfen."),
            ("Message.BreachDoneTitle", "Prüfung abgeschlossen"),
            ("Message.BreachSuccess", "Gute Nachricht! Keines der {0} geprüften Passwörter wurde in bekannten Leaks gefunden."),
            ("Message.BreachWarning", "Warnung: {0} von {1} Passwort/Passwörtern erscheinen in bekannten Leaks. Erwägen Sie, sie zu ändern (mit ⚠ markiert)."),
            ("Message.NetworkErrorTitle", "Netzwerkfehler"),
            ("Message.BreachNetworkError", "Leaks konnten nicht geprüft werden.\nPrüfen Sie Ihre Internetverbindung.\n\nDetail: {0}"),
            ("Message.ExportEmpty", "Der Tresor ist leer. Es gibt nichts zu exportieren."),
            ("Message.ExportSuccess", "{0} Passwort/Passwörter erfolgreich exportiert.\n\nBewahren Sie das Export-Passwort gut auf - ohne es kann die Datei nicht geöffnet werden."),
            ("Message.ExportError", "Fehler beim Exportieren: {0}"),
            ("Message.ImportEmpty", "Keine Passwörter in der Datei gefunden."),
            ("Message.ImportSuccess", "{0} Passwort/Passwörter erfolgreich importiert."),
            ("Message.ImportIgnored", "{0} ignoriert (unvollständige oder ungültige Daten)."),
            ("Message.ImportDuplicates", "{0} waren bereits im Tresor vorhanden."),
            ("Message.ImportError", "Fehler beim Importieren: {0}"),
            ("Message.CsvEmpty", "Keine Zugangsdaten in der Datei gefunden."),
            ("Message.CsvConfirm", "Datei im Format {0} mit {1} Zugangsdaten erkannt.\n\nDie Passwörter werden dem Tresor hinzugefügt (vorhandene Einträge werden ignoriert). Fortfahren?"),
            ("Message.CsvIgnored", "{0} ignoriert (unvollständige oder ungültige Zeile)."),
            ("Message.CsvDuplicates", "{0} waren bereits im Tresor vorhanden."),
            ("Message.CsvSecurity", "Löschen Sie aus Sicherheitsgründen die CSV-Datei - sie enthält Passwörter im Klartext."),
            ("Import.Progress", "Importiere {0} von {1}…"),
            ("Row.FavoriteRemove", "Aus Favoriten entfernen"), ("Row.FavoriteAdd", "Zu Favoriten hinzufügen"),
            ("Row.PinEntry", "Oben anheften"), ("Row.UnpinEntry", "Loslösen"),
            ("Row.CopyUser", "Benutzer kopieren"), ("Row.EditService", "Dienst bearbeiten"),
            ("Row.RevealPassword", "Passwort anzeigen"), ("Row.HidePassword", "Passwort verbergen"),
            ("Row.CopyPassword", "Passwort kopieren"), ("Row.EditEntry", "Eintrag bearbeiten"),
            ("Row.DeleteEntry", "Eintrag löschen"), ("Row.CopyTotp", "2FA-Code kopieren"),
            ("Row.CopyRecoveryCode", "Wiederherstellungscode kopieren"),
            ("Row.UserCopied", "Benutzer kopiert"),
            ("Row.PasswordCopiedClearing", "Passwort kopiert — Löschung in {0}s"),
            ("Row.CategoryTooltip", "Kategorie: {0}"), ("Row.TagsTooltip", "Tags: {0}\nKategorie: {1}"),
            ("Row.PasswordCompromised", "Kompromittiertes Passwort - in {0:N0} Leak(s) gefunden. Ändern Sie es!"),
            ("Row.AuditPrefix", "Audit: {0}"), ("Row.NotFoundInBreaches", " (nicht in Leaks gefunden)"),
            ("Row.PasswordWeak", "Schwaches Passwort"), ("Row.PasswordMedium", "Mittleres Passwort"),
            ("Row.PasswordStrong", "Starkes Passwort"), ("Row.AuditWeak", "schwaches Passwort"),
            ("Row.AuditRepeatedWithCount", "Passwort in {0} Einträgen wiederverwendet"),
            ("Row.AuditRepeated", "wiederverwendetes Passwort"),
            ("Row.AuditOld", "seit {0} Tagen nicht aktualisiert"), ("Row.AuditAlert", "Warnung"),
            ("Category.Work", "Arbeit"), ("Category.Personal", "Persönlich"),
            ("Category.Finance", "Finanzen"), ("Category.Social", "Sozial"), ("Category.Other", "Andere"),
            ("Access.Title", "Barrierefreiheit"), ("Access.Colorblind", "Farbenblindheit"), ("Access.None", "Keine"),
            ("Access.Protanopia", "Protanopie"), ("Access.Deuteranopia", "Deuteranopie"), ("Access.Tritanopia", "Tritanopie"),
            ("Access.Monochromacy", "Monochromasie"),
            ("Access.HighContrast", "Hoher Kontrast"), ("Access.TextSize", "Textgröße"),
            ("Access.TextNormal", "Normal"), ("Access.TextLarge", "Groß"), ("Access.TextLarger", "Größer"),
            ("Access.ReduceMotion", "Animationen reduzieren"), ("Access.ScreenReader", "Screenreader"),
            ("Access.ScreenReaderHelp", "Ausführlicherer Modus für Screenreader"), ("Access.Minimize", "Minimieren"),
            ("Access.Maximize", "Maximieren"), ("Access.Close", "Fenster schließen"),

            ("Entry.FieldDecryptError", "(dieses Feld konnte nicht entschlüsselt werden)"),
            ("Entry.Error.ServiceRequired", "Der Dienstname darf nicht leer sein"),
            ("Entry.Error.UserRequired", "Der Benutzer darf nicht leer sein"),
            ("Entry.Error.PasswordRequired", "Das Passwort darf nicht leer sein"),
            ("Entry.Error.ServiceTooLong", "Der Dienstname darf {0} Zeichen nicht überschreiten"),
            ("Entry.Error.UserTooLong", "Der Benutzer darf {0} Zeichen nicht überschreiten"),
            ("Entry.Error.PasswordTooLong", "Das Passwort darf {0} Zeichen nicht überschreiten"),
            ("Auth.Error.PasswordRequired", "Das Master-Passwort darf nicht leer sein."),
            ("Auth.Error.PasswordTooShort", "Das Master-Passwort muss mindestens {0} Zeichen lang sein."),
            ("Master.Error.NewPasswordTooShort", "Das neue Master-Passwort muss mindestens {0} Zeichen lang sein."),
            ("Master.Error.CurrentPasswordWrong", "Das aktuelle Master-Passwort ist falsch."),
            ("Export.Error.PasswordTooShort", "Das Exportpasswort muss mindestens {0} Zeichen lang sein."),
            ("Export.Error.FileNotFound", "Importdatei nicht gefunden."),
            ("Export.Error.PasswordRequired", "Geben Sie das Exportpasswort ein."),
            ("Export.Error.InvalidFile", "Ungültige oder beschädigte Importdatei."),
            ("Export.Error.WrongPassword", "Falsches Exportpasswort oder beschädigte Datei."),
            ("Export.Error.InvalidContent", "Ungültiger Inhalt der Importdatei."),
            ("Import.Error.FileNotFound", "Importdatei nicht gefunden."),
            ("Import.Error.CannotRead", "Die Importdatei konnte nicht gelesen werden."),
            ("Import.Error.EmptyFile", "Die Datei ist leer."),
            ("Import.Error.NoCredentials", "Die Datei enthält keine zu importierenden Zugangsdaten."),
            ("Import.Error.NoPasswordColumn", "Die Passwortspalte konnte nicht erkannt werden. Prüfen Sie, ob die Datei eine Kopfzeile mit den Spaltennamen hat."),
            ("Attachment.Error.NameRequired", "Der Dateiname darf nicht leer sein"),
            ("Attachment.Error.EmptyFile", "Leere Datei"),
            ("Attachment.Error.FileTooLarge", "Datei größer als das Limit von {0} MB pro Anhang"),
            ("Attachment.Error.MaxPerCredential", "Dieser Eintrag hat bereits das Maximum von {0} Anhängen"),
            ("Attachment.Error.VaultLimit", "Der Tresor würde das Limit von {0} MB an Anhängen erreichen"),
            ("Generator.Error.LengthRange", "Die Passwortlänge muss zwischen 4 und 1000 Zeichen liegen."),
            ("Generator.Error.NoCharacterType", "Wählen Sie mindestens einen Zeichentyp aus."),
            ("Generator.Error.PassphraseWordsRange", "Die Passphrase muss zwischen 3 und 12 Wörtern haben."),
            ("Generator.Error.SeparatorTooLong", "Das Trennzeichen darf höchstens 3 Zeichen lang sein."),
            ("Generator.Error.NotEnoughWords", "Geben Sie eine Liste mit mindestens zwei Wörtern an."),
            ("Generator.Error.QuantityRange", "Die Anzahl muss zwischen 1 und 50 liegen."),
            ("Vault.Error.WrongKeyOrCorrupt", "Der Tresor konnte nicht geöffnet werden: Der Schlüssel ist falsch oder die Datei wurde beschädigt."),
            ("Vault.Error.CorruptData", "Der Inhalt des Tresors ist beschädigt."),
            ("Vault.Error.IOFailure", "Auf die Tresordatei konnte nicht zugegriffen werden."),
            ("Vault.Error.BackupFailed", "Die Sicherung des Tresors konnte nicht erstellt werden.")
        });
    }
}
