namespace CofreDeSenhas
{
    internal static partial class Idioma
    {
        private static IReadOnlyDictionary<string, string> CriarPtBr() => Criar(new (string, string)[]
        {
            ("App.Title", "Cofre de Senhas"),
            ("Common.Save", "Salvar"),
            ("Common.Cancel", "Cancelar"),
            ("Common.Change", "Alterar"),
            ("Common.Connect", "Conectar"),
            ("Common.Export", "Exportar"),
            ("Common.Import", "Importar"),
            ("Common.Exit", "Sair"),
            ("Common.Close", "Fechar"),
            ("Common.Warning", "Aviso"),
            ("Common.Error", "Erro"),
            ("Common.Success", "Sucesso"),
            ("Common.Validation", "Validação"),
            ("Common.Yes", "Sim"),
            ("Common.No", "Não"),
            ("Common.AllFiles", "Todos os arquivos"),
            ("Common.ExportedVaultFile", "Cofre exportado"),
            ("Common.CsvFile", "Arquivo CSV"),
            ("Common.PngImage", "Imagem PNG"),
            ("Common.SQLiteDatabase", "Banco SQLite"),

            ("Settings.Tooltip", "Configurações"),
            ("Settings.SectionSecurity", "SEGURANÇA"),
            ("Settings.ChangeMasterPassword", "Alterar senha mestra..."),
            ("Settings.RegenerateQr", "Regerar QR code..."),
            ("Settings.Backup", "Backup e restauração..."),
            ("Settings.AutoLock", "Bloqueio automático"),
            ("Settings.Disabled", "Desativado"),
            ("Settings.AfterOneMinute", "Após 1 minuto"),
            ("Settings.AfterMinutes5", "Após 5 minutos"),
            ("Settings.AfterMinutes15", "Após 15 minutos"),
            ("Settings.AfterMinutes30", "Após 30 minutos"),
            ("Settings.ClipboardClear", "Limpeza da área de transferência"),
            ("Settings.ClipboardClear.After15", "Após 15 segundos"),
            ("Settings.ClipboardClear.After30", "Após 30 segundos"),
            ("Settings.ClipboardClear.After60", "Após 60 segundos"),
            ("Settings.SectionAppearance", "APARÊNCIA"),
            ("Settings.Language", "Idioma"),
            ("Settings.SectionData", "DADOS"),
            ("Settings.ImportCsv", "Importar de CSV / outro gerenciador..."),
            ("Settings.ConnectDatabase", "Conectar banco de dados..."),
            ("Settings.DisconnectDatabase", "Desconectar do banco"),
            ("Settings.EnableWindowsHello", "Ativar Windows Hello..."),
            ("Settings.DisableWindowsHello", "Desativar Windows Hello"),
            ("Settings.OnlineIcons", "Ícones online dos serviços"),
            ("Settings.OnlineIconsTooltip", "Baixa da internet o ícone real de cada serviço. Desativado, o cofre mostra apenas iniciais e não acessa a rede."),
            ("Settings.TrackUsageHistory", "Registrar histórico de uso"),
            ("Settings.TrackUsageHistoryTooltip", "Registra a data da última cópia de senha, usuário e código TOTP de cada credencial. Desative para parar de guardar esses registros — datas já salvas continuam visíveis."),
            ("Icons.ConsentMessage", "Para exibir o ícone real de cada serviço, o aplicativo consulta o serviço de ícones do Google enviando apenas o domínio do site (por exemplo, github.com). Nenhuma senha, usuário ou outro dado sai do seu computador, e os ícones baixados ficam em cache no disco para evitar novas consultas.\n\nDeseja ativar a busca de ícones online?"),
            ("Theme.Light", "Tema claro"),
            ("Theme.Dark", "Tema escuro"),
            ("Privacy.Enable", "Ativar modo privacidade"),
            ("Privacy.Disable", "Desativar modo privacidade"),
            ("Settings.LockNow", "Bloquear agora"),
            ("Settings.SectionHelp", "AJUDA"),
            ("Settings.KeyboardShortcuts", "Atalhos de teclado..."),
            ("Shortcuts.Title", "Atalhos de teclado"),
            ("Shortcuts.Search", "Buscar"),
            ("Shortcuts.NewPassword", "Nova senha"),
            ("Shortcuts.OpenGenerator", "Abrir o gerador"),
            ("Shortcuts.LockNow", "Bloquear agora"),
            ("Shortcuts.CopyUser", "Copiar usuário da linha selecionada"),
            ("Shortcuts.CopyPassword", "Copiar senha da linha selecionada"),
            ("Shortcuts.PrivacyMode", "Ativar/desativar modo privacidade"),
            ("Shortcuts.CloseDialog", "Fechar diálogo ou cancelar"),
            ("Shortcuts.SelectedRowHint", "A \"linha selecionada\" é a que está com foco de teclado; sem foco em nenhuma, os atalhos de cópia usam a primeira linha da lista."),

            ("Backup.Title", "Backup do cofre"),
            ("Backup.Frequency", "Frequência do backup automático"),
            ("Backup.Manual", "Manual apenas"),
            ("Backup.Daily", "Diário"),
            ("Backup.Weekly", "Semanal"),
            ("Backup.MaxKept", "Quantidade máxima de backups mantidos"),
            ("Backup.Now", "Fazer backup agora"),
            ("Backup.NeverDone", "Nenhum backup realizado ainda."),
            ("Backup.LastDone", "Último backup: {0}"),
            ("Backup.Available", "Backups disponíveis"),
            ("Backup.None", "Nenhum backup disponível ainda."),
            ("Backup.Restore", "Restaurar"),
            ("Backup.RestoreFrom", "Restaurar backup de {0}"),
            ("Backup.RestoreTitle", "Restaurar backup"),
            ("Backup.RestoreConfirm", "Isso vai substituir todas as senhas do cofre pelas do backup de {0}. Alterações feitas depois dessa data serão perdidas. Deseja continuar?"),
            ("Backup.RestoreSuccess", "Backup restaurado com sucesso."),
            ("Backup.RestoreDisabledDbConnected", "Desconecte o banco de dados para restaurar um backup."),
            ("Backup.Success", "Backup criado com sucesso."),
            ("Backup.Error", "Erro ao processar o backup: {0}"),

            ("Vault.Header", "Cofre de senhas"),
            ("Vault.ImportTooltip", "Importar senhas de um arquivo"),
            ("Vault.ExportTooltip", "Exportar senhas para um arquivo criptografado"),
            ("Vault.NewPassword", "Nova senha"),
            ("Vault.SearchWatermark", "Buscar por serviço, usuário ou categoria"),
            ("Vault.BreachTooltip", "Verificar senhas vazadas (Have I Been Pwned)"),
            ("Vault.AuditTooltip", "Auditar senhas fracas, repetidas ou antigas"),
            ("Vault.SecurityReportTooltip", "Relatório de segurança do cofre"),
            ("Vault.FavoritesOnlyTooltip", "Somente favoritas"),
            ("Vault.Table.Service", "SERVIÇO"),
            ("Vault.Table.User", "USUÁRIO"),
            ("Vault.Table.Category", "CATEGORIA"),
            ("Vault.Table.Actions", "AÇÕES"),
            ("Vault.Table.Strength", "FORÇA"),
            ("Vault.SortTooltip", "Ordenar"),
            ("Nav.Vault", "Cofre"),
            ("Nav.Favorites", "Favoritas"),
            ("Nav.Recent", "Recentes"),
            ("Nav.Categories", "CATEGORIAS"),
            ("Nav.Toggle", "Alternar navegação"),
            ("Details.Title", "Detalhes"),
            ("Details.Close", "Fechar detalhes"),
            ("Details.Save", "Salvar alterações"),
            ("Details.Delete", "Excluir"),
            ("Details.FullEdit", "Edição completa..."),
            ("Generator.Close", "Fechar gerador"),
            ("Row.CopyUrl", "Copiar URL"),
            ("Footer.AutoLockOff", "Bloqueio automático desativado"),
            ("Footer.AutoLockCountdown", "{0} min até bloqueio automático"),
            ("Vault.Empty", "Nenhuma senha no cofre.\nClique em \"Nova senha\" para começar."),
            ("Vault.Filter.All", "Todas"),
            ("Vault.Counter.ItemSingular", "{0} item"),
            ("Vault.Counter.ItemPlural", "{0} itens"),
            ("Vault.Status", "{0} {1} • {2} {3}"),
            ("Vault.Status.PasswordSingular", "senha"),
            ("Vault.Status.PasswordPlural", "senhas"),
            ("Vault.Status.FavoriteSingular", "favorita"),
            ("Vault.Status.FavoritePlural", "favoritas"),
            ("Vault.Status.AuditOk", "auditoria OK"),
            ("Vault.Status.WithAlert", "{0} com alerta"),
            ("Vault.Connection.Local", "Cofre criptografado"),
            ("Vault.Connection.Connected", "Conectado: {0}"),
            ("Vault.Connection.DatabaseUnavailable", "Banco indisponível - usando cofre local"),

            ("Generator.Title", "Gerador de senha"),
            ("Generator.Mode", "Modo"),
            ("Generator.Mode.Password", "Senha"),
            ("Generator.Mode.Passphrase", "Frase-senha"),
            ("Generator.Strength", "Força"),
            ("Generator.Quantity", "Quantidade"),
            ("Generator.Length", "Comprimento"),
            ("Generator.Uppercase", "Letras maiúsculas (A-Z)"),
            ("Generator.Lowercase", "Letras minúsculas (a-z)"),
            ("Generator.Numbers", "Números (0-9)"),
            ("Generator.Special", "Caracteres especiais (!@#)"),
            ("Generator.Words", "Palavras"),
            ("Generator.Separator", "Separador"),
            ("Generator.Separator.Space", "espaço"),
            ("Generator.Capitalize", "Capitalizar palavras"),
            ("Generator.AddNumber", "Adicionar número"),
            ("Generator.GeneratePassword", "Gerar nova senha"),
            ("Generator.GeneratePassphrase", "Gerar frase-senha"),
            ("Generator.SaveToVault", "Salvar no cofre"),
            ("Generator.Clear", "Limpar"),
            ("Generator.CopyAll", "Copiar todas"),
            ("Generator.PasswordsGenerated", "Senhas geradas ({0})"),
            ("Generator.PassphrasesGenerated", "Frases-senha geradas ({0})"),
            ("Generator.StrengthWeak", "Fraca"),
            ("Generator.StrengthMedium", "Média"),
            ("Generator.StrengthStrong", "Forte"),
            ("Generator.StrengthExcellent", "Excelente"),
            ("Generator.Item.Password", "senha"),
            ("Generator.Item.Passphrase", "frase-senha"),
            ("Generator.GenerateFirst", "Gere uma {0} primeiro"),
            ("Generator.PasswordCopied", "Senha copiada!"),
            ("Generator.PassphraseCopied", "Frase-senha copiada!"),
            ("Generator.PasswordCopiedClearing", "Senha copiada! Será apagada da área de transferência em {0} segundos."),
            ("Generator.PassphraseCopiedClearing", "Frase-senha copiada! Será apagada da área de transferência em {0} segundos."),

            ("Login.SubtitleCreate", "Crie uma senha mestra para proteger o cofre"),
            ("Login.SubtitleUnlock", "Digite sua senha mestra para desbloquear"),
            ("Login.MasterPassword", "Senha mestra"),
            ("Login.ConfirmPassword", "Confirmar senha"),
            ("Login.CreateVault", "Criar cofre"),
            ("Login.Unlock", "Desbloquear"),
            ("Login.WindowsHello", "Desbloquear com Windows Hello"),
            ("Login.EnableWindowsHello", "Ativar Windows Hello"),
            ("Login.WindowsHelloHint", "Use digital, rosto ou PIN para desbloquear mais rápido."),
            ("Login.Error.PasswordLength", "A senha deve ter pelo menos 8 caracteres."),
            ("Login.Error.PasswordMismatch", "As senhas não coincidem."),
            ("Login.Error.MasterPasswordRequired", "Digite a senha mestra."),
            ("Login.Error.TooManyAttempts", "Muitas tentativas. Aguarde 5 segundos."),
            ("Login.Error.WrongPassword", "Senha incorreta. Tentativa {0} de 5."),

            ("Entry.NewTitle", "Nova senha"),
            ("Entry.EditTitle", "Editar senha"),
            ("Entry.EditTitleWithService", "Editar senha - {0}"),
            ("Entry.ServiceName", "Nome do serviço"),
            ("Entry.UserEmail", "Usuário / E-mail"),
            ("Entry.Password", "Senha"),
            ("Entry.PasswordKeepCurrent", "Senha  (deixe em branco para manter a atual)"),
            ("Entry.TotpOptional", "Autenticação em duas etapas (2FA)  (opcional)"),
            ("Entry.TotpRemove", "Autenticação em duas etapas (2FA)  (em branco remove)"),
            ("Entry.TotpLabel", "Código de verificação (2FA)"),
            ("Entry.TotpWatermark", "Cole a chave secreta ou o link otpauth://"),
            ("Entry.TotpExpiresIn", "expira em {0}s"),
            ("Entry.Category", "Categoria"),
            ("Entry.CustomCategory", "Categoria personalizada"),
            ("Entry.CustomCategoryWatermark", "Ex.: Jogos"),
            ("Entry.UrlOptional", "URL  (opcional)"),
            ("Entry.NotesOptional", "Notas  (opcional)"),
            ("Entry.Usage.Created", "Criada em {0}"),
            ("Entry.Usage.Updated", "Editada em {0}"),
            ("Entry.Usage.CopyPasswordLabel", "Senha copiada: {0}"),
            ("Entry.Usage.CopyUserLabel", "Usuário copiado: {0}"),
            ("Entry.Usage.CopyTotpLabel", "TOTP copiado: {0}"),
            ("Entry.Usage.Never", "nunca"),
            ("Entry.CreateRequired", "Preencha os campos obrigatórios (nome, usuário e senha)."),
            ("Entry.EditRequired", "Preencha os campos obrigatórios."),
            ("Entry.TotpInvalid", "A chave de autenticação em duas etapas é inválida. Cole a chave secreta (Base32) ou um link otpauth://."),
            ("Entry.CreateError", "Erro ao criar senha: {0}"),
            ("Entry.UpdateError", "Erro ao atualizar senha: {0}"),
            ("Entry.RecoverCurrentPasswordError", "Não foi possível recuperar a senha atual. Digite uma nova senha."),
            ("Entry.HistoryHeader", "Histórico de senhas ({0})"),
            ("Entry.HistoryReplacedOn", "Substituída em {0}"),
            ("Entry.HistoryUse", "Usar"),
            ("Entry.HistoryUseTooltip", "Preencher o campo com esta senha"),
            ("A11y.PreviousPassword", "Senha anterior"),

            ("Entry.RecoveryCodes", "Códigos de recuperação"),
            ("Entry.RecoveryCodesWatermark", "Cole um código por linha"),
            ("Entry.RecoveryCodesAdd", "Adicionar"),
            ("Entry.RecoveryCodeMarkUsed", "Marcar como usado"),
            ("Entry.RecoveryCodeUnmark", "Desmarcar"),
            ("Entry.RecoveryCodeRemove", "Remover"),
            ("Entry.RecoveryCodeRemoveConfirm", "Remover este código de recuperação? Essa ação não pode ser desfeita."),
            ("Entry.RecoveryCodesAddError", "Erro ao adicionar códigos de recuperação: {0}"),
            ("Entry.RecoveryCodeMarkError", "Erro ao atualizar o código de recuperação: {0}"),
            ("Entry.RecoveryCodeRemoveError", "Erro ao remover o código de recuperação: {0}"),
            ("A11y.RecoveryCode", "Código de recuperação"),

            ("ExportDialog.ExportTitle", "Exportar senhas"),
            ("ExportDialog.ImportTitle", "Importar senhas"),
            ("ExportDialog.ExportPassword", "Senha de exportação"),
            ("ExportDialog.Password", "Senha"),
            ("ExportDialog.InfoExport", "Defina uma senha para proteger o arquivo. Ela será exigida na importação - guarde-a bem, pois sem ela o arquivo não pode ser aberto."),
            ("ExportDialog.InfoImport", "Informe a senha definida quando o arquivo foi exportado."),
            ("ExportDialog.PasswordRequired", "Informe a senha."),
            ("ExportDialog.PasswordLength", "A senha deve ter pelo menos 8 caracteres."),
            ("ExportDialog.PasswordMismatch", "As senhas não coincidem."),

            ("Master.ChangeTitle", "Alterar senha mestra"),
            ("Master.CurrentPassword", "Senha mestra atual"),
            ("Master.NewPassword", "Nova senha mestra"),
            ("Master.ConfirmNewPassword", "Confirmar nova senha"),
            ("Master.ErrorCurrentRequired", "Informe a senha mestra atual."),
            ("Master.ErrorNewLength", "A nova senha deve ter pelo menos 8 caracteres."),
            ("Master.ErrorConfirmMismatch", "A confirmação não coincide com a nova senha."),
            ("Master.ChangeError", "Erro ao alterar a senha mestra: {0}"),
            ("Master.ChangedRestart", "Senha mestra alterada com sucesso.\n\nO aplicativo será reiniciado para aplicar a nova senha."),

            ("Biometric.Title", "Windows Hello"),
            ("Biometric.EnableOffer", "Deseja ativar o desbloqueio por Windows Hello neste dispositivo?\n\nA senha mestra continuará funcionando como fallback."),
            ("Biometric.Enabled", "Desbloqueio por Windows Hello ativado neste dispositivo."),
            ("Biometric.Disabled", "Desbloqueio por Windows Hello desativado neste dispositivo."),
            ("Biometric.DisableConfirm", "Desativar o desbloqueio por Windows Hello neste dispositivo?"),
            ("Biometric.DisabledAfterMasterChange", "O desbloqueio por Windows Hello foi desativado e poderá ser reativado após o reinício."),
            ("Biometric.DisabledAfterKdfUpgrade", "O cofre recebeu um reforço de segurança na derivação da chave. O desbloqueio por Windows Hello foi desativado e pode ser reativado agora no menu de configurações."),
            ("Biometric.NotEnabled", "O desbloqueio por Windows Hello não está ativado."),
            ("Biometric.InvalidVaultKey", "A chave do cofre não é válida para ativar o Windows Hello."),
            ("Biometric.InvalidRegistration", "O registro do Windows Hello não corresponde mais a este cofre. Entre com a senha mestra e ative novamente."),
            ("Biometric.EnableError", "Erro ao ativar o Windows Hello: {0}"),
            ("Biometric.UnlockError", "Erro ao desbloquear com Windows Hello: {0}"),
            ("Biometric.UnsupportedPlatform", "Windows Hello está disponível apenas no Windows 10 ou superior."),
            ("Biometric.AvailabilityError", "Não foi possível verificar a disponibilidade do Windows Hello: {0}"),
            ("Biometric.NotConfigured", "Configure um PIN, biometria ou Windows Hello nas configurações do Windows."),
            ("Biometric.RetriesExhausted", "Muitas tentativas de verificação. Tente novamente mais tarde."),
            ("Biometric.Unavailable", "Windows Hello está indisponível no momento."),

            ("Qr.RegenerateTitle", "Regerar QR code"),
            ("Qr.RegenerateInstruction", "Confirme sua senha mestra para gerar um novo QR code de backup."),
            ("Qr.GenerateButton", "Gerar QR code"),
            ("Qr.ErrorMasterRequired", "Digite sua senha mestra."),
            ("Qr.ErrorMasterIncorrect", "Senha mestra incorreta."),
            ("Qr.BackupTitle", "Backup da senha mestra"),
            ("Qr.BackupTitleWithType", "Backup da senha mestra (QR code)"),
            ("Qr.Offer", "Deseja salvar um QR code de backup da sua senha mestra?\n\nATENÇÃO: o QR code contém a versão senha-frase da sua senha mestra. Qualquer pessoa que escaneie a imagem poderá reconstruir a senha e acessar o cofre.\n\nGuarde o arquivo em local seguro e offline (ou impresso) - nunca em nuvem, e-mail ou pastas compartilhadas."),
            ("Qr.SavePickerTitle", "Salvar QR code da senha mestra"),
            ("Qr.SaveSuccess", "QR code salvo com sucesso. Guarde-o em local seguro."),
            ("Qr.SaveError", "Não foi possível salvar o QR code: {0}"),
            ("Qr.SheetSubtitle", "Backup da senha mestra"),
            ("Qr.SheetWarning1", "Contém a versão senha-frase da senha mestra."),
            ("Qr.SheetWarning2", "Guarde em local seguro e offline."),

            ("Db.SelectTitle", "Conectar banco de dados"),
            ("Db.ChooseType", "Escolha o tipo de banco de dados para conectar."),
            ("Db.ConnectionTitle", "Conexão"),
            ("Db.ConnectProviderTitle", "Conectar - {0}"),
            ("Db.TestConnection", "Testar conexão"),
            ("Db.DatabaseFile", "Arquivo do banco (.db)"),
            ("Db.Browse", "Procurar..."),
            ("Db.Host", "Host"),
            ("Db.Port", "Porta"),
            ("Db.Database", "Banco de dados"),
            ("Db.User", "Usuário"),
            ("Db.Password", "Senha"),
            ("Db.SQLitePickerTitle", "Arquivo do banco SQLite"),
            ("Db.ConnectionSuccess", "Conexão bem-sucedida."),
            ("Db.CreateTableTitle", "Criar tabela"),
            ("Db.TableMissing", "A tabela \"{0}\" não existe neste banco.\n\nDeseja criá-la agora?"),
            ("Db.ConnectionCanceledNoTable", "Conexão cancelada: a tabela não existe."),
            ("Db.ErrorFileRequired", "Informe o arquivo do banco."),
            ("Db.ErrorFieldsRequired", "Preencha host, banco de dados e usuário."),
            ("Db.ErrorInvalidPort", "Porta inválida."),
            ("Db.ConnectionFailed", "Falha na conexão: {0}"),
            ("Db.CannotConnect", "Não foi possível conectar: {0}"),
            ("Db.FeatureUnavailable", "Recurso indisponível nesta sessão."),
            ("Db.ConnectedMessage", "Conectado ao banco de dados e sincronizado com o cofre local.\n\n{0}"),
            ("Db.ConnectError", "Erro ao conectar: {0}"),

            ("Message.LoadError", "Erro ao carregar: {0}"),
            ("Message.FavoriteError", "Erro ao favoritar: {0}"),
            ("Message.DeleteTitle", "Excluir senha"),
            ("Message.MoveToTrash", "A credencial será movida para a lixeira. Você pode restaurá-la ou excluí-la definitivamente por lá."),
            ("Message.DeletePrompt", "Excluir \"{0}\"?\n\n{1}"),
            ("Message.DeleteError", "Erro ao excluir senha: {0}"),
            ("Nav.Trash", "Lixeira"),
            ("Trash.Empty", "A lixeira está vazia."),
            ("Trash.DeletedOn", "Excluída em {0}"),
            ("Trash.Restore", "Restaurar"),
            ("Trash.RestoreError", "Erro ao restaurar: {0}"),
            ("Trash.DeleteForever", "Excluir definitivamente"),
            ("Trash.DeleteForeverConfirm", "Excluir \"{0}\" definitivamente?\n\nEsta ação não pode ser desfeita."),
            ("Trash.DeleteForeverError", "Erro ao excluir definitivamente: {0}"),
            ("Trash.EmptyButton", "Esvaziar lixeira"),
            ("Trash.EmptyConfirmTitle", "Esvaziar lixeira"),
            ("Trash.EmptyConfirm", "Excluir definitivamente todos os itens da lixeira?\n\nEsta ação não pode ser desfeita."),
            ("Trash.EmptyError", "Erro ao esvaziar a lixeira: {0}"),
            ("Message.RenameDecryptError", "Não foi possível descriptografar a senha para salvar a alteração."),
            ("Message.RenameError", "Erro ao renomear serviço: {0}"),
            ("Message.AuditTitle", "Auditoria do cofre"),
            ("Message.AuditNoPasswords", "Não há senhas no cofre para auditar."),
            ("Message.AuditSuccess", "Auditoria concluída: nenhuma senha fraca, repetida ou antiga entre {0} senha(s)."),
            ("Message.AuditIncomplete", "{0} senha(s) não puderam ser analisadas por completo."),
            ("Message.AuditFoundHeader", "Encontradas {0} entrada(s) com alerta em {1} senha(s):"),
            ("Message.AuditWeakLine", "- {0} fraca(s)"),
            ("Message.AuditRepeatedLine", "- {0} repetida(s)"),
            ("Message.AuditOldLine", "- {0} antiga(s)"),
            ("Message.AuditUnreadableLine", "- {0} não auditada(s) por falha de leitura"),
            ("Message.AuditMarked", "As entradas afetadas foram marcadas com ⚠ na lista."),
            ("Message.AuditOldDefinition", "Senhas antigas são as sem atualização há {0} dias ou mais."),
            ("Message.AuditError", "Erro ao auditar o cofre: {0}"),

            ("SecurityReport.Title", "Relatório de segurança"),
            ("SecurityReport.ScoreLabel", "Pontuação do cofre"),
            ("SecurityReport.ScoreWeak", "Precisa de atenção"),
            ("SecurityReport.ScoreMedium", "Razoável"),
            ("SecurityReport.ScoreStrong", "Boa"),
            ("SecurityReport.ScoreExcellent", "Excelente"),
            ("SecurityReport.Weak", "Senhas fracas"),
            ("SecurityReport.Repeated", "Senhas repetidas"),
            ("SecurityReport.Old", "Senhas antigas"),
            ("SecurityReport.Compromised", "Senhas comprometidas"),
            ("SecurityReport.NoTotp", "Sem verificação em duas etapas"),
            ("SecurityReport.NoUrl", "Sem URL cadastrada"),
            ("SecurityReport.NoCategory", "Sem categoria definida"),
            ("SecurityReport.RowAutomationName", "{0}: {1}"),
            ("SecurityReport.CheckBreaches", "Verificar vazamentos agora"),
            ("SecurityReport.BreachesNotChecked", "Ainda não verificado nesta sessão"),
            ("SecurityReport.AllGood", "Nenhum problema encontrado. Continue assim!"),
            ("SecurityReport.ClearFilter", "Limpar filtro"),
            ("SecurityReport.FilterActive", "Filtrando por: {0}"),
            ("SecurityReport.BreachCheckError", "Erro ao verificar vazamentos: {0}"),
            ("Message.BreachTitle", "Verificar vazamentos"),
            ("Message.BreachNoPasswords", "Não há senhas no cofre para verificar."),
            ("Message.BreachDoneTitle", "Verificação concluída"),
            ("Message.BreachSuccess", "Boa notícia! Nenhuma das {0} senha(s) verificada(s) foi encontrada em vazamentos conhecidos."),
            ("Message.BreachWarning", "Atenção: {0} de {1} senha(s) aparecem em vazamentos conhecidos. Considere trocá-las (marcadas com ⚠)."),
            ("Message.NetworkErrorTitle", "Erro de rede"),
            ("Message.BreachNetworkError", "Não foi possível verificar os vazamentos.\nVerifique sua conexão com a internet.\n\nDetalhe: {0}"),
            ("Message.ExportEmpty", "O cofre está vazio. Não há nada para exportar."),
            ("Message.ExportSuccess", "{0} senha(s) exportada(s) com sucesso.\n\nGuarde bem a senha de exportação - sem ela o arquivo não pode ser aberto."),
            ("Message.ExportError", "Erro ao exportar: {0}"),
            ("Message.ImportEmpty", "Nenhuma senha encontrada no arquivo."),
            ("Message.ImportSuccess", "{0} senha(s) importada(s) com sucesso."),
            ("Message.ImportIgnored", "{0} ignorada(s) (já existiam ou inválidas)."),
            ("Message.ImportError", "Erro ao importar: {0}"),
            ("Message.CsvEmpty", "Nenhuma credencial encontrada no arquivo."),
            ("Message.CsvConfirm", "Detectamos um arquivo no formato {0} com {1} credencial(is).\n\nAs senhas serão adicionadas ao cofre (itens já existentes são ignorados). Deseja continuar?"),
            ("Message.CsvIgnored", "{0} ignorada(s) (já existiam ou incompletas)."),
            ("Message.CsvSecurity", "Por segurança, apague o arquivo CSV - ele guarda as senhas em texto aberto."),

            ("Row.FavoriteRemove", "Remover dos favoritos"),
            ("Row.FavoriteAdd", "Adicionar aos favoritos"),
            ("Row.CopyUser", "Copiar usuário"),
            ("Row.EditService", "Editar serviço"),
            ("Row.RevealPassword", "Revelar senha"),
            ("Row.HidePassword", "Ocultar senha"),
            ("Row.CopyPassword", "Copiar senha"),
            ("Row.EditEntry", "Editar entrada"),
            ("Row.DeleteEntry", "Excluir entrada"),
            ("Row.CopyTotp", "Copiar código 2FA"),
            ("Row.CopyRecoveryCode", "Copiar código de recuperação"),
            ("Row.UserCopied", "Usuário copiado"),
            ("Row.PasswordCopiedClearing", "Senha copiada — apagando em {0}s"),
            ("Row.CategoryTooltip", "Categoria: {0}"),
            ("Row.TagsTooltip", "Etiquetas: {0}\nCategoria: {1}"),
            ("Row.PasswordCompromised", "Senha comprometida - encontrada em {0:N0} vazamento(s). Troque-a!"),
            ("Row.AuditPrefix", "Auditoria: {0}"),
            ("Row.NotFoundInBreaches", " (não encontrada em vazamentos)"),
            ("Row.PasswordWeak", "Senha fraca"),
            ("Row.PasswordMedium", "Senha média"),
            ("Row.PasswordStrong", "Senha forte"),
            ("Row.AuditWeak", "senha fraca"),
            ("Row.AuditRepeatedWithCount", "senha repetida em {0} entradas"),
            ("Row.AuditRepeated", "senha repetida"),
            ("Row.AuditOld", "sem atualização há {0} dias"),
            ("Row.AuditAlert", "alerta"),

            ("Category.Work", "Trabalho"),
            ("Category.Personal", "Pessoal"),
            ("Category.Finance", "Finanças"),
            ("Category.Social", "Social"),
            ("Category.Other", "Outro"),

            ("Access.Title", "Acessibilidade"),
            ("Access.Colorblind", "Daltonismo"),
            ("Access.None", "Nenhum"),
            ("Access.Protanopia", "Protanopia"),
            ("Access.Deuteranopia", "Deuteranopia"),
            ("Access.Tritanopia", "Tritanopia"),
            ("Access.Monochromacy", "Monocromacia"),
            ("Access.HighContrast", "Alto contraste"),
            ("Access.TextSize", "Tamanho do texto"),
            ("Access.TextNormal", "Normal"),
            ("Access.TextLarge", "Grande"),
            ("Access.TextLarger", "Maior"),
            ("Access.ReduceMotion", "Reduzir animações"),
            ("Access.ScreenReader", "Leitor de tela"),
            ("Access.ScreenReaderHelp", "Modo mais descritivo para leitores de tela"),
            ("Access.Minimize", "Minimizar"),
            ("Access.Maximize", "Maximizar"),
            ("Access.Close", "Fechar janela"),
            ("A11y.PasswordFieldHelp", "Campo protegido. Use revelar senha apenas em local seguro."),
            ("A11y.GeneratedPassword", "Senha gerada"),
            ("A11y.GeneratedPasswordHelp", "O valor não é anunciado automaticamente. Use copiar para enviar à área de transferência."),
            ("A11y.GeneratedReady", "{0} {1}(s) gerada(s). Use copiar para enviar à área de transferência."),
            ("A11y.GeneratedList", "Lista de senhas geradas"),
            ("A11y.CopyGenerated", "Copiar item gerado"),
            ("A11y.CopyAllGenerated", "Copiar todos os itens gerados"),
            ("A11y.Copied", "{0} copiado para a área de transferência."),
            ("A11y.CopiedWillClear", "{0} copiado. Será apagado da área de transferência em {1} segundos."),
            ("A11y.PasswordVisible", "Senha visível na tela."),
            ("A11y.PasswordHidden", "Senha oculta."),
            ("A11y.PrivacyModeOn", "Modo privacidade ativado. Serviço, usuário e categoria ocultos na lista."),
            ("A11y.PrivacyModeOff", "Modo privacidade desativado."),
            ("A11y.RowHelp", "Use Tab para acessar as ações desta entrada."),
            ("A11y.EditServiceHelp", "Pressione Enter para editar o nome do serviço."),
            ("A11y.EditServiceMode", "Editando serviço. Pressione Enter para salvar ou Esc para cancelar."),
            ("A11y.SliderHelp", "Use as setas para ajustar. Home e End vão ao mínimo e máximo."),
            ("A11y.ToggleOn", "Ativado"),
            ("A11y.ToggleOff", "Desativado"),
            ("A11y.VaultStatus", "Status do cofre"),
            ("A11y.ConnectionStatus", "Status da conexão"),
            ("A11y.ResultsList", "Lista de senhas"),
            ("A11y.EmptyList", "Lista vazia"),
            ("A11y.OptionalField", "Campo opcional"),
            ("A11y.TotpPreview", "Prévia do código 2FA"),
            ("A11y.FilterOn", "Filtro ativado"),
            ("A11y.FilterOff", "Filtro desativado"),
            ("A11y.ScreenReaderEnabled", "Leitor de tela ativado."),
            ("A11y.ScreenReaderDisabled", "Leitor de tela desativado.")
        });
    }
}
