namespace CofreDeSenhas
{
    internal static partial class Idioma
    {
        private static IReadOnlyDictionary<string, string> CriarEn() => Mesclar(new (string, string)[]
        {
            ("App.Title", "Password Vault"),
            ("Common.Save", "Save"),
            ("Common.Cancel", "Cancel"),
            ("Common.Change", "Change"),
            ("Common.Connect", "Connect"),
            ("Common.Export", "Export"),
            ("Common.Import", "Import"),
            ("Common.Exit", "Exit"),
            ("Common.Close", "Close"),
            ("Common.Warning", "Warning"),
            ("Common.Error", "Error"),
            ("Common.Success", "Success"),
            ("Common.Validation", "Validation"),
            ("Common.Yes", "Yes"),
            ("Common.No", "No"),
            ("Common.AllFiles", "All files"),
            ("Common.ExportedVaultFile", "Exported vault"),
            ("Common.CsvFile", "CSV file"),
            ("Common.PngImage", "PNG image"),
            ("Common.SQLiteDatabase", "SQLite database"),
            ("Settings.Tooltip", "Settings"),
            ("Settings.SectionSecurity", "SECURITY"),
            ("Settings.ChangeMasterPassword", "Change master password..."),
            ("Settings.RegenerateQr", "Regenerate QR code..."),
            ("Settings.Backup", "Backup and restore..."),
            ("Settings.AutoLock", "Automatic lock"),
            ("Settings.Disabled", "Disabled"),
            ("Settings.AfterOneMinute", "After 1 minute"),
            ("Settings.AfterMinutes5", "After 5 minutes"),
            ("Settings.AfterMinutes15", "After 15 minutes"),
            ("Settings.AfterMinutes30", "After 30 minutes"),
            ("Settings.ClipboardClear", "Clipboard clearing"),
            ("Settings.ClipboardClear.After15", "After 15 seconds"),
            ("Settings.ClipboardClear.After30", "After 30 seconds"),
            ("Settings.ClipboardClear.After60", "After 60 seconds"),
            ("Settings.SectionAppearance", "APPEARANCE"),
            ("Settings.Language", "Language"),
            ("Settings.SectionData", "DATA"),
            ("Settings.ImportCsv", "Import from CSV / another manager..."),
            ("Settings.ConnectDatabase", "Connect database..."),
            ("Settings.DisconnectDatabase", "Disconnect database"),
            ("Settings.EnableWindowsHello", "Enable Windows Hello..."),
            ("Settings.DisableWindowsHello", "Disable Windows Hello"),
            ("Settings.OnlineIcons", "Online service icons"),
            ("Settings.OnlineIconsTooltip", "Downloads each service's real icon from the internet. When off, the vault shows initials only and never touches the network."),
            ("Settings.TrackUsageHistory", "Track usage history"),
            ("Settings.TrackUsageHistoryTooltip", "Records the date of the last password, username, and TOTP code copy for each credential. Turn off to stop recording new ones — dates already saved stay visible."),
            ("Settings.CheckUpdates", "Check for updates"),
            ("Settings.CheckUpdatesTooltip", "Checks GitHub releases to let you know when a newer version is out. Off by default; nothing is downloaded automatically, and nothing beyond this check is sent."),
            ("Update.Available", "New version available: {0}"),
            ("Update.Dismiss", "Dismiss update notice"),
            ("Icons.ConsentMessage", "To display each service's real icon, the app queries Google's favicon service, sending only the site's domain (for example, github.com). No password, username, or any other data leaves your computer, and downloaded icons are cached on disk to avoid repeated lookups.\n\nEnable online icon fetching?"),
            ("Theme.Light", "Light theme"),
            ("Theme.Dark", "Dark theme"),
            ("Privacy.Enable", "Enable privacy mode"),
            ("Privacy.Disable", "Disable privacy mode"),
            ("Settings.LockNow", "Lock now"),
            ("Settings.SectionHelp", "HELP"),
            ("Settings.KeyboardShortcuts", "Keyboard shortcuts..."),
            ("Shortcuts.Title", "Keyboard shortcuts"),
            ("Shortcuts.Search", "Search"),
            ("Shortcuts.NewPassword", "New password"),
            ("Shortcuts.OpenGenerator", "Open the generator"),
            ("Shortcuts.LockNow", "Lock now"),
            ("Shortcuts.CopyUser", "Copy the selected row's username"),
            ("Shortcuts.CopyPassword", "Copy the selected row's password"),
            ("Shortcuts.PrivacyMode", "Toggle privacy mode"),
            ("Shortcuts.CloseDialog", "Close dialog or cancel"),
            ("Shortcuts.SelectedRowHint", "The \"selected row\" is the one with keyboard focus; with none focused, the copy shortcuts use the first row in the list."),
            ("Backup.Title", "Vault backup"),
            ("Backup.Frequency", "Automatic backup frequency"),
            ("Backup.Manual", "Manual only"),
            ("Backup.Daily", "Daily"),
            ("Backup.Weekly", "Weekly"),
            ("Backup.MaxKept", "Maximum number of backups kept"),
            ("Backup.Now", "Back up now"),
            ("Backup.NeverDone", "No backup has been made yet."),
            ("Backup.LastDone", "Last backup: {0}"),
            ("Backup.Available", "Available backups"),
            ("Backup.None", "No backup available yet."),
            ("Backup.Restore", "Restore"),
            ("Backup.RestoreFrom", "Restore backup from {0}"),
            ("Backup.RestoreTitle", "Restore backup"),
            ("Backup.RestoreConfirm", "This will replace every password in the vault with the ones from the {0} backup. Changes made after that date will be lost. Continue?"),
            ("Backup.RestoreSuccess", "Backup restored successfully."),
            ("Backup.RestoreDisabledDbConnected", "Disconnect the database to restore a backup."),
            ("Backup.Success", "Backup created successfully."),
            ("Backup.Error", "Error processing the backup: {0}"),
            ("Vault.Header", "Password vault"),
            ("Vault.ImportTooltip", "Import passwords from a file"),
            ("Vault.ExportTooltip", "Export passwords to an encrypted file"),
            ("Vault.NewPassword", "New password"),
            ("Vault.SearchWatermark", "Search by service, user, or category"),
            ("Vault.BreachTooltip", "Check leaked passwords (Have I Been Pwned)"),
            ("Vault.AuditTooltip", "Audit weak, reused, or old passwords"),
            ("Vault.SecurityReportTooltip", "Vault security report"),
            ("Vault.FavoritesOnlyTooltip", "Favorites only"),
            ("Vault.Table.Service", "SERVICE"),
            ("Vault.Table.User", "USER"),
            ("Vault.Table.Category", "CATEGORY"),
            ("Vault.Table.Actions", "ACTIONS"),
            ("Vault.Table.Strength", "STRENGTH"),
            ("Vault.SortTooltip", "Sort"),
            ("Nav.Vault", "Vault"),
            ("Nav.Favorites", "Favorites"),
            ("Nav.Recent", "Recent"),
            ("Nav.Categories", "CATEGORIES"),
            ("Nav.Toggle", "Toggle navigation"),
            ("Details.Title", "Details"),
            ("Details.Close", "Close details"),
            ("Details.Save", "Save changes"),
            ("Details.Delete", "Delete"),
            ("Details.FullEdit", "Full edit..."),
            ("Generator.Close", "Close generator"),
            ("Row.CopyUrl", "Copy URL"),
            ("Footer.AutoLockOff", "Auto-lock disabled"),
            ("Footer.AutoLockCountdown", "{0} min until auto-lock"),
            ("Vault.Empty", "No passwords in the vault.\nClick \"New password\" to get started."),
            ("Vault.Filter.All", "All"),
            ("Vault.Counter.ItemSingular", "{0} item"),
            ("Vault.Counter.ItemPlural", "{0} items"),
            ("Vault.Status.PasswordSingular", "password"),
            ("Vault.Status.PasswordPlural", "passwords"),
            ("Vault.Status.FavoriteSingular", "favorite"),
            ("Vault.Status.FavoritePlural", "favorites"),
            ("Vault.Status.AuditOk", "audit OK"),
            ("Vault.Status.WithAlert", "{0} with alert"),
            ("Vault.Connection.Local", "Encrypted vault"),
            ("Vault.Connection.Connected", "Connected: {0}"),
            ("Vault.Connection.DatabaseUnavailable", "Database unavailable - using local vault"),
            ("Generator.Title", "Password generator"),
            ("Generator.Mode", "Mode"),
            ("Generator.Mode.Password", "Password"),
            ("Generator.Mode.Passphrase", "Passphrase"),
            ("Generator.Strength", "Strength"),
            ("Generator.Quantity", "Quantity"),
            ("Generator.Length", "Length"),
            ("Generator.Uppercase", "Uppercase letters (A-Z)"),
            ("Generator.Lowercase", "Lowercase letters (a-z)"),
            ("Generator.Numbers", "Numbers (0-9)"),
            ("Generator.Special", "Special characters (!@#)"),
            ("Generator.Words", "Words"),
            ("Generator.Separator", "Separator"),
            ("Generator.Separator.Space", "space"),
            ("Generator.Capitalize", "Capitalize words"),
            ("Generator.AddNumber", "Add number"),
            ("Generator.GeneratePassword", "Generate new password"),
            ("Generator.GeneratePassphrase", "Generate passphrase"),
            ("Generator.SaveToVault", "Save to vault"),
            ("Generator.Clear", "Clear"),
            ("Generator.CopyAll", "Copy all"),
            ("Generator.PasswordsGenerated", "Generated passwords ({0})"),
            ("Generator.PassphrasesGenerated", "Generated passphrases ({0})"),
            ("Generator.StrengthWeak", "Weak"),
            ("Generator.StrengthMedium", "Medium"),
            ("Generator.StrengthStrong", "Strong"),
            ("Generator.StrengthExcellent", "Excellent"),
            ("Generator.Item.Password", "password"),
            ("Generator.Item.Passphrase", "passphrase"),
            ("Generator.GenerateFirst", "Generate a {0} first"),
            ("Generator.PasswordCopied", "Password copied!"),
            ("Generator.PassphraseCopied", "Passphrase copied!"),
            ("Generator.PasswordCopiedClearing", "Password copied! It will be cleared from the clipboard in {0} seconds."),
            ("Generator.PassphraseCopiedClearing", "Passphrase copied! It will be cleared from the clipboard in {0} seconds."),
            ("Login.SubtitleCreate", "Create a master password to protect the vault"),
            ("Login.SubtitleUnlock", "Enter your master password to unlock"),
            ("Login.MasterPassword", "Master password"),
            ("Login.ConfirmPassword", "Confirm password"),
            ("Login.CreateVault", "Create vault"),
            ("Login.Unlock", "Unlock"),
            ("Login.WindowsHello", "Unlock with Windows Hello"),
            ("Login.EnableWindowsHello", "Enable Windows Hello"),
            ("Login.WindowsHelloHint", "Use your fingerprint, face, or PIN to unlock faster."),
            ("Login.Error.PasswordLength", "The password must be at least 8 characters long."),
            ("Login.Error.PasswordMismatch", "The passwords do not match."),
            ("Login.Error.MasterPasswordRequired", "Enter the master password."),
            ("Login.Error.TooManyAttempts", "Too many attempts. Wait 5 seconds."),
            ("Login.Error.WrongPassword", "Wrong password. Attempt {0} of 5."),
            ("Entry.NewTitle", "New password"),
            ("Entry.EditTitle", "Edit password"),
            ("Entry.EditTitleWithService", "Edit password - {0}"),
            ("Entry.ServiceName", "Service name"),
            ("Entry.UserEmail", "User / Email"),
            ("Entry.Password", "Password"),
            ("Entry.PasswordKeepCurrent", "Password  (leave blank to keep current)"),
            ("Entry.TotpOptional", "Two-factor authentication (2FA)  (optional)"),
            ("Entry.TotpRemove", "Two-factor authentication (2FA)  (blank removes it)"),
            ("Entry.TotpLabel", "Verification code (2FA)"),
            ("Entry.TotpWatermark", "Paste the secret key or otpauth:// link"),
            ("Entry.TotpExpiresIn", "expires in {0}s"),
            ("Entry.Category", "Category"),
            ("Entry.CustomCategory", "Custom category"),
            ("Entry.CustomCategoryWatermark", "E.g.: Games"),
            ("Entry.UrlOptional", "URL  (optional)"),
            ("Entry.NotesOptional", "Notes  (optional)"),
            ("Entry.Usage.Created", "Created on {0}"),
            ("Entry.Usage.Updated", "Edited on {0}"),
            ("Entry.Usage.CopyPasswordLabel", "Password copied: {0}"),
            ("Entry.Usage.CopyUserLabel", "Username copied: {0}"),
            ("Entry.Usage.CopyTotpLabel", "TOTP copied: {0}"),
            ("Entry.Usage.Never", "never"),
            ("Entry.CreateRequired", "Fill in the required fields (name, user, and password)."),
            ("Entry.EditRequired", "Fill in the required fields."),
            ("Entry.TotpInvalid", "The two-factor authentication key is invalid. Paste the secret key (Base32) or an otpauth:// link."),
            ("Entry.CreateError", "Error creating password: {0}"),
            ("Entry.UpdateError", "Error updating password: {0}"),
            ("Entry.RecoverCurrentPasswordError", "Could not recover the current password. Enter a new password."),
            ("Entry.HistoryHeader", "Password history ({0})"),
            ("Entry.HistoryReplacedOn", "Replaced on {0}"),
            ("Entry.HistoryUse", "Use"),
            ("Entry.HistoryUseTooltip", "Fill the field with this password"),
            ("A11y.PreviousPassword", "Previous password"),

            ("Entry.RecoveryCodes", "Recovery codes"),
            ("Entry.RecoveryCodesWatermark", "Paste one code per line"),
            ("Entry.RecoveryCodesAdd", "Add"),
            ("Entry.RecoveryCodeMarkUsed", "Mark as used"),
            ("Entry.RecoveryCodeUnmark", "Unmark"),
            ("Entry.RecoveryCodeRemove", "Remove"),
            ("Entry.RecoveryCodeRemoveConfirm", "Remove this recovery code? This action cannot be undone."),
            ("Entry.RecoveryCodesAddError", "Error adding recovery codes: {0}"),
            ("Entry.RecoveryCodeMarkError", "Error updating the recovery code: {0}"),
            ("Entry.RecoveryCodeRemoveError", "Error removing the recovery code: {0}"),
            ("A11y.RecoveryCode", "Recovery code"),
            ("ExportDialog.ExportTitle", "Export passwords"),
            ("ExportDialog.ImportTitle", "Import passwords"),
            ("ExportDialog.ExportPassword", "Export password"),
            ("ExportDialog.Password", "Password"),
            ("ExportDialog.InfoExport", "Set a password to protect the file. It will be required during import - keep it safe, because the file cannot be opened without it."),
            ("ExportDialog.InfoImport", "Enter the password set when the file was exported."),
            ("ExportDialog.PasswordRequired", "Enter the password."),
            ("ExportDialog.PasswordLength", "The password must be at least 8 characters long."),
            ("ExportDialog.PasswordMismatch", "The passwords do not match."),
            ("Master.ChangeTitle", "Change master password"),
            ("Master.CurrentPassword", "Current master password"),
            ("Master.NewPassword", "New master password"),
            ("Master.ConfirmNewPassword", "Confirm new password"),
            ("Master.ErrorCurrentRequired", "Enter the current master password."),
            ("Master.ErrorNewLength", "The new password must be at least 8 characters long."),
            ("Master.ErrorConfirmMismatch", "The confirmation does not match the new password."),
            ("Master.ChangeError", "Error changing the master password: {0}"),
            ("Master.ChangedRestart", "Master password changed successfully.\n\nThe application will restart to apply the new password."),
            ("Biometric.Title", "Windows Hello"),
            ("Biometric.EnableOffer", "Do you want to enable Windows Hello unlock on this device?\n\nThe master password will continue to work as a fallback."),
            ("Biometric.Enabled", "Windows Hello unlock is enabled on this device."),
            ("Biometric.Disabled", "Windows Hello unlock is disabled on this device."),
            ("Biometric.DisableConfirm", "Disable Windows Hello unlock on this device?"),
            ("Biometric.DisabledAfterMasterChange", "Windows Hello unlock was disabled and can be enabled again after restart."),
            ("Biometric.DisabledAfterKdfUpgrade", "Your vault received a security upgrade to its key derivation. Windows Hello unlock was disabled and can be re-enabled now from the settings menu."),
            ("Biometric.NotEnabled", "Windows Hello unlock is not enabled."),
            ("Biometric.InvalidVaultKey", "The vault key is not valid for enabling Windows Hello."),
            ("Biometric.InvalidRegistration", "The Windows Hello registration no longer matches this vault. Sign in with the master password and enable it again."),
            ("Biometric.EnableError", "Error enabling Windows Hello: {0}"),
            ("Biometric.UnlockError", "Error unlocking with Windows Hello: {0}"),
            ("Biometric.UnsupportedPlatform", "Windows Hello is available only on Windows 10 or later."),
            ("Biometric.AvailabilityError", "Could not check Windows Hello availability: {0}"),
            ("Biometric.NotConfigured", "Set up a PIN, biometrics, or Windows Hello in Windows settings."),
            ("Biometric.RetriesExhausted", "Too many verification attempts. Try again later."),
            ("Biometric.Unavailable", "Windows Hello is currently unavailable."),
            ("Qr.RegenerateTitle", "Regenerate QR code"),
            ("Qr.RegenerateInstruction", "Confirm your master password to generate a new backup QR code."),
            ("Qr.GenerateButton", "Generate QR code"),
            ("Qr.ErrorMasterRequired", "Enter your master password."),
            ("Qr.ErrorMasterIncorrect", "Incorrect master password."),
            ("Qr.BackupTitle", "Master password backup"),
            ("Qr.BackupTitleWithType", "Master password backup (QR code)"),
            ("Qr.Offer", "Do you want to save a backup QR code for your master password?\n\nWARNING: the QR code contains the passphrase version of your master password. Anyone who scans the image can reconstruct the password and access the vault.\n\nKeep the file in a safe offline place (or printed) - never in cloud storage, email, or shared folders."),
            ("Qr.SavePickerTitle", "Save master password QR code"),
            ("Qr.SaveSuccess", "QR code saved successfully. Keep it in a safe place."),
            ("Qr.SaveError", "Could not save the QR code: {0}"),
            ("Qr.SheetSubtitle", "Master password backup"),
            ("Qr.SheetWarning1", "Contains the passphrase version of the master password."),
            ("Qr.SheetWarning2", "Keep in a safe offline place."),
            ("Db.SelectTitle", "Connect database"),
            ("Db.ChooseType", "Choose the database type to connect."),
            ("Db.ConnectionTitle", "Connection"),
            ("Db.ConnectProviderTitle", "Connect - {0}"),
            ("Db.TestConnection", "Test connection"),
            ("Db.DatabaseFile", "Database file (.db)"),
            ("Db.Browse", "Browse..."),
            ("Db.Host", "Host"),
            ("Db.Port", "Port"),
            ("Db.Database", "Database"),
            ("Db.User", "User"),
            ("Db.Password", "Password"),
            ("Db.SQLitePickerTitle", "SQLite database file"),
            ("Db.ConnectionSuccess", "Connection successful."),
            ("Db.CreateTableTitle", "Create table"),
            ("Db.TableMissing", "The table \"{0}\" does not exist in this database.\n\nCreate it now?"),
            ("Db.ConnectionCanceledNoTable", "Connection canceled: the table does not exist."),
            ("Db.ErrorFileRequired", "Enter the database file."),
            ("Db.ErrorFieldsRequired", "Fill in host, database, and user."),
            ("Db.ErrorInvalidPort", "Invalid port."),
            ("Db.ConnectionFailed", "Connection failed: {0}"),
            ("Db.CannotConnect", "Could not connect: {0}"),
            ("Db.FeatureUnavailable", "Feature unavailable in this session."),
            ("Db.ConnectedMessage", "Connected to the database and synchronized with the local vault.\n\n{0}"),
            ("Db.ConnectError", "Error connecting: {0}"),
            ("Message.LoadError", "Error loading: {0}"),
            ("Message.FavoriteError", "Error changing favorite: {0}"),
            ("Message.DeleteTitle", "Delete password"),
            ("Message.MoveToTrash", "The credential will be moved to the trash. You can restore it or delete it permanently from there."),
            ("Message.DeletePrompt", "Delete \"{0}\"?\n\n{1}"),
            ("Message.DeleteError", "Error deleting password: {0}"),
            ("Nav.Trash", "Trash"),
            ("Trash.Empty", "The trash is empty."),
            ("Trash.DeletedOn", "Deleted on {0}"),
            ("Trash.Restore", "Restore"),
            ("Trash.RestoreError", "Error restoring: {0}"),
            ("Trash.DeleteForever", "Delete permanently"),
            ("Trash.DeleteForeverConfirm", "Permanently delete \"{0}\"?\n\nThis action cannot be undone."),
            ("Trash.DeleteForeverError", "Error deleting permanently: {0}"),
            ("Trash.EmptyButton", "Empty trash"),
            ("Trash.EmptyConfirmTitle", "Empty trash"),
            ("Trash.EmptyConfirm", "Permanently delete every item in the trash?\n\nThis action cannot be undone."),
            ("Trash.EmptyError", "Error emptying the trash: {0}"),
            ("Message.RenameDecryptError", "Could not decrypt the password to save the change."),
            ("Message.RenameError", "Error renaming service: {0}"),
            ("Message.AuditTitle", "Vault audit"),
            ("Message.AuditNoPasswords", "There are no passwords in the vault to audit."),
            ("Message.AuditSuccess", "Audit complete: no weak, reused, or old passwords among {0} password(s)."),
            ("Message.AuditIncomplete", "{0} password(s) could not be fully analyzed."),
            ("Message.AuditFoundHeader", "Found {0} entries with alerts among {1} password(s):"),
            ("Message.AuditWeakLine", "- {0} weak"),
            ("Message.AuditRepeatedLine", "- {0} reused"),
            ("Message.AuditOldLine", "- {0} old"),
            ("Message.AuditUnreadableLine", "- {0} not audited due to read failure"),
            ("Message.AuditMarked", "Affected entries were marked with ⚠ in the list."),
            ("Message.AuditOldDefinition", "Old passwords are those not updated for {0} days or more."),
            ("Message.AuditError", "Error auditing the vault: {0}"),

            ("SecurityReport.Title", "Security report"),
            ("SecurityReport.ScoreLabel", "Vault score"),
            ("SecurityReport.ScoreWeak", "Needs attention"),
            ("SecurityReport.ScoreMedium", "Fair"),
            ("SecurityReport.ScoreStrong", "Good"),
            ("SecurityReport.ScoreExcellent", "Excellent"),
            ("SecurityReport.Weak", "Weak passwords"),
            ("SecurityReport.Repeated", "Reused passwords"),
            ("SecurityReport.Old", "Old passwords"),
            ("SecurityReport.Compromised", "Compromised passwords"),
            ("SecurityReport.NoTotp", "No two-factor authentication"),
            ("SecurityReport.NoUrl", "No URL saved"),
            ("SecurityReport.NoCategory", "No category set"),
            ("SecurityReport.RowAutomationName", "{0}: {1}"),
            ("SecurityReport.CheckBreaches", "Check breaches now"),
            ("SecurityReport.BreachesNotChecked", "Not checked yet this session"),
            ("SecurityReport.AllGood", "No issues found. Keep it up!"),
            ("SecurityReport.ClearFilter", "Clear filter"),
            ("SecurityReport.FilterActive", "Filtering by: {0}"),
            ("SecurityReport.BreachCheckError", "Error checking breaches: {0}"),
            ("Message.BreachTitle", "Check breaches"),
            ("Message.BreachNoPasswords", "There are no passwords in the vault to check."),
            ("Message.BreachDoneTitle", "Check complete"),
            ("Message.BreachSuccess", "Good news! None of the {0} checked password(s) were found in known breaches."),
            ("Message.BreachWarning", "Warning: {0} of {1} password(s) appear in known breaches. Consider changing them (marked with ⚠)."),
            ("Message.NetworkErrorTitle", "Network error"),
            ("Message.BreachNetworkError", "Could not check breaches.\nCheck your internet connection.\n\nDetail: {0}"),
            ("Message.ExportEmpty", "The vault is empty. There is nothing to export."),
            ("Message.ExportSuccess", "{0} password(s) exported successfully.\n\nKeep the export password safe - without it, the file cannot be opened."),
            ("Message.ExportError", "Error exporting: {0}"),
            ("Message.ImportEmpty", "No passwords found in the file."),
            ("Message.ImportSuccess", "{0} password(s) imported successfully."),
            ("Message.ImportIgnored", "{0} ignored (already existed or invalid)."),
            ("Message.ImportError", "Error importing: {0}"),
            ("Message.CsvEmpty", "No credentials found in the file."),
            ("Message.CsvConfirm", "Detected a {0} file with {1} credential(s).\n\nPasswords will be added to the vault (existing items are ignored). Continue?"),
            ("Message.CsvIgnored", "{0} ignored (already existed or incomplete)."),
            ("Message.CsvSecurity", "For security, delete the CSV file - it stores passwords in plain text."),
            ("Row.FavoriteRemove", "Remove from favorites"),
            ("Row.FavoriteAdd", "Add to favorites"),
            ("Row.CopyUser", "Copy user"),
            ("Row.EditService", "Edit service"),
            ("Row.RevealPassword", "Reveal password"),
            ("Row.HidePassword", "Hide password"),
            ("Row.CopyPassword", "Copy password"),
            ("Row.EditEntry", "Edit entry"),
            ("Row.DeleteEntry", "Delete entry"),
            ("Row.CopyTotp", "Copy 2FA code"),
            ("Row.CopyRecoveryCode", "Copy recovery code"),
            ("Row.UserCopied", "User copied"),
            ("Row.PasswordCopiedClearing", "Password copied — clearing in {0}s"),
            ("Row.CategoryTooltip", "Category: {0}"),
            ("Row.TagsTooltip", "Tags: {0}\nCategory: {1}"),
            ("Row.PasswordCompromised", "Compromised password - found in {0:N0} breach(es). Change it!"),
            ("Row.AuditPrefix", "Audit: {0}"),
            ("Row.NotFoundInBreaches", " (not found in breaches)"),
            ("Row.PasswordWeak", "Weak password"),
            ("Row.PasswordMedium", "Medium password"),
            ("Row.PasswordStrong", "Strong password"),
            ("Row.AuditWeak", "weak password"),
            ("Row.AuditRepeatedWithCount", "password reused in {0} entries"),
            ("Row.AuditRepeated", "reused password"),
            ("Row.AuditOld", "not updated for {0} days"),
            ("Row.AuditAlert", "alert"),
            ("Category.Work", "Work"),
            ("Category.Personal", "Personal"),
            ("Category.Finance", "Finance"),
            ("Category.Social", "Social"),
            ("Category.Other", "Other"),
            ("Access.Title", "Accessibility"),
            ("Access.Colorblind", "Color blindness"),
            ("Access.None", "None"),
            ("Access.Protanopia", "Protanopia"),
            ("Access.Deuteranopia", "Deuteranopia"),
            ("Access.Tritanopia", "Tritanopia"),
            ("Access.Monochromacy", "Monochromacy"),
            ("Access.HighContrast", "High contrast"),
            ("Access.TextSize", "Text size"),
            ("Access.TextNormal", "Normal"),
            ("Access.TextLarge", "Large"),
            ("Access.TextLarger", "Larger"),
            ("Access.ReduceMotion", "Reduce motion"),
            ("Access.ScreenReader", "Screen reader"),
            ("Access.ScreenReaderHelp", "More descriptive mode for screen readers"),
            ("Access.Minimize", "Minimize"),
            ("Access.Maximize", "Maximize"),
            ("Access.Close", "Close window"),
            ("A11y.PasswordFieldHelp", "Protected field. Reveal the password only in a safe place."),
            ("A11y.GeneratedPassword", "Generated password"),
            ("A11y.GeneratedPasswordHelp", "The value is not announced automatically. Use copy to send it to the clipboard."),
            ("A11y.GeneratedReady", "{0} {1}(s) generated. Use copy to send to the clipboard."),
            ("A11y.GeneratedList", "Generated passwords list"),
            ("A11y.CopyGenerated", "Copy generated item"),
            ("A11y.CopyAllGenerated", "Copy all generated items"),
            ("A11y.Copied", "{0} copied to clipboard."),
            ("A11y.CopiedWillClear", "{0} copied. It will be cleared from the clipboard in {1} seconds."),
            ("A11y.PasswordVisible", "Password visible on screen."),
            ("A11y.PasswordHidden", "Password hidden."),
            ("A11y.PrivacyModeOn", "Privacy mode on. Service, username, and category hidden in the list."),
            ("A11y.PrivacyModeOff", "Privacy mode off."),
            ("A11y.RowHelp", "Use Tab to access this entry's actions."),
            ("A11y.EditServiceHelp", "Press Enter to edit the service name."),
            ("A11y.EditServiceMode", "Editing service. Press Enter to save or Esc to cancel."),
            ("A11y.SliderHelp", "Use arrow keys to adjust. Home and End go to minimum and maximum."),
            ("A11y.ToggleOn", "On"),
            ("A11y.ToggleOff", "Off"),
            ("A11y.VaultStatus", "Vault status"),
            ("A11y.ConnectionStatus", "Connection status"),
            ("A11y.ResultsList", "Password list"),
            ("A11y.EmptyList", "Empty list"),
            ("A11y.OptionalField", "Optional field"),
            ("A11y.TotpPreview", "2FA code preview"),
            ("A11y.FilterOn", "Filter on"),
            ("A11y.FilterOff", "Filter off"),
            ("A11y.ScreenReaderEnabled", "Screen reader enabled."),
            ("A11y.ScreenReaderDisabled", "Screen reader disabled.")
        });
    }
}
