namespace CofreDeSenhas
{
    internal static partial class Idioma
    {
        private static IReadOnlyDictionary<string, string> CriarPtBr() => Criar(new (string, string)[]
        {
            ("App.Title", "Cofre de Senhas"),
            ("Common.Save", "Salvar"),
            ("Common.Apply", "Aplicar"),
            ("Common.Cancel", "Cancelar"),
            ("Common.Change", "Alterar"),
            ("Common.Connect", "Conectar"),
            ("Common.Export", "Exportar"),
            ("Common.Import", "Importar"),
            ("Common.Exit", "Sair"),
            ("Common.Close", "Fechar"),
            ("Common.Warning", "Aviso"),
            ("Common.Error", "Erro"),
            ("Common.UnexpectedError", "Erro inesperado: {0}"),
            ("Common.Success", "Sucesso"),
            ("Common.Validation", "Validação"),
            ("Common.Yes", "Sim"),
            ("Common.No", "Não"),
            ("Common.AllFiles", "Todos os arquivos"),
            ("Common.ExportedVaultFile", "Cofre exportado"),
            ("Common.CsvFile", "Arquivo CSV"),
            ("Common.PngImage", "Imagem PNG"),
            ("Common.AndMore", "+{0} mais"),
            ("Common.SQLiteDatabase", "Banco SQLite"),

            ("Settings.Tooltip", "Configurações"),
            ("Settings.SectionSecurity", "SEGURANÇA"),
            ("Settings.ChangeMasterPassword", "Alterar senha mestra..."),
            ("Settings.RegenerateQr", "Regerar QR code..."),
            ("Settings.Backup", "Backup e restauração..."),
            ("Settings.AutoLock", "Bloqueio automático"),
            ("Settings.Disabled", "Desativado"),
            ("Settings.AfterOneMinute", "Após 1 minuto"),
            ("Settings.AfterMinutes5", "Após 5 minutos"),
            ("Settings.AfterMinutes15", "Após 15 minutos"),
            ("Settings.AfterMinutes30", "Após 30 minutos"),
            ("Settings.ClipboardClear", "Limpeza da área de transferência"),
            ("Settings.ClipboardClear.After15", "Após 15 segundos"),
            ("Settings.ClipboardClear.After30", "Após 30 segundos"),
            ("Settings.ClipboardClear.After60", "Após 60 segundos"),
            ("Settings.SectionAppearance", "APARÊNCIA"),
            ("Settings.Language", "Idioma"),
            ("Settings.SectionData", "DADOS"),
            ("Settings.ImportCsv", "Importar de CSV / outro gerenciador..."),
            ("Settings.ConnectDatabase", "Conectar banco de dados..."),
            ("Settings.ConnectDatabaseTooltip", "Recurso self-hosted/compartilhado — para sincronizar só os seus próprios dispositivos, use a Sincronização por pasta."),
            ("Settings.DisconnectDatabase", "Desconectar do banco"),
            ("Settings.EnableWindowsHello", "Ativar Windows Hello..."),
            ("Settings.DisableWindowsHello", "Desativar Windows Hello"),
            ("Settings.OnlineIcons", "Ícones online dos serviços"),
            ("Settings.OnlineIconsTooltip", "Baixa da internet o ícone real de cada serviço. Desativado, o cofre mostra apenas iniciais e não acessa a rede."),
            ("Settings.TrackUsageHistory", "Registrar histórico de uso"),
            ("Settings.TrackUsageHistoryTooltip", "Registra a data da última cópia de senha, usuário e código TOTP de cada credencial. Desative para parar de guardar esses registros — datas já salvas continuam visíveis."),
            ("Settings.CheckUpdates", "Verificar atualizações"),
            ("Settings.CheckUpdatesTooltip", "Consulta as releases do GitHub para avisar quando houver uma versão mais nova. Desligado por padrão; nenhum download é feito automaticamente, e nada além dessa consulta é enviado."),
            ("Update.Available", "Nova versão disponível: {0}"),
            ("Update.Now", "Atualizar agora"),
            ("Update.ConfirmTitle", "Atualizar para a versão {0}"),
            ("Update.ConfirmMessage", "Confira o que muda na versão {0} antes de continuar. A atualização será baixada e aplicada automaticamente."),
            ("Update.NoReleaseNotes", "Nenhuma descrição de mudanças foi encontrada para esta versão."),
            ("Update.Downloading", "Baixando..."),
            ("Update.Failed", "Não foi possível atualizar automaticamente. Abrindo a página de lançamentos para baixar manualmente."),
            ("Update.Error.NoAssets", "Não foi possível obter os arquivos da versão."),
            ("Update.Error.ExecutableNotFound", "Não foi possível localizar o executável atual."),
            ("Update.Error.AssetNotFound", "Arquivo de atualização não encontrado nesta versão."),
            ("Update.Error.ChecksumUnavailable", "Não foi possível verificar a integridade do arquivo."),
            ("Update.Error.ChecksumMismatch", "A verificação de integridade do arquivo baixado falhou."),
            ("Update.Error.SignatureMissing", "Esta versão não traz a assinatura de atualização. Baixe a nova versão manualmente pela página de lançamentos."),
            ("Update.Error.SignatureInvalid", "A assinatura da atualização não confere. O arquivo pode ter sido adulterado — não instale."),
            ("Update.Dismiss", "Dispensar aviso de atualização"),
            ("Icons.ConsentMessage", "Para exibir o ícone real de cada serviço, o aplicativo consulta o serviço de ícones do Google enviando apenas o domínio do site (por exemplo, github.com). Nenhuma senha, usuário ou outro dado sai do seu computador, e os ícones baixados ficam em cache no disco para evitar novas consultas.\n\nDeseja ativar a busca de ícones online?"),
            ("Privacy.Enable", "Ativar modo privacidade"),
            ("Privacy.Disable", "Desativar modo privacidade"),
            ("Settings.LockNow", "Bloquear agora"),
            ("Settings.SectionHelp", "AJUDA"),
            ("Settings.KeyboardShortcuts", "Atalhos de teclado..."),
            ("Settings.SectionDanger", "ZONA DE PERIGO"),
            ("Settings.ClearVault", "Limpar cofre..."),
            ("Settings.DeleteVault", "Excluir cofre..."),
            ("Shortcuts.Title", "Atalhos de teclado"),
            ("Shortcuts.Search", "Buscar"),
            ("Shortcuts.NewPassword", "Nova senha"),
            ("Shortcuts.OpenGenerator", "Abrir o gerador"),
            ("Shortcuts.LockNow", "Bloquear agora"),
            ("Shortcuts.CopyUser", "Copiar usuário da linha selecionada"),
            ("Shortcuts.CopyPassword", "Copiar senha da linha selecionada"),
            ("Shortcuts.PrivacyMode", "Ativar/desativar modo privacidade"),
            ("Shortcuts.CloseDialog", "Fechar diálogo ou cancelar"),
            ("Shortcuts.SelectedRowHint", "A \"linha selecionada\" é a que está com foco de teclado; sem foco em nenhuma, os atalhos de cópia usam a primeira linha da lista."),

            ("Backup.Title", "Backup do cofre"),
            ("Backup.Frequency", "Frequência do backup automático"),
            ("Backup.Manual", "Manual apenas"),
            ("Backup.Daily", "Diário"),
            ("Backup.Weekly", "Semanal"),
            ("Backup.MaxKept", "Quantidade máxima de backups mantidos"),
            ("Backup.Now", "Fazer backup agora"),
            ("Backup.NeverDone", "Nenhum backup realizado ainda."),
            ("Backup.LastDone", "Último backup: {0}"),
            ("Backup.Available", "Backups disponíveis"),
            ("Backup.None", "Nenhum backup disponível ainda."),
            ("Backup.Restore", "Restaurar"),
            ("Backup.RestoreFrom", "Restaurar backup de {0}"),
            ("Backup.RestoreTitle", "Restaurar backup"),
            ("Backup.RestoreConfirm", "Isso vai substituir todas as senhas do cofre pelas do backup de {0}. Alterações feitas depois dessa data serão perdidas. Deseja continuar?"),
            ("Backup.RestoreSuccess", "Backup restaurado com sucesso."),
            ("Backup.RestoreDisabledDbConnected", "Desconecte o banco de dados para restaurar um backup."),
            ("Backup.Success", "Backup criado com sucesso."),
            ("Backup.Error", "Erro ao processar o backup: {0}"),

            ("Settings.Sync", "Sincronização..."),
            ("Sync.Title", "Sincronização entre dispositivos"),
            ("Sync.Explanation", "Sincroniza o cofre com outros dispositivos através de uma pasta compartilhada (ex.: Dropbox, OneDrive, Google Drive). Os dados ficam cifrados de ponta a ponta com a sua senha mestra antes de sair deste dispositivo — o provedor de nuvem nunca vê texto puro."),
            ("Sync.Enable", "Escolher pasta e ativar"),
            ("Sync.Folder", "Pasta de sincronização"),
            ("Sync.Frequency", "Sincronizar automaticamente"),
            ("Sync.EveryMinutes", "A cada {0} minutos"),
            ("Sync.Now", "Sincronizar agora"),
            ("Sync.LastDone", "Última sincronização: {0}"),
            ("Sync.NeverDone", "Ainda não sincronizado."),
            ("Sync.ChooseFolder", "Escolha a pasta de sincronização"),
            ("Sync.EnableError", "Erro ao ativar a sincronização: {0}"),
            ("Sync.Error.WriteFailed", "Não foi possível gravar o arquivo de sincronização. Verifique se a pasta está acessível."),
            ("Sync.Error.ReadFailed", "Não foi possível ler o arquivo de sincronização. Tente novamente em instantes."),
            ("Sync.Success", "Sincronização concluída com sucesso."),
            ("Sync.AlreadyInProgress", "Já existe uma sincronização em andamento. Aguarde ela terminar antes de tentar de novo."),
            ("Sync.Error", "Erro ao sincronizar. Verifique se a pasta está acessível."),
            ("Sync.Disable", "Desativar sincronização"),
            ("Sync.DisableConfirm", "Desativar a sincronização? Os dispositivos param de trocar dados entre si, mas nada é apagado."),
            ("Sync.ConfirmMasterTitle", "Confirmar senha mestra"),
            ("Sync.ConfirmMasterInstruction", "Digite a senha mestra deste cofre para ativar a sincronização. Use a mesma senha mestra em todos os dispositivos que vão compartilhar esta pasta."),
            ("Sync.Confirm", "Confirmar"),
            ("Sync.ConflictsTooltip", "Ver atividade de sincronização"),
            ("Sync.ConflictsTitle", "Atividade de sincronização"),
            ("Sync.ConflictsExplanation", "Registros que foram atualizados a partir de outro dispositivo/cliente na última sincronização com o banco, que foram rejeitados por falha na verificação de integridade, ou que não têm assinatura de integridade gravada."),
            ("Sync.ConflictType.ConcurrentEdit", "Atualizado por outro dispositivo"),
            ("Sync.ConflictType.IntegrityViolated", "Dado rejeitado: falha na verificação de integridade"),
            ("Sync.ConflictType.IntegrityMissing", "Sem assinatura de integridade — verifique se não foi adulterado"),

            ("Vault.Header", "Cofre de senhas"),
            ("Vault.ImportTooltip", "Importar senhas de um arquivo"),
            ("Vault.ExportTooltip", "Exportar senhas para um arquivo criptografado"),
            ("Vault.NewPassword", "Nova senha"),
            ("Vault.SearchWatermark", "Buscar por serviço, usuário ou categoria"),
            ("Vault.BreachTooltip", "Verificar senhas vazadas (Have I Been Pwned)"),
            ("Vault.AuditTooltip", "Auditar senhas fracas, repetidas ou antigas"),
            ("Vault.SecurityReportTooltip", "Relatório de segurança do cofre"),
            ("Vault.FavoritesOnlyTooltip", "Somente favoritas"),
            ("Vault.TagFilter", "Filtrar por etiqueta"),
            ("Vault.Table.Service", "SERVIÇO"),
            ("Vault.Table.User", "USUÁRIO"),
            ("Vault.Table.Category", "CATEGORIA"),
            ("Vault.Table.Actions", "AÇÕES"),
            ("Vault.Table.Strength", "FORÇA"),
            ("Vault.SortTooltip", "Ordenar"),
            ("Nav.Vault", "Cofre"),
            ("Nav.Favorites", "Favoritas"),
            ("Nav.Recent", "Recentes"),
            ("Nav.Categories", "CATEGORIAS"),
            ("Nav.Toggle", "Alternar navegação"),
            ("Details.Title", "Detalhes"),
            ("Details.Close", "Fechar detalhes"),
            ("Details.Save", "Salvar alterações"),
            ("Details.Delete", "Excluir"),
            ("Details.FullEdit", "Edição completa..."),
            ("Generator.Close", "Fechar gerador"),
            ("Row.CopyUrl", "Copiar URL"),
            ("Footer.AutoLockOff", "Bloqueio automático desativado"),
            ("Footer.AutoLockCountdown", "{0} min até bloqueio automático"),
            ("Vault.Empty", "Nenhuma senha no cofre.\nClique em \"Nova senha\" para começar."),
            ("Vault.Filter.All", "Todas"),
            ("Vault.Counter.ItemSingular", "{0} item"),
            ("Vault.Counter.ItemPlural", "{0} itens"),
            ("Batch.CountSingular", "{0} selecionado"),
            ("Batch.CountPlural", "{0} selecionados"),
            ("Batch.Favorite", "Favoritar"),
            ("Batch.AddTag", "Adicionar etiqueta"),
            ("Batch.AddTagWatermark", "Nome da etiqueta"),
            ("Batch.Trash", "Mover para lixeira"),
            ("Batch.TrashConfirm", "Mover {0} credenciais para a lixeira? Você pode restaurá-las ou excluí-las definitivamente por lá."),
            ("Batch.CancelSelection", "Cancelar seleção"),
            ("Vault.Status", "{0} {1} • {2} {3}"),
            ("Vault.Status.PasswordSingular", "senha"),
            ("Vault.Status.PasswordPlural", "senhas"),
            ("Vault.Status.FavoriteSingular", "favorita"),
            ("Vault.Status.FavoritePlural", "favoritas"),
            ("Vault.Status.AuditOk", "auditoria OK"),
            ("Vault.Status.WithAlert", "{0} com alerta"),
            ("Vault.Connection.Local", "Cofre criptografado"),
            ("Vault.Connection.Connected", "Conectado: {0}"),
            ("Vault.Connection.DatabaseUnavailable", "Banco indisponível - usando cofre local"),

            ("Generator.Title", "Gerador de senha"),
            ("Generator.Mode", "Modo"),
            ("Generator.Mode.Password", "Senha"),
            ("Generator.Mode.Passphrase", "Frase-senha"),
            ("Generator.Strength", "Força"),
            ("Generator.Quantity", "Quantidade"),
            ("Generator.Length", "Comprimento"),
            ("Generator.Uppercase", "Letras maiúsculas (A-Z)"),
            ("Generator.Lowercase", "Letras minúsculas (a-z)"),
            ("Generator.Numbers", "Números (0-9)"),
            ("Generator.Special", "Caracteres especiais (!@#)"),
            ("Generator.Words", "Palavras"),
            ("Generator.Separator", "Separador"),
            ("Generator.Separator.Space", "espaço"),
            ("Generator.Capitalize", "Capitalizar palavras"),
            ("Generator.AddNumber", "Adicionar número"),
            ("Generator.GeneratePassword", "Gerar nova senha"),
            ("Generator.GeneratePassphrase", "Gerar frase-senha"),
            ("Generator.SaveToVault", "Salvar no cofre"),
            ("Generator.Clear", "Limpar"),
            ("Generator.CopyAll", "Copiar todas"),
            ("Generator.PasswordsGenerated", "Senhas geradas ({0})"),
            ("Generator.PassphrasesGenerated", "Frases-senha geradas ({0})"),
            ("Generator.StrengthWeak", "Fraca"),
            ("Generator.StrengthMedium", "Média"),
            ("Generator.StrengthStrong", "Forte"),
            ("Generator.StrengthExcellent", "Excelente"),
            ("Generator.Item.Password", "senha"),
            ("Generator.Item.Passphrase", "frase-senha"),
            ("Generator.GenerateFirst", "Gere uma {0} primeiro"),
            ("Generator.PasswordCopied", "Senha copiada!"),
            ("Generator.PassphraseCopied", "Frase-senha copiada!"),
            ("Generator.PasswordCopiedClearing", "Senha copiada! Será apagada da área de transferência em {0} segundos."),
            ("Generator.PassphraseCopiedClearing", "Frase-senha copiada! Será apagada da área de transferência em {0} segundos."),

            ("Login.SubtitleCreate", "Crie uma senha mestra para proteger o cofre"),
            ("Login.SubtitleUnlock", "Digite sua senha mestra para desbloquear"),
            ("Login.MasterPassword", "Senha mestra"),
            ("Login.ConfirmPassword", "Confirmar senha"),
            ("Login.CreateVault", "Criar cofre"),
            ("Login.Unlock", "Desbloquear"),
            ("Login.WindowsHello", "Desbloquear com Windows Hello"),
            ("Login.EnableWindowsHello", "Ativar Windows Hello"),
            ("Login.WindowsHelloHint", "Use digital, rosto ou PIN para desbloquear mais rápido."),
            ("Login.FirstRunNotice", "Guarde bem esta senha: ela não é enviada nem gravada em nenhum servidor, e não existe forma de recuperar o cofre caso você a esqueça. A próxima tela oferece um backup de emergência em QR code."),
            ("Login.Error.PasswordLength", "A senha deve ter pelo menos 8 caracteres."),
            ("Login.Error.PasswordMismatch", "As senhas não coincidem."),
            ("Login.Error.MasterPasswordRequired", "Digite a senha mestra."),
            ("Login.Error.TooManyAttempts", "Muitas tentativas. Aguarde 5 segundos."),
            ("Login.Error.WrongPassword", "Senha incorreta. Tentativa {0} de 5."),
            ("Login.RestoreFromDatabase", "Restaurar de um banco de dados"),
            ("Login.RestoreTitle", "Restaurar cofre"),
            ("Login.RestoreInstruction", "Digite a senha mestra deste cofre para restaurá-lo a partir do banco de dados:"),
            ("Login.RestoreConfirm", "Restaurar"),

            ("Entry.NewTitle", "Nova senha"),
            ("Entry.EditTitle", "Editar senha"),
            ("Entry.EditTitleWithService", "Editar senha - {0}"),
            ("Entry.ServiceName", "Nome do serviço"),
            ("Entry.UserEmail", "Usuário / E-mail"),
            ("Entry.Password", "Senha"),
            ("Entry.PasswordKeepCurrent", "Senha  (deixe em branco para manter a atual)"),
            ("Entry.PasswordKeepCurrentFormat", "{0}  (deixe em branco para manter a atual)"),
            ("Entry.TotpOptional", "Autenticação em duas etapas (2FA)  (opcional)"),
            ("Entry.TotpRemove", "Autenticação em duas etapas (2FA)  (em branco remove)"),
            ("Entry.TotpLabel", "Código de verificação (2FA)"),
            ("Entry.TotpWatermark", "Cole a chave secreta ou o link otpauth://"),
            ("Entry.TotpExpiresIn", "expira em {0}s"),
            ("Entry.Category", "Categoria"),
            ("Entry.TagsOptional", "Etiquetas  (opcional)"),
            ("Entry.TagsWatermark", "Ex.: trabalho, importante, cliente-x"),
            ("Entry.UrlOptional", "URL  (opcional)"),
            ("Entry.NotesOptional", "Notas  (opcional)"),
            ("Entry.Usage.Created", "Criada em {0}"),
            ("Entry.Usage.Updated", "Editada em {0}"),
            ("Entry.Usage.CopyPasswordLabel", "Senha copiada: {0}"),
            ("Entry.Usage.CopyUserLabel", "Usuário copiado: {0}"),
            ("Entry.Usage.CopyTotpLabel", "TOTP copiado: {0}"),
            ("Entry.Usage.Never", "nunca"),
            ("Entry.CreateRequired", "Preencha os campos obrigatórios (nome, usuário e senha)."),
            ("Entry.EditRequired", "Preencha os campos obrigatórios."),
            ("Entry.TotpInvalid", "A chave de autenticação em duas etapas é inválida. Cole a chave secreta (Base32) ou um link otpauth://."),
            ("Entry.CreateError", "Erro ao criar senha: {0}"),
            ("Entry.UpdateError", "Erro ao atualizar senha: {0}"),
            ("Entry.RecoverCurrentPasswordError", "Não foi possível recuperar a senha atual. Digite uma nova senha."),
            ("Entry.Detail.DiscardChangesTitle", "Descartar alterações?"),
            ("Entry.Detail.DiscardChangesConfirm", "Há alterações não salvas nesta credencial. Se continuar, elas serão descartadas."),
            ("Entry.Detail.ConcurrentChangeTitle", "Alterada em outro lugar"),
            ("Entry.Detail.ConcurrentChangeConfirm", "Esta credencial foi alterada (por sincronização ou outro dispositivo) enquanto você editava. Salvar agora vai sobrescrever essa alteração. Continuar mesmo assim?"),
            ("Entry.HistoryHeader", "Histórico de senhas ({0})"),
            ("Entry.HistoryReplacedOn", "Substituída em {0}"),
            ("Entry.HistoryUse", "Usar"),
            ("Entry.HistoryUseTooltip", "Preencher o campo com esta senha"),
            ("A11y.PreviousPassword", "Senha anterior"),

            ("Entry.RecoveryCodes", "Códigos de recuperação"),
            ("Entry.RecoveryCodesWatermark", "Cole um código por linha"),
            ("Entry.RecoveryCodesAdd", "Adicionar"),
            ("Entry.RecoveryCodeMarkUsed", "Marcar como usado"),
            ("Entry.RecoveryCodeUnmark", "Desmarcar"),
            ("Entry.RecoveryCodeRemove", "Remover"),
            ("Entry.RecoveryCodeRemoveConfirm", "Remover este código de recuperação? Essa ação não pode ser desfeita."),
            ("Entry.RecoveryCodesAddError", "Erro ao adicionar códigos de recuperação: {0}"),
            ("Entry.RecoveryCodeMarkError", "Erro ao atualizar o código de recuperação: {0}"),
            ("Entry.RecoveryCodeRemoveError", "Erro ao remover o código de recuperação: {0}"),
            ("Entry.Attachments", "Anexos"),
            ("Entry.AttachmentsAdd", "Adicionar anexo..."),
            ("Entry.AttachmentDownload", "Baixar"),
            ("Entry.AttachmentRemove", "Remover"),
            ("Entry.AttachmentRemoveConfirm", "Remover o anexo \"{0}\"? Essa ação não pode ser desfeita."),
            ("Entry.AttachmentAddError", "Erro ao adicionar anexo: {0}"),
            ("Entry.AttachmentDownloadError", "Erro ao baixar anexo: {0}"),
            ("Entry.AttachmentRemoveError", "Erro ao remover anexo: {0}"),
            ("A11y.RecoveryCode", "Código de recuperação"),

            ("Entry.Type", "Tipo de credencial"),
            ("CredType.Login", "Login"),
            ("CredType.Cartao", "Cartão"),
            ("CredType.ChaveLicenca", "Chave de licença"),
            ("CredType.WiFi", "Wi-Fi"),
            ("CredType.Servidor", "Servidor"),
            ("CredType.BancoDados", "Banco de dados"),
            ("CredField.CardHolder", "Titular do cartão"),
            ("CredField.CardNumber", "Número do cartão"),
            ("CredField.Product", "Produto / Software"),
            ("CredField.LicenseKey", "Chave de licença"),
            ("CredField.Ssid", "Nome da rede (SSID)"),
            ("CredField.WifiPassword", "Senha da rede"),
            ("CredField.Validade", "Validade"),
            ("CredField.Cvv", "CVV"),
            ("CredField.Bandeira", "Bandeira"),
            ("CredField.Seguranca", "Segurança"),
            ("CredField.Banda", "Banda"),
            ("CredField.Host", "Host"),
            ("CredField.Porta", "Porta"),
            ("CredField.Protocolo", "Protocolo"),
            ("CredField.NomeBanco", "Nome do banco"),
            ("CredField.Motor", "Motor"),

            ("ExportDialog.ExportTitle", "Exportar senhas"),
            ("ExportDialog.ImportTitle", "Importar senhas"),
            ("ExportDialog.ExportPassword", "Senha de exportação"),
            ("ExportDialog.Password", "Senha"),
            ("ExportDialog.InfoExport", "Defina uma senha para proteger o arquivo. Ela será exigida na importação - guarde-a bem, pois sem ela o arquivo não pode ser aberto."),
            ("ExportDialog.OnlyFiltered", "Exportar somente os itens filtrados na lista ({0} de {1})"),
            ("ExportDialog.InfoImport", "Informe a senha definida quando o arquivo foi exportado."),
            ("ExportDialog.PasswordRequired", "Informe a senha."),
            ("ExportDialog.PasswordLength", "A senha deve ter pelo menos 8 caracteres."),
            ("ExportDialog.PasswordMismatch", "As senhas não coincidem."),

            ("Master.ChangeTitle", "Alterar senha mestra"),
            ("Master.KdfUpgradeTitle", "Reforço de segurança"),
            ("Master.CurrentPassword", "Senha mestra atual"),
            ("Master.NewPassword", "Nova senha mestra"),
            ("Master.ConfirmNewPassword", "Confirmar nova senha"),
            ("Master.ErrorCurrentRequired", "Informe a senha mestra atual."),
            ("Master.ErrorNewLength", "A nova senha deve ter pelo menos 8 caracteres."),
            ("Master.ErrorConfirmMismatch", "A confirmação não coincide com a nova senha."),
            ("Master.ChangeError", "Erro ao alterar a senha mestra: {0}"),
            ("Master.ChangedRestart", "Senha mestra alterada com sucesso.\n\nO aplicativo será reiniciado para aplicar a nova senha."),
            ("Master.ItemsDiscardedWarning", "Alguns itens com dado corrompido (histórico, campo extra, código de recuperação ou anexo) não puderam ser recuperados e foram descartados durante a troca."),
            ("Master.OtherDevicesWarning", "Se este cofre está conectado a um banco de dados ou a uma pasta de sincronização compartilhada com outros dispositivos, atualize a senha mestra neles também depois de reiniciar — do contrário, eles vão parar de conseguir ler o que for sincronizado por este dispositivo a partir de agora."),

            ("Biometric.Title", "Windows Hello"),
            ("Biometric.EnableOffer", "Deseja ativar o desbloqueio por Windows Hello neste dispositivo?\n\nA senha mestra continuará funcionando como fallback."),
            ("Biometric.Enabled", "Desbloqueio por Windows Hello ativado neste dispositivo."),
            ("Biometric.Disabled", "Desbloqueio por Windows Hello desativado neste dispositivo."),
            ("Biometric.DisableConfirm", "Desativar o desbloqueio por Windows Hello neste dispositivo?"),
            ("Biometric.DisabledAfterMasterChange", "O desbloqueio por Windows Hello foi desativado e poderá ser reativado após o reinício."),
            ("Biometric.DisabledAfterKdfUpgrade", "O cofre recebeu um reforço de segurança na derivação da chave. O desbloqueio por Windows Hello foi desativado e pode ser reativado agora no menu de configurações."),
            ("Biometric.NotEnabled", "O desbloqueio por Windows Hello não está ativado."),
            ("Biometric.InvalidVaultKey", "A chave do cofre não é válida para ativar o Windows Hello."),
            ("Biometric.InvalidRegistration", "O registro do Windows Hello não corresponde mais a este cofre. Entre com a senha mestra e ative novamente."),
            ("Biometric.EnableError", "Erro ao ativar o Windows Hello: {0}"),
            ("Biometric.UnlockError", "Erro ao desbloquear com Windows Hello: {0}"),
            ("Biometric.UnsupportedPlatform", "Windows Hello está disponível apenas no Windows 10 ou superior."),
            ("Biometric.AvailabilityError", "Não foi possível verificar a disponibilidade do Windows Hello: {0}"),
            ("Biometric.NotConfigured", "Configure um PIN, biometria ou Windows Hello nas configurações do Windows."),
            ("Biometric.RetriesExhausted", "Muitas tentativas de verificação. Tente novamente mais tarde."),
            ("Biometric.Unavailable", "Windows Hello está indisponível no momento."),

            ("Qr.RegenerateTitle", "Regerar QR code"),
            ("Qr.RegenerateInstruction", "Confirme sua senha mestra para gerar um novo QR code de backup."),
            ("Qr.GenerateButton", "Gerar QR code"),
            ("Qr.ErrorMasterRequired", "Digite sua senha mestra."),
            ("Qr.ErrorMasterIncorrect", "Senha mestra incorreta."),
            ("Qr.BackupTitle", "Backup da senha mestra"),
            ("Qr.BackupTitleWithType", "Backup da senha mestra (QR code)"),
            ("Qr.Offer", "Deseja salvar um QR code de backup da sua senha mestra?\n\nATENÇÃO: o QR code contém a versão senha-frase da sua senha mestra. Qualquer pessoa que escaneie a imagem poderá reconstruir a senha e acessar o cofre.\n\nGuarde o arquivo em local seguro e offline (ou impresso) - nunca em nuvem, e-mail ou pastas compartilhadas."),
            ("Qr.SavePickerTitle", "Salvar QR code da senha mestra"),
            ("Qr.SaveSuccess", "QR code salvo com sucesso. Guarde-o em local seguro."),
            ("Qr.SaveError", "Não foi possível salvar o QR code: {0}"),
            ("Qr.CloudFolderWarning", "Essa pasta é sincronizada com o {0}. Salvar o QR code aqui envia a senha mestra (em forma reconstruível) para a nuvem. Deseja continuar mesmo assim?"),
            ("Qr.SheetSubtitle", "Backup da senha mestra"),
            ("Qr.SheetWarning1", "Contém a versão senha-frase da senha mestra."),
            ("Qr.SheetWarning2", "Guarde em local seguro e offline."),

            ("Db.SelectTitle", "Conectar banco de dados"),
            ("Db.SelectExplanation", "Recurso para uso self-hosted ou compartilhado: conecta o cofre a um banco de dados próprio, útil para um servidor pessoal ou para compartilhar acesso com outras pessoas de confiança. Para sincronizar só os seus próprios dispositivos, sem manter um banco de dados, use a Sincronização por pasta compartilhada no menu de configurações."),
            ("Db.ChooseType", "Escolha o tipo de banco de dados para conectar."),
            ("Db.ConnectionTitle", "Conexão"),
            ("Db.ConnectProviderTitle", "Conectar - {0}"),
            ("Db.TestConnection", "Testar conexão"),
            ("Db.DatabaseFile", "Arquivo do banco (.db)"),
            ("Db.Browse", "Procurar..."),
            ("Db.Host", "Host"),
            ("Db.Port", "Porta"),
            ("Db.Database", "Banco de dados"),
            ("Db.User", "Usuário"),
            ("Db.Password", "Senha"),
            ("Db.RequireValidCertificate", "Exigir certificado válido do servidor"),
            ("Db.RequireValidCertificateHelp", "Desligado (padrão): a conexão é sempre cifrada, mas aceita certificado autoassinado — comum em banco local ou na rede interna. Ligue para exigir um certificado validado por uma autoridade confiável, recomendado para banco fora da sua rede."),
            ("Db.SQLitePickerTitle", "Arquivo do banco SQLite"),
            ("Db.ConnectionSuccess", "Conexão bem-sucedida."),
            ("Db.CreateTableTitle", "Criar tabela"),
            ("Db.TableMissing", "A tabela \"{0}\" não existe neste banco.\n\nDeseja criá-la agora?"),
            ("Db.ConnectionCanceledNoTable", "Conexão cancelada: a tabela não existe."),
            ("Db.RestoreTableMissing", "Este banco não tem o cofre esperado — a tabela não existe. Confira os dados de conexão."),
            ("Db.RestoreNoAuthPublished", "Este banco ainda não tem uma senha mestra publicada para restauração. Conecte primeiro, neste banco, um dispositivo que já tenha este cofre desbloqueado — a publicação acontece sozinha na próxima vez que ele conectar."),
            ("Db.RestoreInvalidAuth", "Os parâmetros de derivação de chave guardados neste banco estão fora da faixa aceita. Não é possível restaurar o cofre a partir dele."),
            ("Db.ErrorFileRequired", "Informe o arquivo do banco."),
            ("Db.ErrorFieldsRequired", "Preencha host, banco de dados e usuário."),
            ("Db.ErrorInvalidPort", "Porta inválida."),
            ("Db.ConnectionFailed", "Falha na conexão: {0}"),
            ("Db.CannotConnect", "Não foi possível conectar: {0}"),
            ("Db.Error.ConnectionFailed", "Não foi possível conectar ao banco de dados. Verifique host, porta e credenciais."),
            ("Db.Error.SchemaFailed", "Não foi possível criar ou atualizar a tabela do cofre no banco de dados."),
            ("Db.FeatureUnavailable", "Recurso indisponível nesta sessão."),
            ("Db.ConnectedMessage", "Conectado ao banco de dados — os dados passam a ser espelhados com este banco compartilhado.\n\n{0}"),
            ("Db.ConnectError", "Erro ao conectar: {0}"),

            ("Message.LoadError", "Erro ao carregar: {0}"),
            ("Message.FavoriteError", "Erro ao favoritar: {0}"),
            ("Message.PinError", "Erro ao fixar: {0}"),
            ("Message.DeleteTitle", "Excluir senha"),
            ("Message.MoveToTrash", "A credencial será movida para a lixeira. Você pode restaurá-la ou excluí-la definitivamente por lá."),
            ("Message.DeletePrompt", "Excluir \"{0}\"?\n\n{1}"),
            ("Message.DeleteError", "Erro ao excluir senha: {0}"),
            ("Nav.Trash", "Lixeira"),
            ("Trash.Empty", "A lixeira está vazia."),
            ("Trash.DeletedOn", "Excluída em {0}"),
            ("Trash.Restore", "Restaurar"),
            ("Trash.RestoreError", "Erro ao restaurar: {0}"),
            ("Trash.DeleteForever", "Excluir definitivamente"),
            ("Trash.DeleteForeverConfirm", "Excluir \"{0}\" definitivamente?\n\nEsta ação não pode ser desfeita."),
            ("Trash.DeleteForeverError", "Erro ao excluir definitivamente: {0}"),
            ("Trash.EmptyButton", "Esvaziar lixeira"),
            ("Trash.EmptyConfirmTitle", "Esvaziar lixeira"),
            ("Trash.EmptyConfirm", "Excluir definitivamente todos os itens da lixeira?\n\nEsta ação não pode ser desfeita."),
            ("Trash.EmptyError", "Erro ao esvaziar a lixeira: {0}"),

            ("Vault.ClearTitle", "Limpar cofre"),
            ("Vault.ClearConfirm", "Mover todas as senhas do cofre para a lixeira?\n\nVocê poderá restaurar os itens a partir da lixeira, se precisar."),
            ("Vault.ClearError", "Erro ao limpar o cofre: {0}"),
            ("Vault.DeleteTitle", "Excluir cofre"),
            ("Vault.DeleteReauthInstruction", "Digite sua senha mestra atual para continuar."),
            ("Vault.DeleteReauthButton", "Continuar"),
            ("Vault.DeleteConfirm", "Excluir o cofre permanentemente?\n\nTodas as senhas, a senha mestra, os backups e os anexos serão apagados, e o desbloqueio por Windows Hello será desativado. Esta ação não pode ser desfeita."),
            ("Vault.DeleteError", "Erro ao excluir o cofre: {0}"),
            ("Vault.DeletedRestart", "Cofre excluído. O aplicativo será reiniciado."),
            ("Message.RenameDecryptError", "Não foi possível descriptografar a senha para salvar a alteração."),
            ("Message.RenameError", "Erro ao renomear serviço: {0}"),
            ("Message.AuditTitle", "Auditoria do cofre"),
            ("Message.AuditNoPasswords", "Não há senhas no cofre para auditar."),
            ("Message.AuditSuccess", "Auditoria concluída: nenhuma senha fraca, repetida ou antiga entre {0} senha(s)."),
            ("Message.AuditIncomplete", "{0} senha(s) não puderam ser analisadas por completo."),
            ("Message.AuditFoundHeader", "Encontradas {0} entrada(s) com alerta em {1} senha(s):"),
            ("Message.AuditWeakLine", "- {0} fraca(s)"),
            ("Message.AuditRepeatedLine", "- {0} repetida(s)"),
            ("Message.AuditOldLine", "- {0} antiga(s)"),
            ("Message.AuditUnreadableLine", "- {0} não auditada(s) por falha de leitura"),
            ("Message.AuditMarked", "As entradas afetadas foram marcadas com ⚠ na lista."),
            ("Message.AuditOldDefinition", "Senhas antigas são as sem atualização há {0} dias ou mais."),
            ("Message.AuditError", "Erro ao auditar o cofre: {0}"),

            ("SecurityReport.Title", "Relatório de segurança"),
            ("SecurityReport.ScoreLabel", "Pontuação do cofre"),
            ("SecurityReport.TrendLabel", "Tendência da pontuação"),
            ("SecurityReport.ScoreWeak", "Precisa de atenção"),
            ("SecurityReport.ScoreMedium", "Razoável"),
            ("SecurityReport.ScoreStrong", "Boa"),
            ("SecurityReport.ScoreExcellent", "Excelente"),
            ("SecurityReport.Weak", "Senhas fracas"),
            ("SecurityReport.Repeated", "Senhas repetidas"),
            ("SecurityReport.Old", "Senhas antigas"),
            ("SecurityReport.Compromised", "Senhas comprometidas"),
            ("SecurityReport.NoTotp", "Sem verificação em duas etapas"),
            ("SecurityReport.NoUrl", "Sem URL cadastrada"),
            ("SecurityReport.NoCategory", "Sem categoria definida"),
            ("SecurityReport.CertNotRequired", "A conexão com o banco não exige certificado de servidor válido. O tráfego continua cifrado, mas fica vulnerável a um ataque man-in-the-middle. Ative \"Exigir certificado válido do servidor\" na tela de conexão a banco."),
            ("SecurityReport.RowAutomationName", "{0}: {1}"),
            ("SecurityReport.CheckBreaches", "Verificar vazamentos agora"),
            ("SecurityReport.BreachesNotChecked", "Ainda não verificado nesta sessão"),
            ("SecurityReport.AllGood", "Nenhum problema encontrado. Continue assim!"),
            ("SecurityReport.ClearFilter", "Limpar filtro"),
            ("SecurityReport.FilterActive", "Filtrando por: {0}"),
            ("SecurityReport.BreachCheckError", "Erro ao verificar vazamentos: {0}"),
            ("Message.BreachTitle", "Verificar vazamentos"),
            ("Message.BreachNoPasswords", "Não há senhas no cofre para verificar."),
            ("Message.BreachDoneTitle", "Verificação concluída"),
            ("Message.BreachSuccess", "Boa notícia! Nenhuma das {0} senha(s) verificada(s) foi encontrada em vazamentos conhecidos."),
            ("Message.BreachWarning", "Atenção: {0} de {1} senha(s) aparecem em vazamentos conhecidos. Considere trocá-las (marcadas com ⚠)."),
            ("Message.NetworkErrorTitle", "Erro de rede"),
            ("Message.BreachNetworkError", "Não foi possível verificar os vazamentos.\nVerifique sua conexão com a internet.\n\nDetalhe: {0}"),
            ("Message.ExportEmpty", "O cofre está vazio. Não há nada para exportar."),
            ("Message.ExportSuccess", "{0} senha(s) exportada(s) com sucesso.\n\nGuarde bem a senha de exportação - sem ela o arquivo não pode ser aberto."),
            ("Message.ExportError", "Erro ao exportar: {0}"),
            ("Message.ImportEmpty", "Nenhuma senha encontrada no arquivo."),
            ("Message.ImportSuccess", "{0} senha(s) importada(s) com sucesso."),
            ("Message.ImportIgnored", "{0} ignorada(s) (dados incompletos ou inválidos)."),
            ("Message.ImportDuplicates", "{0} já existia(m) no cofre."),
            ("Message.ImportError", "Erro ao importar: {0}"),
            ("Message.CsvEmpty", "Nenhuma credencial encontrada no arquivo."),
            ("Message.CsvConfirm", "Detectamos um arquivo no formato {0} com {1} credencial(is).\n\nAs senhas serão adicionadas ao cofre (itens já existentes são ignorados). Deseja continuar?"),
            ("Message.CsvIgnored", "{0} ignorada(s) (linha incompleta ou inválida)."),
            ("Message.CsvDuplicates", "{0} já existia(m) no cofre."),
            ("Message.CsvSecurity", "Por segurança, apague o arquivo CSV - ele guarda as senhas em texto aberto."),
            ("Import.Progress", "Importando {0} de {1}…"),
            ("Export.Progress", "Exportando {0} de {1}…"),

            ("Row.FavoriteRemove", "Remover dos favoritos"),
            ("Row.FavoriteAdd", "Adicionar aos favoritos"),
            ("Row.PinEntry", "Fixar no topo"),
            ("Row.UnpinEntry", "Desafixar"),
            ("Row.CopyUser", "Copiar usuário"),
            ("Row.EditService", "Editar serviço"),
            ("Row.RevealPassword", "Revelar senha"),
            ("Row.HidePassword", "Ocultar senha"),
            ("Row.CopyPassword", "Copiar senha"),
            ("Row.EditEntry", "Editar entrada"),
            ("Row.DeleteEntry", "Excluir entrada"),
            ("Row.CopyTotp", "Copiar código 2FA"),
            ("Row.CopyRecoveryCode", "Copiar código de recuperação"),
            ("Row.UserCopied", "Usuário copiado"),
            ("Row.UserCopiedClearing", "Usuário copiado — apagando em {0}s"),
            ("Row.PasswordCopiedClearing", "Senha copiada — apagando em {0}s"),
            ("Row.TotpCopiedClearing", "Código 2FA copiado — apagando em {0}s"),
            ("Row.CategoryTooltip", "Categoria: {0}"),
            ("Row.TagsTooltip", "Etiquetas: {0}\nCategoria: {1}"),
            ("Row.PasswordCompromised", "Senha comprometida - encontrada em {0:N0} vazamento(s). Troque-a!"),
            ("Row.AuditPrefix", "Auditoria: {0}"),
            ("Row.NotFoundInBreaches", " (não encontrada em vazamentos)"),
            ("Row.PasswordWeak", "Senha fraca"),
            ("Row.PasswordMedium", "Senha média"),
            ("Row.PasswordStrong", "Senha forte"),
            ("Row.AuditWeak", "senha fraca"),
            ("Row.AuditRepeatedWithCount", "senha repetida em {0} entradas"),
            ("Row.AuditRepeated", "senha repetida"),
            ("Row.AuditOld", "sem atualização há {0} dias"),
            ("Row.AuditAlert", "alerta"),

            ("Category.Work", "Trabalho"),
            ("Category.Personal", "Pessoal"),
            ("Category.Finance", "Finanças"),
            ("Category.Social", "Social"),
            ("Category.Other", "Outro"),

            ("Access.Title", "Acessibilidade"),
            ("Access.Colorblind", "Daltonismo"),
            ("Access.None", "Nenhum"),
            ("Access.Protanopia", "Protanopia"),
            ("Access.Deuteranopia", "Deuteranopia"),
            ("Access.Tritanopia", "Tritanopia"),
            ("Access.Monochromacy", "Monocromacia"),
            ("Access.HighContrast", "Alto contraste"),
            ("Access.TextSize", "Tamanho do texto"),
            ("Access.TextNormal", "Normal"),
            ("Access.TextLarge", "Grande"),
            ("Access.TextLarger", "Maior"),
            ("Access.ReduceMotion", "Reduzir animações"),
            ("Access.ScreenReader", "Leitor de tela"),
            ("Access.ScreenReaderHelp", "Modo mais descritivo para leitores de tela"),
            ("Access.Minimize", "Minimizar"),
            ("Access.Maximize", "Maximizar"),
            ("Access.Restore", "Restaurar"),
            ("Access.Close", "Fechar janela"),
            ("A11y.PasswordFieldHelp", "Campo protegido. Use revelar senha apenas em local seguro."),
            ("A11y.GeneratedPassword", "Senha gerada"),
            ("A11y.GeneratedPasswordHelp", "O valor não é anunciado automaticamente. Use copiar para enviar à área de transferência."),
            ("A11y.GeneratedReady", "{0} {1}(s) gerada(s). Use copiar para enviar à área de transferência."),
            ("A11y.GeneratedList", "Lista de senhas geradas"),
            ("A11y.CopyGenerated", "Copiar item gerado"),
            ("A11y.CopyAllGenerated", "Copiar todos os itens gerados"),
            ("A11y.Copied", "{0} copiado para a área de transferência."),
            ("A11y.Restored", "{0} restaurado."),
            ("A11y.CopiedWillClear", "{0} copiado. Será apagado da área de transferência em {1} segundos."),
            ("A11y.PasswordVisible", "Senha visível na tela."),
            ("A11y.PasswordHidden", "Senha oculta."),
            ("A11y.PrivacyModeOn", "Modo privacidade ativado. Serviço, usuário e categoria ocultos na lista."),
            ("A11y.PrivacyModeOff", "Modo privacidade desativado."),
            ("A11y.RowHelp", "Use Tab para acessar as ações desta entrada."),
            ("A11y.SortByColumn", "Clique para ordenar por esta coluna."),
            ("A11y.EditServiceHelp", "Pressione Enter para editar o nome do serviço."),
            ("A11y.EditServiceMode", "Editando serviço. Pressione Enter para salvar ou Esc para cancelar."),
            ("A11y.SliderHelp", "Use as setas para ajustar. Home e End vão ao mínimo e máximo."),
            ("A11y.ToggleOn", "Ativado"),
            ("A11y.ToggleOff", "Desativado"),
            ("A11y.VaultStatus", "Status do cofre"),
            ("A11y.ConnectionStatus", "Status da conexão"),
            ("A11y.ResultsList", "Lista de senhas"),
            ("A11y.EmptyList", "Lista vazia"),
            ("A11y.OptionalField", "Campo opcional"),
            ("A11y.TotpPreview", "Prévia do código 2FA"),
            ("A11y.FilterOn", "Filtro ativado"),
            ("A11y.FilterOff", "Filtro desativado"),
            ("A11y.ScreenReaderEnabled", "Leitor de tela ativado."),
            ("A11y.ScreenReaderDisabled", "Leitor de tela desativado."),

            ("Entry.FieldDecryptError", "(não foi possível decifrar este campo)"),
            ("Entry.Error.ServiceRequired", "Nome do serviço não pode ser vazio"),
            ("Entry.Error.UserRequired", "Usuário não pode ser vazio"),
            ("Entry.Error.PasswordRequired", "Senha não pode ser vazia"),
            ("Entry.Error.ServiceTooLong", "Nome do serviço não pode exceder {0} caracteres"),
            ("Entry.Error.UserTooLong", "Usuário não pode exceder {0} caracteres"),
            ("Entry.Error.PasswordTooLong", "Senha não pode exceder {0} caracteres"),
            ("Entry.Error.UrlTooLong", "URL não pode exceder {0} caracteres"),
            ("Entry.Error.NotesTooLong", "Notas não podem exceder {0} caracteres"),
            ("Entry.Error.CustomFieldTooLong", "Campo personalizado não pode exceder {0} caracteres"),
            ("Entry.Error.RecoveryCodeTooLong", "Código de recuperação não pode exceder {0} caracteres"),
            ("Entry.Error.RecoveryCodesTooMany", "Um item não pode ter mais de {0} códigos de recuperação"),
            ("Auth.Error.PasswordRequired", "A senha mestra não pode ser vazia."),
            ("Auth.Error.PasswordTooShort", "A senha mestra deve ter pelo menos {0} caracteres."),
            ("Master.Error.NewPasswordTooShort", "A nova senha mestra deve ter pelo menos {0} caracteres."),
            ("Master.Error.CurrentPasswordWrong", "Senha mestra atual incorreta."),
            ("Export.Error.PasswordTooShort", "A senha de exportação deve ter pelo menos {0} caracteres."),
            ("Export.Error.FileNotFound", "Arquivo de importação não encontrado."),
            ("Export.Error.PasswordRequired", "Informe a senha de exportação."),
            ("Export.Error.InvalidFile", "Arquivo de importação inválido ou corrompido."),
            ("Export.Error.WrongPassword", "Senha de exportação incorreta ou arquivo corrompido."),
            ("Export.Error.InvalidContent", "Conteúdo do arquivo de importação inválido."),
            ("Import.Error.FileNotFound", "Arquivo de importação não encontrado."),
            ("Import.Error.CannotRead", "Não foi possível ler o arquivo de importação."),
            ("Import.Error.EmptyFile", "O arquivo está vazio."),
            ("Import.Error.NoCredentials", "O arquivo não contém credenciais para importar."),
            ("Import.Error.NoPasswordColumn", "Não foi possível identificar a coluna de senha. Verifique se o arquivo tem uma linha de cabeçalho com os nomes das colunas."),
            ("Attachment.Error.NameRequired", "Nome do arquivo não pode ser vazio"),
            ("Attachment.Error.EmptyFile", "Arquivo vazio"),
            ("Attachment.Error.FileTooLarge", "Arquivo maior que o limite de {0} MB por anexo"),
            ("Attachment.Error.MaxPerCredential", "Esta credencial já tem o máximo de {0} anexos"),
            ("Attachment.Error.VaultLimit", "O cofre atingiria o limite de {0} MB em anexos"),
            ("Generator.Error.LengthRange", "O tamanho da senha deve ficar entre 4 e 1000 caracteres."),
            ("Generator.Error.NoCharacterType", "Selecione pelo menos um tipo de caractere."),
            ("Generator.Error.PassphraseWordsRange", "A frase-senha deve ter entre 3 e 12 palavras."),
            ("Generator.Error.SeparatorTooLong", "O separador deve ter no máximo 3 caracteres."),
            ("Generator.Error.NotEnoughWords", "Informe uma lista com pelo menos duas palavras."),
            ("Generator.Error.QuantityRange", "A quantidade deve ficar entre 1 e 50."),
            ("Vault.Error.WrongKeyOrCorrupt", "Não foi possível abrir o cofre: a chave está incorreta ou o arquivo foi corrompido."),
            ("Vault.Error.CorruptData", "O conteúdo do cofre está corrompido."),
            ("Vault.Error.IOFailure", "Não foi possível acessar o arquivo do cofre."),
            ("Vault.Error.BackupFailed", "Não foi possível criar o backup do cofre.")
        });
    }
}
