namespace CofreDeSenhas
{
    internal static partial class Idioma
    {
        private static IReadOnlyDictionary<string, string> CriarEs() => Mesclar(new (string, string)[]
        {
            ("App.Title", "Caja de contraseñas"),
            ("Common.Save", "Guardar"), ("Common.Cancel", "Cancelar"), ("Common.Change", "Cambiar"),
            ("Common.Connect", "Conectar"), ("Common.Export", "Exportar"), ("Common.Import", "Importar"),
            ("Common.Exit", "Salir"), ("Common.Close", "Cerrar"),
            ("Common.Warning", "Aviso"), ("Common.Error", "Error"), ("Common.Success", "Éxito"),
            ("Common.Validation", "Validación"), ("Common.Yes", "Sí"), ("Common.No", "No"),
            ("Common.AllFiles", "Todos los archivos"), ("Common.ExportedVaultFile", "Caja exportada"),
            ("Common.CsvFile", "Archivo CSV"), ("Common.PngImage", "Imagen PNG"),
            ("Common.SQLiteDatabase", "Base SQLite"),
            ("Settings.Tooltip", "Configuración"), ("Settings.SectionSecurity", "SEGURIDAD"),
            ("Settings.ChangeMasterPassword", "Cambiar contraseña maestra..."),
            ("Settings.RegenerateQr", "Regenerar código QR..."), ("Settings.Backup", "Copia de seguridad y restauración..."),
            ("Settings.AutoLock", "Bloqueo automático"),
            ("Settings.Disabled", "Desactivado"), ("Settings.AfterOneMinute", "Después de 1 minuto"),
            ("Settings.AfterMinutes5", "Después de 5 minutos"), ("Settings.AfterMinutes15", "Después de 15 minutos"),
            ("Settings.AfterMinutes30", "Después de 30 minutos"),
            ("Settings.SectionAppearance", "APARIENCIA"), ("Settings.Language", "Idioma"),
            ("Settings.ClipboardClear", "Limpieza del portapapeles"),
            ("Settings.ClipboardClear.After15", "Después de 15 segundos"),
            ("Settings.ClipboardClear.After30", "Después de 30 segundos"),
            ("Settings.ClipboardClear.After60", "Después de 60 segundos"),
            ("Settings.SectionData", "DATOS"),
            ("Settings.ImportCsv", "Importar desde CSV / otro gestor..."),
            ("Settings.ConnectDatabase", "Conectar base de datos..."),
            ("Settings.DisconnectDatabase", "Desconectar base de datos"),
            ("Settings.EnableWindowsHello", "Activar Windows Hello..."),
            ("Settings.DisableWindowsHello", "Desactivar Windows Hello"),
            ("Settings.OnlineIcons", "Iconos en línea de los servicios"),
            ("Settings.OnlineIconsTooltip", "Descarga de internet el icono real de cada servicio. Desactivado, la caja muestra solo iniciales y no accede a la red."),
            ("Settings.TrackUsageHistory", "Registrar historial de uso"),
            ("Settings.TrackUsageHistoryTooltip", "Registra la fecha de la última copia de contraseña, usuario y código TOTP de cada credencial. Desactiva para dejar de registrar nuevas fechas — las ya guardadas siguen visibles."),
            ("Settings.CheckUpdates", "Buscar actualizaciones"),
            ("Settings.CheckUpdatesTooltip", "Consulta las releases de GitHub para avisar cuando haya una versión más nueva. Desactivado por defecto; no se descarga nada automáticamente y no se envía nada más que esta consulta."),
            ("Update.Available", "Nueva versión disponible: {0}"),
            ("Update.Dismiss", "Descartar aviso de actualización"),
            ("Icons.ConsentMessage", "Para mostrar el icono real de cada servicio, la aplicación consulta el servicio de iconos de Google enviando solo el dominio del sitio (por ejemplo, github.com). Ninguna contraseña, usuario u otro dato sale de tu equipo, y los iconos descargados se guardan en caché en el disco para evitar nuevas consultas.\n\n¿Activar la búsqueda de iconos en línea?"),
            ("Theme.Light", "Tema claro"), ("Theme.Dark", "Tema oscuro"),
            ("Privacy.Enable", "Activar modo privacidad"), ("Privacy.Disable", "Desactivar modo privacidad"),
            ("Settings.LockNow", "Bloquear ahora"),
            ("Settings.SectionHelp", "AYUDA"),
            ("Settings.KeyboardShortcuts", "Atajos de teclado..."),
            ("Shortcuts.Title", "Atajos de teclado"),
            ("Shortcuts.Search", "Buscar"),
            ("Shortcuts.NewPassword", "Nueva contraseña"),
            ("Shortcuts.OpenGenerator", "Abrir el generador"),
            ("Shortcuts.LockNow", "Bloquear ahora"),
            ("Shortcuts.PrivacyMode", "Activar/desactivar modo privacidad"),
            ("Shortcuts.CopyUser", "Copiar el usuario de la fila seleccionada"),
            ("Shortcuts.CopyPassword", "Copiar la contraseña de la fila seleccionada"),
            ("Shortcuts.CloseDialog", "Cerrar el diálogo o cancelar"),
            ("Shortcuts.SelectedRowHint", "La \"fila seleccionada\" es la que tiene el foco de teclado; si ninguna lo tiene, los atajos de copia usan la primera fila de la lista."),
            ("Backup.Title", "Copia de seguridad de la caja"),
            ("Backup.Frequency", "Frecuencia de la copia de seguridad automática"),
            ("Backup.Manual", "Solo manual"), ("Backup.Daily", "Diaria"), ("Backup.Weekly", "Semanal"),
            ("Backup.MaxKept", "Cantidad máxima de copias de seguridad mantenidas"),
            ("Backup.Now", "Hacer copia de seguridad ahora"),
            ("Backup.NeverDone", "Aún no se ha hecho ninguna copia de seguridad."),
            ("Backup.LastDone", "Última copia de seguridad: {0}"),
            ("Backup.Available", "Copias de seguridad disponibles"),
            ("Backup.None", "Aún no hay copias de seguridad disponibles."),
            ("Backup.Restore", "Restaurar"),
            ("Backup.RestoreFrom", "Restaurar copia de seguridad de {0}"),
            ("Backup.RestoreTitle", "Restaurar copia de seguridad"),
            ("Backup.RestoreConfirm", "Esto reemplazará todas las contraseñas de la caja por las de la copia de seguridad de {0}. Los cambios hechos después de esa fecha se perderán. ¿Continuar?"),
            ("Backup.RestoreSuccess", "Copia de seguridad restaurada con éxito."),
            ("Backup.RestoreDisabledDbConnected", "Desconecta la base de datos para restaurar una copia de seguridad."),
            ("Backup.Success", "Copia de seguridad creada con éxito."),
            ("Backup.Error", "Error al procesar la copia de seguridad: {0}"),

            ("Settings.Sync", "Sincronización..."),
            ("Sync.Title", "Sincronización entre dispositivos"),
            ("Sync.Explanation", "Sincroniza la caja fuerte con otros dispositivos a través de una carpeta compartida (ej.: Dropbox, OneDrive, Google Drive). Los datos se cifran de extremo a extremo con tu contraseña maestra antes de salir de este dispositivo — el proveedor de la nube nunca ve texto plano."),
            ("Sync.Enable", "Elegir carpeta y activar"),
            ("Sync.Folder", "Carpeta de sincronización"),
            ("Sync.Frequency", "Sincronizar automáticamente"),
            ("Sync.EveryMinutes", "Cada {0} minutos"),
            ("Sync.Now", "Sincronizar ahora"),
            ("Sync.LastDone", "Última sincronización: {0}"),
            ("Sync.NeverDone", "Aún no sincronizado."),
            ("Sync.ChooseFolder", "Elige la carpeta de sincronización"),
            ("Sync.EnableError", "Error al activar la sincronización: {0}"),
            ("Sync.Success", "Sincronización completada con éxito."),
            ("Sync.Error", "Error al sincronizar. Verifica que la carpeta esté accesible."),
            ("Sync.Disable", "Desactivar sincronización"),
            ("Sync.DisableConfirm", "¿Desactivar la sincronización? Los dispositivos dejan de intercambiar datos entre sí, pero nada se elimina."),
            ("Sync.ConfirmMasterTitle", "Confirmar contraseña maestra"),
            ("Sync.ConfirmMasterInstruction", "Escribe la contraseña maestra de esta caja fuerte para activar la sincronización. Usa la misma contraseña maestra en todos los dispositivos que compartan esta carpeta."),
            ("Sync.Confirm", "Confirmar"),
            ("Vault.Header", "Caja de contraseñas"), ("Vault.ImportTooltip", "Importar contraseñas desde un archivo"),
            ("Vault.ExportTooltip", "Exportar contraseñas a un archivo cifrado"),
            ("Vault.NewPassword", "Nueva contraseña"),
            ("Vault.SearchWatermark", "Buscar por servicio, usuario o categoría"),
            ("Vault.BreachTooltip", "Verificar contraseñas filtradas (Have I Been Pwned)"),
            ("Vault.AuditTooltip", "Auditar contraseñas débiles, repetidas o antiguas"),
            ("Vault.SecurityReportTooltip", "Informe de seguridad de la caja"),
            ("Vault.FavoritesOnlyTooltip", "Solo favoritas"),
            ("Vault.TagFilter", "Filtrar por etiqueta"),
            ("Vault.Table.Service", "SERVICIO"), ("Vault.Table.User", "USUARIO"),
            ("Vault.Table.Category", "CATEGORÍA"),
            ("Vault.Table.Actions", "ACCIONES"),
            ("Vault.Table.Strength", "FUERZA"),
            ("Vault.SortTooltip", "Ordenar"),
            ("Nav.Vault", "Caja fuerte"),
            ("Nav.Favorites", "Favoritas"),
            ("Nav.Recent", "Recientes"),
            ("Nav.Categories", "CATEGORÍAS"),
            ("Nav.Toggle", "Alternar navegación"),
            ("Details.Title", "Detalles"),
            ("Details.Close", "Cerrar detalles"),
            ("Details.Save", "Guardar cambios"),
            ("Details.Delete", "Eliminar"),
            ("Details.FullEdit", "Edición completa..."),
            ("Generator.Close", "Cerrar generador"),
            ("Row.CopyUrl", "Copiar URL"),
            ("Footer.AutoLockOff", "Bloqueo automático desactivado"),
            ("Footer.AutoLockCountdown", "{0} min hasta el bloqueo automático"),
            ("Vault.Empty", "No hay contraseñas en la caja.\nHaz clic en \"Nueva contraseña\" para empezar."),
            ("Vault.Filter.All", "Todas"), ("Vault.Counter.ItemSingular", "{0} elemento"),
            ("Vault.Counter.ItemPlural", "{0} elementos"),
            ("Vault.Status.PasswordSingular", "contraseña"), ("Vault.Status.PasswordPlural", "contraseñas"),
            ("Vault.Status.FavoriteSingular", "favorita"), ("Vault.Status.FavoritePlural", "favoritas"),
            ("Vault.Status.AuditOk", "auditoría OK"), ("Vault.Status.WithAlert", "{0} con alerta"),
            ("Vault.Connection.Local", "Caja cifrada"),
            ("Vault.Connection.Connected", "Conectado: {0}"),
            ("Vault.Connection.DatabaseUnavailable", "Base no disponible - usando caja local"),
            ("Generator.Title", "Generador de contraseñas"), ("Generator.Mode", "Modo"),
            ("Generator.Mode.Password", "Contraseña"), ("Generator.Mode.Passphrase", "Frase contraseña"),
            ("Generator.Strength", "Fortaleza"), ("Generator.Quantity", "Cantidad"),
            ("Generator.Length", "Longitud"), ("Generator.Uppercase", "Letras mayúsculas (A-Z)"),
            ("Generator.Lowercase", "Letras minúsculas (a-z)"), ("Generator.Numbers", "Números (0-9)"),
            ("Generator.Special", "Caracteres especiales (!@#)"), ("Generator.Words", "Palabras"),
            ("Generator.Separator", "Separador"), ("Generator.Separator.Space", "espacio"),
            ("Generator.Capitalize", "Capitalizar palabras"), ("Generator.AddNumber", "Agregar número"),
            ("Generator.GeneratePassword", "Generar nueva contraseña"),
            ("Generator.GeneratePassphrase", "Generar frase contraseña"),
            ("Generator.SaveToVault", "Guardar en la caja"), ("Generator.Clear", "Limpiar"),
            ("Generator.CopyAll", "Copiar todas"),
            ("Generator.PasswordsGenerated", "Contraseñas generadas ({0})"),
            ("Generator.PassphrasesGenerated", "Frases contraseña generadas ({0})"),
            ("Generator.StrengthWeak", "Débil"), ("Generator.StrengthMedium", "Media"),
            ("Generator.StrengthStrong", "Fuerte"), ("Generator.StrengthExcellent", "Excelente"),
            ("Generator.Item.Password", "contraseña"), ("Generator.Item.Passphrase", "frase contraseña"),
            ("Generator.GenerateFirst", "Genera una {0} primero"),
            ("Generator.PasswordCopied", "¡Contraseña copiada!"),
            ("Generator.PassphraseCopied", "¡Frase contraseña copiada!"),
            ("Generator.PasswordCopiedClearing", "¡Contraseña copiada! Se borrará del portapapeles en {0} segundos."),
            ("Generator.PassphraseCopiedClearing", "¡Frase contraseña copiada! Se borrará del portapapeles en {0} segundos."),
            ("Login.SubtitleCreate", "Crea una contraseña maestra para proteger la caja"),
            ("Login.SubtitleUnlock", "Escribe tu contraseña maestra para desbloquear"),
            ("Login.MasterPassword", "Contraseña maestra"), ("Login.ConfirmPassword", "Confirmar contraseña"),
            ("Login.CreateVault", "Crear caja"), ("Login.Unlock", "Desbloquear"),
            ("Login.WindowsHello", "Desbloquear con Windows Hello"),
            ("Login.EnableWindowsHello", "Activar Windows Hello"),
            ("Login.WindowsHelloHint", "Usa huella, rostro o PIN para desbloquear más rápido."),
            ("Login.Error.PasswordLength", "La contraseña debe tener al menos 8 caracteres."),
            ("Login.Error.PasswordMismatch", "Las contraseñas no coinciden."),
            ("Login.Error.MasterPasswordRequired", "Escribe la contraseña maestra."),
            ("Login.Error.TooManyAttempts", "Demasiados intentos. Espera 5 segundos."),
            ("Login.Error.WrongPassword", "Contraseña incorrecta. Intento {0} de 5."),
            ("Entry.NewTitle", "Nueva contraseña"), ("Entry.EditTitle", "Editar contraseña"),
            ("Entry.EditTitleWithService", "Editar contraseña - {0}"),
            ("Entry.ServiceName", "Nombre del servicio"), ("Entry.UserEmail", "Usuario / Correo"),
            ("Entry.Password", "Contraseña"),
            ("Entry.PasswordKeepCurrent", "Contraseña  (deja en blanco para mantener la actual)"),
            ("Entry.PasswordKeepCurrentFormat", "{0}  (deja en blanco para mantener la actual)"),
            ("Entry.TotpOptional", "Autenticación de dos factores (2FA)  (opcional)"),
            ("Entry.TotpRemove", "Autenticación de dos factores (2FA)  (en blanco elimina)"),
            ("Entry.TotpLabel", "Código de verificación (2FA)"),
            ("Entry.TotpWatermark", "Pega la clave secreta o el enlace otpauth://"),
            ("Entry.TotpExpiresIn", "expira en {0}s"), ("Entry.Category", "Categoría"),
            ("Entry.TagsOptional", "Etiquetas  (opcional)"),
            ("Entry.TagsWatermark", "Ej.: trabajo, importante, cliente-x"),
            ("Entry.UrlOptional", "URL  (opcional)"), ("Entry.NotesOptional", "Notas  (opcional)"),
            ("Entry.Usage.Created", "Creada el {0}"), ("Entry.Usage.Updated", "Editada el {0}"),
            ("Entry.Usage.CopyPasswordLabel", "Contraseña copiada: {0}"), ("Entry.Usage.CopyUserLabel", "Usuario copiado: {0}"),
            ("Entry.Usage.CopyTotpLabel", "TOTP copiado: {0}"), ("Entry.Usage.Never", "nunca"),
            ("Entry.CreateRequired", "Completa los campos obligatorios (nombre, usuario y contraseña)."),
            ("Entry.EditRequired", "Completa los campos obligatorios."),
            ("Entry.TotpInvalid", "La clave de autenticación de dos factores no es válida. Pega la clave secreta (Base32) o un enlace otpauth://."),
            ("Entry.CreateError", "Error al crear la contraseña: {0}"),
            ("Entry.UpdateError", "Error al actualizar la contraseña: {0}"),
            ("Entry.RecoverCurrentPasswordError", "No se pudo recuperar la contraseña actual. Escribe una nueva contraseña."),
            ("Entry.HistoryHeader", "Historial de contraseñas ({0})"),
            ("Entry.HistoryReplacedOn", "Reemplazada el {0}"),
            ("Entry.HistoryUse", "Usar"),
            ("Entry.HistoryUseTooltip", "Rellenar el campo con esta contraseña"),
            ("A11y.PreviousPassword", "Contraseña anterior"),

            ("Entry.RecoveryCodes", "Códigos de recuperación"),
            ("Entry.RecoveryCodesWatermark", "Pega un código por línea"),
            ("Entry.RecoveryCodesAdd", "Agregar"),
            ("Entry.RecoveryCodeMarkUsed", "Marcar como usado"),
            ("Entry.RecoveryCodeUnmark", "Desmarcar"),
            ("Entry.RecoveryCodeRemove", "Quitar"),
            ("Entry.RecoveryCodeRemoveConfirm", "¿Quitar este código de recuperación? Esta acción no se puede deshacer."),
            ("Entry.RecoveryCodesAddError", "Error al agregar códigos de recuperación: {0}"),
            ("Entry.RecoveryCodeMarkError", "Error al actualizar el código de recuperación: {0}"),
            ("Entry.RecoveryCodeRemoveError", "Error al quitar el código de recuperación: {0}"),
            ("Entry.Attachments", "Archivos adjuntos"),
            ("Entry.AttachmentsAdd", "Agregar adjunto..."),
            ("Entry.AttachmentDownload", "Descargar"),
            ("Entry.AttachmentRemove", "Quitar"),
            ("Entry.AttachmentRemoveConfirm", "¿Quitar el adjunto \"{0}\"? Esta acción no se puede deshacer."),
            ("Entry.AttachmentAddError", "Error al agregar el adjunto: {0}"),
            ("Entry.AttachmentDownloadError", "Error al descargar el adjunto: {0}"),
            ("A11y.RecoveryCode", "Código de recuperación"),

            ("Entry.Type", "Tipo de credencial"),
            ("CredType.Login", "Inicio de sesión"),
            ("CredType.Cartao", "Tarjeta"),
            ("CredType.ChaveLicenca", "Clave de licencia"),
            ("CredType.WiFi", "Wi-Fi"),
            ("CredType.Servidor", "Servidor"),
            ("CredType.BancoDados", "Base de datos"),
            ("CredType.DocumentoSeguro", "Documento seguro"),
            ("CredField.CardHolder", "Titular de la tarjeta"),
            ("CredField.CardNumber", "Número de la tarjeta"),
            ("CredField.Product", "Producto / Software"),
            ("CredField.LicenseKey", "Clave de licencia"),
            ("CredField.Ssid", "Nombre de la red (SSID)"),
            ("CredField.WifiPassword", "Contraseña de la red"),
            ("CredField.DocTitle", "Título del documento"),
            ("CredField.DocContent", "Contenido sensible"),
            ("CredField.Validade", "Fecha de vencimiento"),
            ("CredField.Cvv", "CVV"),
            ("CredField.Bandeira", "Marca de la tarjeta"),
            ("CredField.Seguranca", "Seguridad"),
            ("CredField.Banda", "Banda"),
            ("CredField.Host", "Host"),
            ("CredField.Porta", "Puerto"),
            ("CredField.Protocolo", "Protocolo"),
            ("CredField.NomeBanco", "Nombre de la base de datos"),
            ("CredField.Motor", "Motor"),
            ("ExportDialog.ExportTitle", "Exportar contraseñas"),
            ("ExportDialog.ImportTitle", "Importar contraseñas"),
            ("ExportDialog.ExportPassword", "Contraseña de exportación"),
            ("ExportDialog.Password", "Contraseña"),
            ("ExportDialog.InfoExport", "Define una contraseña para proteger el archivo. Se exigirá al importar - guárdala bien, porque sin ella el archivo no se puede abrir."),
            ("ExportDialog.InfoImport", "Escribe la contraseña definida cuando se exportó el archivo."),
            ("ExportDialog.PasswordRequired", "Escribe la contraseña."),
            ("ExportDialog.PasswordLength", "La contraseña debe tener al menos 8 caracteres."),
            ("ExportDialog.PasswordMismatch", "Las contraseñas no coinciden."),
            ("Master.ChangeTitle", "Cambiar contraseña maestra"),
            ("Master.CurrentPassword", "Contraseña maestra actual"),
            ("Master.NewPassword", "Nueva contraseña maestra"),
            ("Master.ConfirmNewPassword", "Confirmar nueva contraseña"),
            ("Master.ErrorCurrentRequired", "Informa la contraseña maestra actual."),
            ("Master.ErrorNewLength", "La nueva contraseña debe tener al menos 8 caracteres."),
            ("Master.ErrorConfirmMismatch", "La confirmación no coincide con la nueva contraseña."),
            ("Master.ChangeError", "Error al cambiar la contraseña maestra: {0}"),
            ("Master.ChangedRestart", "Contraseña maestra cambiada correctamente.\n\nLa aplicación se reiniciará para aplicar la nueva contraseña."),
            ("Biometric.Title", "Windows Hello"),
            ("Biometric.EnableOffer", "¿Quieres activar el desbloqueo con Windows Hello en este dispositivo?\n\nLa contraseña maestra seguirá funcionando como alternativa."),
            ("Biometric.Enabled", "El desbloqueo con Windows Hello está activado en este dispositivo."),
            ("Biometric.Disabled", "El desbloqueo con Windows Hello está desactivado en este dispositivo."),
            ("Biometric.DisableConfirm", "¿Desactivar el desbloqueo con Windows Hello en este dispositivo?"),
            ("Biometric.DisabledAfterMasterChange", "El desbloqueo con Windows Hello se desactivó y podrás activarlo de nuevo después del reinicio."),
            ("Biometric.DisabledAfterKdfUpgrade", "Tu caja recibió una mejora de seguridad en la derivación de la clave. El desbloqueo con Windows Hello se desactivó y puedes reactivarlo ahora desde el menú de configuración."),
            ("Biometric.NotEnabled", "El desbloqueo con Windows Hello no está activado."),
            ("Biometric.InvalidVaultKey", "La clave de la caja no es válida para activar Windows Hello."),
            ("Biometric.InvalidRegistration", "El registro de Windows Hello ya no corresponde a esta caja. Entra con la contraseña maestra y actívalo de nuevo."),
            ("Biometric.EnableError", "Error al activar Windows Hello: {0}"),
            ("Biometric.UnlockError", "Error al desbloquear con Windows Hello: {0}"),
            ("Biometric.UnsupportedPlatform", "Windows Hello solo está disponible en Windows 10 o posterior."),
            ("Biometric.AvailabilityError", "No se pudo comprobar la disponibilidad de Windows Hello: {0}"),
            ("Biometric.NotConfigured", "Configura un PIN, biometría o Windows Hello en la configuración de Windows."),
            ("Biometric.RetriesExhausted", "Demasiados intentos de verificación. Inténtalo más tarde."),
            ("Biometric.Unavailable", "Windows Hello no está disponible en este momento."),
            ("Qr.RegenerateTitle", "Regenerar código QR"),
            ("Qr.RegenerateInstruction", "Confirma tu contraseña maestra para generar un nuevo código QR de respaldo."),
            ("Qr.GenerateButton", "Generar código QR"),
            ("Qr.ErrorMasterRequired", "Escribe tu contraseña maestra."),
            ("Qr.ErrorMasterIncorrect", "Contraseña maestra incorrecta."),
            ("Qr.BackupTitle", "Respaldo de la contraseña maestra"),
            ("Qr.BackupTitleWithType", "Respaldo de la contraseña maestra (código QR)"),
            ("Qr.Offer", "¿Quieres guardar un código QR de respaldo de tu contraseña maestra?\n\nATENCIÓN: el código QR contiene la versión frase contraseña de tu contraseña maestra. Cualquiera que escanee la imagen podrá reconstruir la contraseña y acceder a la caja.\n\nGuarda el archivo en un lugar seguro y sin conexión (o impreso) - nunca en la nube, correo o carpetas compartidas."),
            ("Qr.SavePickerTitle", "Guardar código QR de la contraseña maestra"),
            ("Qr.SaveSuccess", "Código QR guardado correctamente. Guárdalo en un lugar seguro."),
            ("Qr.SaveError", "No se pudo guardar el código QR: {0}"),
            ("Qr.SheetSubtitle", "Respaldo de la contraseña maestra"),
            ("Qr.SheetWarning1", "Contiene la versión frase contraseña de la contraseña maestra."),
            ("Qr.SheetWarning2", "Guárdalo en un lugar seguro y sin conexión."),
            ("Db.SelectTitle", "Conectar base de datos"), ("Db.ChooseType", "Elige el tipo de base de datos para conectar."),
            ("Db.ConnectionTitle", "Conexión"), ("Db.ConnectProviderTitle", "Conectar - {0}"),
            ("Db.TestConnection", "Probar conexión"), ("Db.DatabaseFile", "Archivo de base (.db)"),
            ("Db.Browse", "Buscar..."), ("Db.Host", "Host"), ("Db.Port", "Puerto"),
            ("Db.Database", "Base de datos"), ("Db.User", "Usuario"), ("Db.Password", "Contraseña"),
            ("Db.SQLitePickerTitle", "Archivo de base SQLite"),
            ("Db.ConnectionSuccess", "Conexión exitosa."),
            ("Db.CreateTableTitle", "Crear tabla"),
            ("Db.TableMissing", "La tabla \"{0}\" no existe en esta base.\n\n¿Deseas crearla ahora?"),
            ("Db.ConnectionCanceledNoTable", "Conexión cancelada: la tabla no existe."),
            ("Db.ErrorFileRequired", "Informa el archivo de la base."),
            ("Db.ErrorFieldsRequired", "Completa host, base de datos y usuario."),
            ("Db.ErrorInvalidPort", "Puerto no válido."),
            ("Db.ConnectionFailed", "Fallo en la conexión: {0}"),
            ("Db.CannotConnect", "No se pudo conectar: {0}"),
            ("Db.FeatureUnavailable", "Recurso no disponible en esta sesión."),
            ("Db.ConnectedMessage", "Conectado a la base de datos y sincronizado con la caja local.\n\n{0}"),
            ("Db.ConnectError", "Error al conectar: {0}"),
            ("Message.LoadError", "Error al cargar: {0}"),
            ("Message.FavoriteError", "Error al marcar favorito: {0}"),
            ("Message.PinError", "Error al fijar: {0}"),
            ("Message.DeleteTitle", "Eliminar contraseña"),
            ("Message.MoveToTrash", "La credencial se moverá a la papelera. Puedes restaurarla o eliminarla definitivamente desde allí."),
            ("Message.DeletePrompt", "¿Eliminar \"{0}\"?\n\n{1}"),
            ("Message.DeleteError", "Error al eliminar contraseña: {0}"),
            ("Nav.Trash", "Papelera"),
            ("Trash.Empty", "La papelera está vacía."),
            ("Trash.DeletedOn", "Eliminada el {0}"),
            ("Trash.Restore", "Restaurar"),
            ("Trash.RestoreError", "Error al restaurar: {0}"),
            ("Trash.DeleteForever", "Eliminar definitivamente"),
            ("Trash.DeleteForeverConfirm", "¿Eliminar \"{0}\" definitivamente?\n\nEsta acción no se puede deshacer."),
            ("Trash.DeleteForeverError", "Error al eliminar definitivamente: {0}"),
            ("Trash.EmptyButton", "Vaciar papelera"),
            ("Trash.EmptyConfirmTitle", "Vaciar papelera"),
            ("Trash.EmptyConfirm", "¿Eliminar definitivamente todos los elementos de la papelera?\n\nEsta acción no se puede deshacer."),
            ("Trash.EmptyError", "Error al vaciar la papelera: {0}"),
            ("Message.RenameDecryptError", "No se pudo descifrar la contraseña para guardar el cambio."),
            ("Message.RenameError", "Error al renombrar el servicio: {0}"),
            ("Message.AuditTitle", "Auditoría de la caja"),
            ("Message.AuditNoPasswords", "No hay contraseñas en la caja para auditar."),
            ("Message.AuditSuccess", "Auditoría concluida: ninguna contraseña débil, repetida o antigua entre {0} contraseña(s)."),
            ("Message.AuditIncomplete", "{0} contraseña(s) no pudieron analizarse por completo."),
            ("Message.AuditFoundHeader", "Se encontraron {0} entrada(s) con alerta en {1} contraseña(s):"),
            ("Message.AuditWeakLine", "- {0} débil(es)"),
            ("Message.AuditRepeatedLine", "- {0} repetida(s)"),
            ("Message.AuditOldLine", "- {0} antigua(s)"),
            ("Message.AuditUnreadableLine", "- {0} no auditada(s) por error de lectura"),
            ("Message.AuditMarked", "Las entradas afectadas se marcaron con ⚠ en la lista."),
            ("Message.AuditOldDefinition", "Las contraseñas antiguas son las no actualizadas hace {0} días o más."),
            ("Message.AuditError", "Error al auditar la caja: {0}"),

            ("SecurityReport.Title", "Informe de seguridad"),
            ("SecurityReport.ScoreLabel", "Puntuación de la caja"),
            ("SecurityReport.ScoreWeak", "Necesita atención"),
            ("SecurityReport.ScoreMedium", "Aceptable"),
            ("SecurityReport.ScoreStrong", "Buena"),
            ("SecurityReport.ScoreExcellent", "Excelente"),
            ("SecurityReport.Weak", "Contraseñas débiles"),
            ("SecurityReport.Repeated", "Contraseñas repetidas"),
            ("SecurityReport.Old", "Contraseñas antiguas"),
            ("SecurityReport.Compromised", "Contraseñas comprometidas"),
            ("SecurityReport.NoTotp", "Sin verificación en dos pasos"),
            ("SecurityReport.NoUrl", "Sin URL guardada"),
            ("SecurityReport.NoCategory", "Sin categoría definida"),
            ("SecurityReport.RowAutomationName", "{0}: {1}"),
            ("SecurityReport.CheckBreaches", "Verificar filtraciones ahora"),
            ("SecurityReport.BreachesNotChecked", "Aún no verificado en esta sesión"),
            ("SecurityReport.AllGood", "No se encontraron problemas. ¡Sigue así!"),
            ("SecurityReport.ClearFilter", "Quitar filtro"),
            ("SecurityReport.FilterActive", "Filtrando por: {0}"),
            ("SecurityReport.BreachCheckError", "Error al verificar filtraciones: {0}"),
            ("Message.BreachTitle", "Verificar filtraciones"),
            ("Message.BreachNoPasswords", "No hay contraseñas en la caja para verificar."),
            ("Message.BreachDoneTitle", "Verificación concluida"),
            ("Message.BreachSuccess", "¡Buenas noticias! Ninguna de las {0} contraseña(s) verificadas se encontró en filtraciones conocidas."),
            ("Message.BreachWarning", "Atención: {0} de {1} contraseña(s) aparecen en filtraciones conocidas. Considera cambiarlas (marcadas con ⚠)."),
            ("Message.NetworkErrorTitle", "Error de red"),
            ("Message.BreachNetworkError", "No se pudieron verificar las filtraciones.\nComprueba tu conexión a internet.\n\nDetalle: {0}"),
            ("Message.ExportEmpty", "La caja está vacía. No hay nada que exportar."),
            ("Message.ExportSuccess", "{0} contraseña(s) exportada(s) correctamente.\n\nGuarda bien la contraseña de exportación - sin ella el archivo no se puede abrir."),
            ("Message.ExportError", "Error al exportar: {0}"),
            ("Message.ImportEmpty", "No se encontraron contraseñas en el archivo."),
            ("Message.ImportSuccess", "{0} contraseña(s) importada(s) correctamente."),
            ("Message.ImportIgnored", "{0} ignorada(s) (ya existían o no eran válidas)."),
            ("Message.ImportError", "Error al importar: {0}"),
            ("Message.CsvEmpty", "No se encontraron credenciales en el archivo."),
            ("Message.CsvConfirm", "Detectamos un archivo en formato {0} con {1} credencial(es).\n\nLas contraseñas se añadirán a la caja (los elementos existentes se ignoran). ¿Deseas continuar?"),
            ("Message.CsvIgnored", "{0} ignorada(s) (ya existían o estaban incompletas)."),
            ("Message.CsvSecurity", "Por seguridad, borra el archivo CSV - guarda las contraseñas en texto abierto."),
            ("Row.FavoriteRemove", "Quitar de favoritos"), ("Row.FavoriteAdd", "Agregar a favoritos"),
            ("Row.PinEntry", "Fijar arriba"), ("Row.UnpinEntry", "Desfijar"),
            ("Row.CopyUser", "Copiar usuario"), ("Row.EditService", "Editar servicio"),
            ("Row.RevealPassword", "Revelar contraseña"), ("Row.HidePassword", "Ocultar contraseña"),
            ("Row.CopyPassword", "Copiar contraseña"), ("Row.EditEntry", "Editar entrada"),
            ("Row.DeleteEntry", "Eliminar entrada"), ("Row.CopyTotp", "Copiar código 2FA"),
            ("Row.CopyRecoveryCode", "Copiar código de recuperación"),
            ("Row.UserCopied", "Usuario copiado"),
            ("Row.PasswordCopiedClearing", "Contraseña copiada — borrando en {0}s"),
            ("Row.CategoryTooltip", "Categoría: {0}"), ("Row.TagsTooltip", "Etiquetas: {0}\nCategoría: {1}"),
            ("Row.PasswordCompromised", "Contraseña comprometida - encontrada en {0:N0} filtración(es). ¡Cámbiala!"),
            ("Row.AuditPrefix", "Auditoría: {0}"),
            ("Row.NotFoundInBreaches", " (no encontrada en filtraciones)"),
            ("Row.PasswordWeak", "Contraseña débil"), ("Row.PasswordMedium", "Contraseña media"),
            ("Row.PasswordStrong", "Contraseña fuerte"), ("Row.AuditWeak", "contraseña débil"),
            ("Row.AuditRepeatedWithCount", "contraseña repetida en {0} entradas"),
            ("Row.AuditRepeated", "contraseña repetida"),
            ("Row.AuditOld", "sin actualizar hace {0} días"), ("Row.AuditAlert", "alerta"),
            ("Category.Work", "Trabajo"), ("Category.Personal", "Personal"),
            ("Category.Finance", "Finanzas"), ("Category.Social", "Social"), ("Category.Other", "Otro"),
            ("Access.Title", "Accesibilidad"), ("Access.Colorblind", "Daltonismo"), ("Access.None", "Ninguno"),
            ("Access.Protanopia", "Protanopía"), ("Access.Deuteranopia", "Deuteranopía"), ("Access.Tritanopia", "Tritanopía"),
            ("Access.Monochromacy", "Monocromatismo"),
            ("Access.HighContrast", "Alto contraste"), ("Access.TextSize", "Tamaño del texto"),
            ("Access.TextNormal", "Normal"), ("Access.TextLarge", "Grande"), ("Access.TextLarger", "Mayor"),
            ("Access.ReduceMotion", "Reducir animaciones"), ("Access.ScreenReader", "Lector de pantalla"),
            ("Access.ScreenReaderHelp", "Modo más descriptivo para lectores de pantalla"), ("Access.Minimize", "Minimizar"),
            ("Access.Maximize", "Maximizar"), ("Access.Close", "Cerrar ventana")
        });
    }
}
