namespace CofreDeSenhas
{
    internal static partial class Idioma
    {
        private static IReadOnlyDictionary<string, string> CriarIt() => Mesclar(new (string, string)[]
        {
            ("App.Title", "Cassaforte password"),
            ("Common.Save", "Salva"), ("Common.Cancel", "Annulla"), ("Common.Change", "Cambia"),
            ("Common.Connect", "Connetti"), ("Common.Export", "Esporta"), ("Common.Import", "Importa"),
            ("Common.Exit", "Esci"), ("Common.Close", "Chiudi"),
            ("Common.Warning", "Avviso"), ("Common.Error", "Errore"), ("Common.Success", "Successo"),
            ("Common.Validation", "Validazione"), ("Common.Yes", "Sì"), ("Common.No", "No"),
            ("Common.AllFiles", "Tutti i file"), ("Common.ExportedVaultFile", "Cassaforte esportata"),
            ("Common.CsvFile", "File CSV"), ("Common.PngImage", "Immagine PNG"),
            ("Common.SQLiteDatabase", "Database SQLite"),
            ("Settings.Tooltip", "Impostazioni"), ("Settings.SectionSecurity", "SICUREZZA"),
            ("Settings.ChangeMasterPassword", "Cambia password principale..."),
            ("Settings.RegenerateQr", "Rigenera codice QR..."), ("Settings.Backup", "Backup e ripristino..."),
            ("Settings.AutoLock", "Blocco automatico"),
            ("Settings.Disabled", "Disattivato"), ("Settings.AfterOneMinute", "Dopo 1 minuto"),
            ("Settings.AfterMinutes5", "Dopo 5 minuti"), ("Settings.AfterMinutes15", "Dopo 15 minuti"),
            ("Settings.AfterMinutes30", "Dopo 30 minuti"),
            ("Settings.SectionAppearance", "ASPETTO"), ("Settings.Language", "Lingua"),
            ("Settings.ClipboardClear", "Pulizia degli appunti"),
            ("Settings.ClipboardClear.After15", "Dopo 15 secondi"),
            ("Settings.ClipboardClear.After30", "Dopo 30 secondi"),
            ("Settings.ClipboardClear.After60", "Dopo 60 secondi"),
            ("Settings.SectionData", "DATI"),
            ("Settings.ImportCsv", "Importa da CSV / altro gestore..."),
            ("Settings.ConnectDatabase", "Connetti database..."),
            ("Settings.ConnectDatabaseTooltip", "Funzione self-hosted/condivisa — per sincronizzare solo i tuoi dispositivi, usa la Sincronizzazione tramite cartella."),
            ("Settings.DisconnectDatabase", "Disconnetti database"),
            ("Settings.EnableWindowsHello", "Attiva Windows Hello..."),
            ("Settings.DisableWindowsHello", "Disattiva Windows Hello"),
            ("Settings.OnlineIcons", "Icone online dei servizi"),
            ("Settings.OnlineIconsTooltip", "Scarica da internet l'icona reale di ogni servizio. Disattivato, la cassaforte mostra solo le iniziali e non accede mai alla rete."),
            ("Settings.TrackUsageHistory", "Registra cronologia di utilizzo"),
            ("Settings.TrackUsageHistoryTooltip", "Registra la data dell'ultima copia di password, nome utente e codice TOTP di ogni credenziale. Disattiva per smettere di registrare nuove date — quelle già salvate restano visibili."),
            ("Settings.CheckUpdates", "Verifica aggiornamenti"),
            ("Settings.CheckUpdatesTooltip", "Controlla le release di GitHub per segnalare una versione più recente. Disattivato per impostazione predefinita; non viene scaricato nulla automaticamente e non viene inviato nulla oltre a questa verifica."),
            ("Update.Available", "Nuova versione disponibile: {0}"),
            ("Update.Dismiss", "Ignora avviso di aggiornamento"),
            ("Icons.ConsentMessage", "Per mostrare l'icona reale di ogni servizio, l'app interroga il servizio di icone di Google inviando solo il dominio del sito (ad esempio, github.com). Nessuna password, nome utente o altro dato lascia il tuo computer, e le icone scaricate vengono salvate nella cache su disco per evitare nuove richieste.\n\nAttivare il recupero delle icone online?"),
            ("Theme.Light", "Tema chiaro"), ("Theme.Dark", "Tema scuro"),
            ("Privacy.Enable", "Attiva modalità privacy"), ("Privacy.Disable", "Disattiva modalità privacy"),
            ("Settings.LockNow", "Blocca ora"),
            ("Settings.SectionHelp", "AIUTO"),
            ("Settings.KeyboardShortcuts", "Scorciatoie da tastiera..."),
            ("Shortcuts.Title", "Scorciatoie da tastiera"),
            ("Shortcuts.Search", "Cerca"),
            ("Shortcuts.NewPassword", "Nuova password"),
            ("Shortcuts.OpenGenerator", "Apri il generatore"),
            ("Shortcuts.LockNow", "Blocca ora"),
            ("Shortcuts.PrivacyMode", "Attiva/disattiva modalità privacy"),
            ("Shortcuts.CopyUser", "Copia l'utente della riga selezionata"),
            ("Shortcuts.CopyPassword", "Copia la password della riga selezionata"),
            ("Shortcuts.CloseDialog", "Chiudi la finestra o annulla"),
            ("Shortcuts.SelectedRowHint", "La \"riga selezionata\" è quella con il focus da tastiera; se nessuna è selezionata, le scorciatoie di copia usano la prima riga dell'elenco."),
            ("Backup.Title", "Backup della cassaforte"),
            ("Backup.Frequency", "Frequenza del backup automatico"),
            ("Backup.Manual", "Solo manuale"), ("Backup.Daily", "Giornaliero"), ("Backup.Weekly", "Settimanale"),
            ("Backup.MaxKept", "Numero massimo di backup conservati"),
            ("Backup.Now", "Esegui backup ora"),
            ("Backup.NeverDone", "Nessun backup ancora eseguito."),
            ("Backup.LastDone", "Ultimo backup: {0}"),
            ("Backup.Available", "Backup disponibili"),
            ("Backup.None", "Nessun backup ancora disponibile."),
            ("Backup.Restore", "Ripristina"),
            ("Backup.RestoreFrom", "Ripristina il backup del {0}"),
            ("Backup.RestoreTitle", "Ripristina backup"),
            ("Backup.RestoreConfirm", "Questo sostituirà tutte le password della cassaforte con quelle del backup del {0}. Le modifiche fatte dopo quella data andranno perse. Continuare?"),
            ("Backup.RestoreSuccess", "Backup ripristinato con successo."),
            ("Backup.RestoreDisabledDbConnected", "Disconnetti il database per ripristinare un backup."),
            ("Backup.Success", "Backup creato con successo."),
            ("Backup.Error", "Errore durante l'elaborazione del backup: {0}"),

            ("Settings.Sync", "Sincronizzazione..."),
            ("Sync.Title", "Sincronizzazione tra dispositivi"),
            ("Sync.Explanation", "Sincronizza la cassaforte con altri dispositivi tramite una cartella condivisa (es.: Dropbox, OneDrive, Google Drive). I dati sono cifrati end-to-end con la password principale prima di lasciare questo dispositivo — il provider cloud non vede mai il testo in chiaro."),
            ("Sync.Enable", "Scegli cartella e attiva"),
            ("Sync.Folder", "Cartella di sincronizzazione"),
            ("Sync.Frequency", "Sincronizza automaticamente"),
            ("Sync.EveryMinutes", "Ogni {0} minuti"),
            ("Sync.Now", "Sincronizza ora"),
            ("Sync.LastDone", "Ultima sincronizzazione: {0}"),
            ("Sync.NeverDone", "Non ancora sincronizzato."),
            ("Sync.ChooseFolder", "Scegli la cartella di sincronizzazione"),
            ("Sync.EnableError", "Errore durante l'attivazione della sincronizzazione: {0}"),
            ("Sync.Success", "Sincronizzazione completata con successo."),
            ("Sync.Error", "Errore di sincronizzazione. Verifica che la cartella sia accessibile."),
            ("Sync.Disable", "Disattiva sincronizzazione"),
            ("Sync.DisableConfirm", "Disattivare la sincronizzazione? I dispositivi smettono di scambiare dati tra loro, ma nulla viene eliminato."),
            ("Sync.ConfirmMasterTitle", "Conferma password principale"),
            ("Sync.ConfirmMasterInstruction", "Inserisci la password principale di questa cassaforte per attivare la sincronizzazione. Usa la stessa password principale su tutti i dispositivi che condividono questa cartella."),
            ("Sync.Confirm", "Conferma"),
            ("Vault.Header", "Cassaforte password"), ("Vault.ImportTooltip", "Importa password da un file"),
            ("Vault.ExportTooltip", "Esporta password in un file cifrato"),
            ("Vault.NewPassword", "Nuova password"),
            ("Vault.SearchWatermark", "Cerca per servizio, utente o categoria"),
            ("Vault.BreachTooltip", "Verifica password trapelate (Have I Been Pwned)"),
            ("Vault.AuditTooltip", "Controlla password deboli, riutilizzate o vecchie"),
            ("Vault.SecurityReportTooltip", "Rapporto di sicurezza del caveau"),
            ("Vault.FavoritesOnlyTooltip", "Solo preferite"),
            ("Vault.TagFilter", "Filtra per etichetta"),
            ("Vault.Table.Service", "SERVIZIO"), ("Vault.Table.User", "UTENTE"),
            ("Vault.Table.Category", "CATEGORIA"),
            ("Vault.Table.Actions", "AZIONI"),
            ("Vault.Table.Strength", "FORZA"),
            ("Vault.SortTooltip", "Ordina"),
            ("Nav.Vault", "Cassaforte"),
            ("Nav.Favorites", "Preferite"),
            ("Nav.Recent", "Recenti"),
            ("Nav.Categories", "CATEGORIE"),
            ("Nav.Toggle", "Attiva/disattiva navigazione"),
            ("Details.Title", "Dettagli"),
            ("Details.Close", "Chiudi dettagli"),
            ("Details.Save", "Salva modifiche"),
            ("Details.Delete", "Elimina"),
            ("Details.FullEdit", "Modifica completa..."),
            ("Generator.Close", "Chiudi generatore"),
            ("Row.CopyUrl", "Copia URL"),
            ("Footer.AutoLockOff", "Blocco automatico disattivato"),
            ("Footer.AutoLockCountdown", "{0} min al blocco automatico"),
            ("Vault.Empty", "Nessuna password nella cassaforte.\nFai clic su \"Nuova password\" per iniziare."),
            ("Vault.Filter.All", "Tutte"), ("Vault.Counter.ItemSingular", "{0} elemento"),
            ("Vault.Counter.ItemPlural", "{0} elementi"),
            ("Vault.Status.PasswordSingular", "password"), ("Vault.Status.PasswordPlural", "password"),
            ("Vault.Status.FavoriteSingular", "preferita"), ("Vault.Status.FavoritePlural", "preferite"),
            ("Vault.Status.AuditOk", "audit OK"), ("Vault.Status.WithAlert", "{0} con avviso"),
            ("Vault.Connection.Local", "Cassaforte cifrata"),
            ("Vault.Connection.Connected", "Connesso: {0}"),
            ("Vault.Connection.DatabaseUnavailable", "Database non disponibile - uso cassaforte locale"),
            ("Generator.Title", "Generatore di password"), ("Generator.Mode", "Modalità"),
            ("Generator.Mode.Password", "Password"), ("Generator.Mode.Passphrase", "Frase password"),
            ("Generator.Strength", "Forza"), ("Generator.Quantity", "Quantità"),
            ("Generator.Length", "Lunghezza"), ("Generator.Uppercase", "Lettere maiuscole (A-Z)"),
            ("Generator.Lowercase", "Lettere minuscole (a-z)"), ("Generator.Numbers", "Numeri (0-9)"),
            ("Generator.Special", "Caratteri speciali (!@#)"), ("Generator.Words", "Parole"),
            ("Generator.Separator", "Separatore"), ("Generator.Separator.Space", "spazio"),
            ("Generator.Capitalize", "Iniziali maiuscole"), ("Generator.AddNumber", "Aggiungi numero"),
            ("Generator.GeneratePassword", "Genera nuova password"),
            ("Generator.GeneratePassphrase", "Genera frase password"),
            ("Generator.SaveToVault", "Salva nella cassaforte"), ("Generator.Clear", "Pulisci"),
            ("Generator.CopyAll", "Copia tutte"),
            ("Generator.PasswordsGenerated", "Password generate ({0})"),
            ("Generator.PassphrasesGenerated", "Frasi password generate ({0})"),
            ("Generator.StrengthWeak", "Debole"), ("Generator.StrengthMedium", "Media"),
            ("Generator.StrengthStrong", "Forte"), ("Generator.StrengthExcellent", "Eccellente"),
            ("Generator.Item.Password", "password"), ("Generator.Item.Passphrase", "frase password"),
            ("Generator.GenerateFirst", "Genera prima una {0}"),
            ("Generator.PasswordCopied", "Password copiata!"),
            ("Generator.PassphraseCopied", "Frase password copiata!"),
            ("Generator.PasswordCopiedClearing", "Password copiata! Sarà cancellata dagli appunti tra {0} secondi."),
            ("Generator.PassphraseCopiedClearing", "Frase password copiata! Sarà cancellata dagli appunti tra {0} secondi."),
            ("Login.SubtitleCreate", "Crea una password principale per proteggere la cassaforte"),
            ("Login.SubtitleUnlock", "Inserisci la password principale per sbloccare"),
            ("Login.MasterPassword", "Password principale"), ("Login.ConfirmPassword", "Conferma password"),
            ("Login.CreateVault", "Crea cassaforte"), ("Login.Unlock", "Sblocca"),
            ("Login.WindowsHello", "Sblocca con Windows Hello"),
            ("Login.EnableWindowsHello", "Attiva Windows Hello"),
            ("Login.WindowsHelloHint", "Usa impronta, volto o PIN per sbloccare più rapidamente."),
            ("Login.Error.PasswordLength", "La password deve avere almeno 8 caratteri."),
            ("Login.Error.PasswordMismatch", "Le password non coincidono."),
            ("Login.Error.MasterPasswordRequired", "Inserisci la password principale."),
            ("Login.Error.TooManyAttempts", "Troppi tentativi. Attendi 5 secondi."),
            ("Login.Error.WrongPassword", "Password errata. Tentativo {0} di 5."),
            ("Entry.NewTitle", "Nuova password"), ("Entry.EditTitle", "Modifica password"),
            ("Entry.EditTitleWithService", "Modifica password - {0}"),
            ("Entry.ServiceName", "Nome del servizio"), ("Entry.UserEmail", "Utente / E-mail"),
            ("Entry.Password", "Password"),
            ("Entry.PasswordKeepCurrent", "Password  (lascia vuoto per mantenere l'attuale)"),
            ("Entry.PasswordKeepCurrentFormat", "{0}  (lascia vuoto per mantenere l'attuale)"),
            ("Entry.TotpOptional", "Autenticazione a due fattori (2FA)  (opzionale)"),
            ("Entry.TotpRemove", "Autenticazione a due fattori (2FA)  (vuoto rimuove)"),
            ("Entry.TotpLabel", "Codice di verifica (2FA)"),
            ("Entry.TotpWatermark", "Incolla la chiave segreta o il link otpauth://"),
            ("Entry.TotpExpiresIn", "scade tra {0}s"), ("Entry.Category", "Categoria"),
            ("Entry.TagsOptional", "Etichette  (opzionale)"),
            ("Entry.TagsWatermark", "Es.: lavoro, importante, cliente-x"),
            ("Entry.UrlOptional", "URL  (opzionale)"), ("Entry.NotesOptional", "Note  (opzionale)"),
            ("Entry.Usage.Created", "Creata il {0}"), ("Entry.Usage.Updated", "Modificata il {0}"),
            ("Entry.Usage.CopyPasswordLabel", "Password copiata: {0}"), ("Entry.Usage.CopyUserLabel", "Nome utente copiato: {0}"),
            ("Entry.Usage.CopyTotpLabel", "TOTP copiato: {0}"), ("Entry.Usage.Never", "mai"),
            ("Entry.CreateRequired", "Compila i campi obbligatori (nome, utente e password)."),
            ("Entry.EditRequired", "Compila i campi obbligatori."),
            ("Entry.TotpInvalid", "La chiave di autenticazione a due fattori non è valida. Incolla la chiave segreta (Base32) o un link otpauth://."),
            ("Entry.CreateError", "Errore durante la creazione della password: {0}"),
            ("Entry.UpdateError", "Errore durante l'aggiornamento della password: {0}"),
            ("Entry.RecoverCurrentPasswordError", "Impossibile recuperare la password attuale. Inserisci una nuova password."),
            ("Entry.HistoryHeader", "Cronologia delle password ({0})"),
            ("Entry.HistoryReplacedOn", "Sostituita il {0}"),
            ("Entry.HistoryUse", "Usa"),
            ("Entry.HistoryUseTooltip", "Compila il campo con questa password"),
            ("A11y.PreviousPassword", "Password precedente"),

            ("Entry.RecoveryCodes", "Codici di ripristino"),
            ("Entry.RecoveryCodesWatermark", "Incolla un codice per riga"),
            ("Entry.RecoveryCodesAdd", "Aggiungi"),
            ("Entry.RecoveryCodeMarkUsed", "Segna come usato"),
            ("Entry.RecoveryCodeUnmark", "Rimuovi contrassegno"),
            ("Entry.RecoveryCodeRemove", "Rimuovi"),
            ("Entry.RecoveryCodeRemoveConfirm", "Rimuovere questo codice di ripristino? Questa azione non può essere annullata."),
            ("Entry.RecoveryCodesAddError", "Errore durante l'aggiunta dei codici di ripristino: {0}"),
            ("Entry.RecoveryCodeMarkError", "Errore durante l'aggiornamento del codice di ripristino: {0}"),
            ("Entry.RecoveryCodeRemoveError", "Errore durante la rimozione del codice di ripristino: {0}"),
            ("Entry.Attachments", "Allegati"),
            ("Entry.AttachmentsAdd", "Aggiungi allegato..."),
            ("Entry.AttachmentDownload", "Scarica"),
            ("Entry.AttachmentRemove", "Rimuovi"),
            ("Entry.AttachmentRemoveConfirm", "Rimuovere l'allegato \"{0}\"? Questa azione non può essere annullata."),
            ("Entry.AttachmentAddError", "Errore durante l'aggiunta dell'allegato: {0}"),
            ("Entry.AttachmentDownloadError", "Errore durante il download dell'allegato: {0}"),
            ("A11y.RecoveryCode", "Codice di ripristino"),

            ("Entry.Type", "Tipo di credenziale"),
            ("CredType.Login", "Accesso"),
            ("CredType.Cartao", "Carta"),
            ("CredType.ChaveLicenca", "Chiave di licenza"),
            ("CredType.WiFi", "Wi-Fi"),
            ("CredType.Servidor", "Server"),
            ("CredType.BancoDados", "Database"),
            ("CredField.CardHolder", "Intestatario della carta"),
            ("CredField.CardNumber", "Numero della carta"),
            ("CredField.Product", "Prodotto / Software"),
            ("CredField.LicenseKey", "Chiave di licenza"),
            ("CredField.Ssid", "Nome della rete (SSID)"),
            ("CredField.WifiPassword", "Password della rete"),
            ("CredField.Validade", "Scadenza"),
            ("CredField.Cvv", "CVV"),
            ("CredField.Bandeira", "Circuito della carta"),
            ("CredField.Seguranca", "Sicurezza"),
            ("CredField.Banda", "Banda"),
            ("CredField.Host", "Host"),
            ("CredField.Porta", "Porta"),
            ("CredField.Protocolo", "Protocollo"),
            ("CredField.NomeBanco", "Nome del database"),
            ("CredField.Motor", "Motore"),
            ("ExportDialog.ExportTitle", "Esporta password"),
            ("ExportDialog.ImportTitle", "Importa password"),
            ("ExportDialog.ExportPassword", "Password di esportazione"),
            ("ExportDialog.Password", "Password"),
            ("ExportDialog.InfoExport", "Definisci una password per proteggere il file. Sarà richiesta durante l'importazione - conservala bene, perché senza di essa il file non può essere aperto."),
            ("ExportDialog.InfoImport", "Inserisci la password definita quando il file è stato esportato."),
            ("ExportDialog.PasswordRequired", "Inserisci la password."),
            ("ExportDialog.PasswordLength", "La password deve avere almeno 8 caratteri."),
            ("ExportDialog.PasswordMismatch", "Le password non coincidono."),
            ("Master.ChangeTitle", "Cambia password principale"),
            ("Master.CurrentPassword", "Password principale attuale"),
            ("Master.NewPassword", "Nuova password principale"),
            ("Master.ConfirmNewPassword", "Conferma nuova password"),
            ("Master.ErrorCurrentRequired", "Inserisci la password principale attuale."),
            ("Master.ErrorNewLength", "La nuova password deve avere almeno 8 caratteri."),
            ("Master.ErrorConfirmMismatch", "La conferma non coincide con la nuova password."),
            ("Master.ChangeError", "Errore durante il cambio della password principale: {0}"),
            ("Master.ChangedRestart", "Password principale cambiata con successo.\n\nL'applicazione verrà riavviata per applicare la nuova password."),
            ("Biometric.Title", "Windows Hello"),
            ("Biometric.EnableOffer", "Vuoi attivare lo sblocco con Windows Hello su questo dispositivo?\n\nLa password principale continuerà a funzionare come alternativa."),
            ("Biometric.Enabled", "Lo sblocco con Windows Hello è attivo su questo dispositivo."),
            ("Biometric.Disabled", "Lo sblocco con Windows Hello è disattivato su questo dispositivo."),
            ("Biometric.DisableConfirm", "Disattivare lo sblocco con Windows Hello su questo dispositivo?"),
            ("Biometric.DisabledAfterMasterChange", "Lo sblocco con Windows Hello è stato disattivato e potrà essere riattivato dopo il riavvio."),
            ("Biometric.DisabledAfterKdfUpgrade", "La tua cassaforte ha ricevuto un rafforzamento di sicurezza nella derivazione della chiave. Lo sblocco con Windows Hello è stato disattivato e può essere riattivato ora dal menu delle impostazioni."),
            ("Biometric.NotEnabled", "Lo sblocco con Windows Hello non è attivo."),
            ("Biometric.InvalidVaultKey", "La chiave della cassaforte non è valida per attivare Windows Hello."),
            ("Biometric.InvalidRegistration", "La registrazione di Windows Hello non corrisponde più a questa cassaforte. Accedi con la password principale e riattivala."),
            ("Biometric.EnableError", "Errore durante l'attivazione di Windows Hello: {0}"),
            ("Biometric.UnlockError", "Errore durante lo sblocco con Windows Hello: {0}"),
            ("Biometric.UnsupportedPlatform", "Windows Hello è disponibile solo su Windows 10 o versioni successive."),
            ("Biometric.AvailabilityError", "Impossibile verificare la disponibilità di Windows Hello: {0}"),
            ("Biometric.NotConfigured", "Configura un PIN, la biometria o Windows Hello nelle impostazioni di Windows."),
            ("Biometric.RetriesExhausted", "Troppi tentativi di verifica. Riprova più tardi."),
            ("Biometric.Unavailable", "Windows Hello non è disponibile al momento."),
            ("Qr.RegenerateTitle", "Rigenera codice QR"),
            ("Qr.RegenerateInstruction", "Conferma la password principale per generare un nuovo codice QR di backup."),
            ("Qr.GenerateButton", "Genera codice QR"),
            ("Qr.ErrorMasterRequired", "Inserisci la password principale."),
            ("Qr.ErrorMasterIncorrect", "Password principale errata."),
            ("Qr.BackupTitle", "Backup della password principale"),
            ("Qr.BackupTitleWithType", "Backup della password principale (codice QR)"),
            ("Qr.Offer", "Vuoi salvare un codice QR di backup della password principale?\n\nATTENZIONE: il codice QR contiene la versione frase password della tua password principale. Chiunque scansioni l'immagine potrà ricostruire la password e accedere alla cassaforte.\n\nConserva il file in un luogo sicuro e offline (o stampato) - mai in cloud, e-mail o cartelle condivise."),
            ("Qr.SavePickerTitle", "Salva codice QR della password principale"),
            ("Qr.SaveSuccess", "Codice QR salvato con successo. Conservalo in un luogo sicuro."),
            ("Qr.SaveError", "Impossibile salvare il codice QR: {0}"),
            ("Qr.SheetSubtitle", "Backup della password principale"),
            ("Qr.SheetWarning1", "Contiene la versione frase password della password principale."),
            ("Qr.SheetWarning2", "Conserva in un luogo sicuro e offline."),
            ("Db.SelectTitle", "Connetti database"), ("Db.ChooseType", "Scegli il tipo di database da connettere."),
            ("Db.SelectExplanation", "Una funzione per uso self-hosted o condiviso: collega la cassaforte a un proprio database, utile per un server personale o per condividere l'accesso con altre persone di fiducia. Per sincronizzare solo i propri dispositivi senza mantenere un database, usa la Sincronizzazione tramite cartella condivisa nel menu delle impostazioni."),
            ("Db.ConnectionTitle", "Connessione"), ("Db.ConnectProviderTitle", "Connetti - {0}"),
            ("Db.TestConnection", "Test connessione"), ("Db.DatabaseFile", "File database (.db)"),
            ("Db.Browse", "Sfoglia..."), ("Db.Host", "Host"), ("Db.Port", "Porta"),
            ("Db.Database", "Database"), ("Db.User", "Utente"), ("Db.Password", "Password"),
            ("Db.SQLitePickerTitle", "File database SQLite"),
            ("Db.ConnectionSuccess", "Connessione riuscita."),
            ("Db.CreateTableTitle", "Crea tabella"),
            ("Db.TableMissing", "La tabella \"{0}\" non esiste in questo database.\n\nVuoi crearla ora?"),
            ("Db.ConnectionCanceledNoTable", "Connessione annullata: la tabella non esiste."),
            ("Db.ErrorFileRequired", "Indica il file del database."),
            ("Db.ErrorFieldsRequired", "Compila host, database e utente."),
            ("Db.ErrorInvalidPort", "Porta non valida."),
            ("Db.ConnectionFailed", "Connessione non riuscita: {0}"),
            ("Db.CannotConnect", "Impossibile connettersi: {0}"),
            ("Db.FeatureUnavailable", "Funzione non disponibile in questa sessione."),
            ("Db.ConnectedMessage", "Connesso al database — i dati ora vengono rispecchiati con questo database condiviso.\n\n{0}"),
            ("Db.ConnectError", "Errore durante la connessione: {0}"),
            ("Message.LoadError", "Errore durante il caricamento: {0}"),
            ("Message.FavoriteError", "Errore durante la modifica del preferito: {0}"),
            ("Message.PinError", "Errore durante l'aggiunta ai fissati: {0}"),
            ("Message.DeleteTitle", "Elimina password"),
            ("Message.MoveToTrash", "La credenziale sarà spostata nel cestino. Da lì potrai ripristinarla o eliminarla definitivamente."),
            ("Message.DeletePrompt", "Eliminare \"{0}\"?\n\n{1}"),
            ("Message.DeleteError", "Errore durante l'eliminazione della password: {0}"),
            ("Nav.Trash", "Cestino"),
            ("Trash.Empty", "Il cestino è vuoto."),
            ("Trash.DeletedOn", "Eliminata il {0}"),
            ("Trash.Restore", "Ripristina"),
            ("Trash.RestoreError", "Errore durante il ripristino: {0}"),
            ("Trash.DeleteForever", "Elimina definitivamente"),
            ("Trash.DeleteForeverConfirm", "Eliminare definitivamente \"{0}\"?\n\nQuesta azione non può essere annullata."),
            ("Trash.DeleteForeverError", "Errore durante l'eliminazione definitiva: {0}"),
            ("Trash.EmptyButton", "Svuota cestino"),
            ("Trash.EmptyConfirmTitle", "Svuota cestino"),
            ("Trash.EmptyConfirm", "Eliminare definitivamente tutti gli elementi nel cestino?\n\nQuesta azione non può essere annullata."),
            ("Trash.EmptyError", "Errore durante lo svuotamento del cestino: {0}"),
            ("Message.RenameDecryptError", "Impossibile decifrare la password per salvare la modifica."),
            ("Message.RenameError", "Errore durante la rinomina del servizio: {0}"),
            ("Message.AuditTitle", "Audit della cassaforte"),
            ("Message.AuditNoPasswords", "Non ci sono password nella cassaforte da controllare."),
            ("Message.AuditSuccess", "Audit completato: nessuna password debole, riutilizzata o vecchia tra {0} password."),
            ("Message.AuditIncomplete", "{0} password non sono state analizzate completamente."),
            ("Message.AuditFoundHeader", "Trovate {0} voce/i con avviso in {1} password:"),
            ("Message.AuditWeakLine", "- {0} deboli"),
            ("Message.AuditRepeatedLine", "- {0} riutilizzate"),
            ("Message.AuditOldLine", "- {0} vecchie"),
            ("Message.AuditUnreadableLine", "- {0} non controllate per errore di lettura"),
            ("Message.AuditMarked", "Le voci interessate sono state marcate con ⚠ nell'elenco."),
            ("Message.AuditOldDefinition", "Le password vecchie non sono state aggiornate da {0} giorni o più."),
            ("Message.AuditError", "Errore durante l'audit della cassaforte: {0}"),

            ("SecurityReport.Title", "Rapporto di sicurezza"),
            ("SecurityReport.ScoreLabel", "Punteggio del caveau"),
            ("SecurityReport.ScoreWeak", "Richiede attenzione"),
            ("SecurityReport.ScoreMedium", "Discreto"),
            ("SecurityReport.ScoreStrong", "Buono"),
            ("SecurityReport.ScoreExcellent", "Eccellente"),
            ("SecurityReport.Weak", "Password deboli"),
            ("SecurityReport.Repeated", "Password riutilizzate"),
            ("SecurityReport.Old", "Password vecchie"),
            ("SecurityReport.Compromised", "Password compromesse"),
            ("SecurityReport.NoTotp", "Senza autenticazione a due fattori"),
            ("SecurityReport.NoUrl", "Senza URL salvato"),
            ("SecurityReport.NoCategory", "Senza categoria definita"),
            ("SecurityReport.RowAutomationName", "{0}: {1}"),
            ("SecurityReport.CheckBreaches", "Verifica violazioni ora"),
            ("SecurityReport.BreachesNotChecked", "Non ancora verificato in questa sessione"),
            ("SecurityReport.AllGood", "Nessun problema trovato. Continua così!"),
            ("SecurityReport.ClearFilter", "Rimuovi filtro"),
            ("SecurityReport.FilterActive", "Filtrato per: {0}"),
            ("SecurityReport.BreachCheckError", "Errore durante la verifica delle violazioni: {0}"),
            ("Message.BreachTitle", "Verifica fughe"),
            ("Message.BreachNoPasswords", "Non ci sono password nella cassaforte da verificare."),
            ("Message.BreachDoneTitle", "Verifica completata"),
            ("Message.BreachSuccess", "Buone notizie! Nessuna delle {0} password verificate è stata trovata in fughe note."),
            ("Message.BreachWarning", "Attenzione: {0} di {1} password compaiono in fughe note. Valuta di cambiarle (marcate con ⚠)."),
            ("Message.NetworkErrorTitle", "Errore di rete"),
            ("Message.BreachNetworkError", "Impossibile verificare le fughe.\nControlla la connessione a internet.\n\nDettaglio: {0}"),
            ("Message.ExportEmpty", "La cassaforte è vuota. Non c'è nulla da esportare."),
            ("Message.ExportSuccess", "{0} password esportate con successo.\n\nConserva bene la password di esportazione - senza di essa il file non può essere aperto."),
            ("Message.ExportError", "Errore durante l'esportazione: {0}"),
            ("Message.ImportEmpty", "Nessuna password trovata nel file."),
            ("Message.ImportSuccess", "{0} password importate con successo."),
            ("Message.ImportIgnored", "{0} ignorate (già esistenti o non valide)."),
            ("Message.ImportError", "Errore durante l'importazione: {0}"),
            ("Message.CsvEmpty", "Nessuna credenziale trovata nel file."),
            ("Message.CsvConfirm", "Rilevato un file in formato {0} con {1} credenziale/i.\n\nLe password saranno aggiunte alla cassaforte (gli elementi esistenti vengono ignorati). Continuare?"),
            ("Message.CsvIgnored", "{0} ignorate (già esistenti o incomplete)."),
            ("Message.CsvSecurity", "Per sicurezza, elimina il file CSV - conserva le password in testo semplice."),
            ("Row.FavoriteRemove", "Rimuovi dai preferiti"), ("Row.FavoriteAdd", "Aggiungi ai preferiti"),
            ("Row.PinEntry", "Fissa in alto"), ("Row.UnpinEntry", "Rimuovi fissaggio"),
            ("Row.CopyUser", "Copia utente"), ("Row.EditService", "Modifica servizio"),
            ("Row.RevealPassword", "Mostra password"), ("Row.HidePassword", "Nascondi password"),
            ("Row.CopyPassword", "Copia password"), ("Row.EditEntry", "Modifica voce"),
            ("Row.DeleteEntry", "Elimina voce"), ("Row.CopyTotp", "Copia codice 2FA"),
            ("Row.CopyRecoveryCode", "Copia codice di ripristino"),
            ("Row.UserCopied", "Utente copiato"),
            ("Row.PasswordCopiedClearing", "Password copiata — cancellazione tra {0}s"),
            ("Row.CategoryTooltip", "Categoria: {0}"), ("Row.TagsTooltip", "Etichette: {0}\nCategoria: {1}"),
            ("Row.PasswordCompromised", "Password compromessa - trovata in {0:N0} fuga/fughe. Cambiala!"),
            ("Row.AuditPrefix", "Audit: {0}"), ("Row.NotFoundInBreaches", " (non trovata in fughe)"),
            ("Row.PasswordWeak", "Password debole"), ("Row.PasswordMedium", "Password media"),
            ("Row.PasswordStrong", "Password forte"), ("Row.AuditWeak", "password debole"),
            ("Row.AuditRepeatedWithCount", "password riutilizzata in {0} voci"),
            ("Row.AuditRepeated", "password riutilizzata"),
            ("Row.AuditOld", "non aggiornata da {0} giorni"), ("Row.AuditAlert", "avviso"),
            ("Category.Work", "Lavoro"), ("Category.Personal", "Personale"),
            ("Category.Finance", "Finanze"), ("Category.Social", "Social"), ("Category.Other", "Altro"),
            ("Access.Title", "Accessibilità"), ("Access.Colorblind", "Daltonismo"), ("Access.None", "Nessuno"),
            ("Access.Protanopia", "Protanopia"), ("Access.Deuteranopia", "Deuteranopia"), ("Access.Tritanopia", "Tritanopia"),
            ("Access.Monochromacy", "Monocromia"),
            ("Access.HighContrast", "Contrasto elevato"), ("Access.TextSize", "Dimensione del testo"),
            ("Access.TextNormal", "Normale"), ("Access.TextLarge", "Grande"), ("Access.TextLarger", "Più grande"),
            ("Access.ReduceMotion", "Riduci animazioni"), ("Access.ScreenReader", "Lettore schermo"),
            ("Access.ScreenReaderHelp", "Modalità più descrittiva per lettori schermo"), ("Access.Minimize", "Riduci a icona"),
            ("Access.Maximize", "Ingrandisci"), ("Access.Close", "Chiudi finestra")
        });
    }
}
