namespace CofreDeSenhas
{
    internal static partial class Idioma
    {
        private static IReadOnlyDictionary<string, string> CriarFr() => Mesclar(new (string, string)[]
        {
            ("App.Title", "Coffre de mots de passe"),
            ("Common.Save", "Enregistrer"), ("Common.Apply", "Appliquer"), ("Common.Cancel", "Annuler"), ("Common.Change", "Modifier"),
            ("Common.Connect", "Connecter"), ("Common.Export", "Exporter"), ("Common.Import", "Importer"),
            ("Common.Exit", "Quitter"), ("Common.Close", "Fermer"),
            ("Common.Warning", "Avertissement"), ("Common.Error", "Erreur"), ("Common.Success", "Succès"),
            ("Common.UnexpectedError", "Erreur inattendue : {0}"),
            ("Common.Validation", "Validation"), ("Common.Yes", "Oui"), ("Common.No", "Non"),
            ("Common.AllFiles", "Tous les fichiers"), ("Common.ExportedVaultFile", "Coffre exporté"),
            ("Common.CsvFile", "Fichier CSV"), ("Common.PngImage", "Image PNG"),
            ("Common.AndMore", "+{0} de plus"),
            ("Common.SQLiteDatabase", "Base SQLite"),
            ("Settings.Tooltip", "Paramètres"), ("Settings.SectionSecurity", "SÉCURITÉ"),
            ("Settings.ChangeMasterPassword", "Modifier le mot de passe maître..."),
            ("Settings.RegenerateQr", "Regénérer le code QR..."), ("Settings.Backup", "Sauvegarde et restauration..."),
            ("Settings.AutoLock", "Verrouillage automatique"),
            ("Settings.Disabled", "Désactivé"), ("Settings.AfterOneMinute", "Après 1 minute"),
            ("Settings.AfterMinutes5", "Après 5 minutes"), ("Settings.AfterMinutes15", "Après 15 minutes"),
            ("Settings.AfterMinutes30", "Après 30 minutes"),
            ("Settings.SectionAppearance", "APPARENCE"), ("Settings.Language", "Langue"),
            ("Settings.ClipboardClear", "Effacement du presse-papiers"),
            ("Settings.ClipboardClear.After15", "Après 15 secondes"),
            ("Settings.ClipboardClear.After30", "Après 30 secondes"),
            ("Settings.ClipboardClear.After60", "Après 60 secondes"),
            ("Settings.SectionData", "DONNÉES"),
            ("Settings.ImportCsv", "Importer depuis CSV / autre gestionnaire..."),
            ("Settings.ConnectDatabase", "Connecter une base de données..."),
            ("Settings.ConnectDatabaseTooltip", "Fonctionnalité self-hosted/partagée — pour synchroniser uniquement vos propres appareils, utilisez la Synchronisation par dossier."),
            ("Settings.DisconnectDatabase", "Déconnecter la base"),
            ("Settings.EnableWindowsHello", "Activer Windows Hello..."),
            ("Settings.DisableWindowsHello", "Désactiver Windows Hello"),
            ("Settings.OnlineIcons", "Icônes en ligne des services"),
            ("Settings.OnlineIconsTooltip", "Télécharge sur internet l'icône réelle de chaque service. Désactivé, le coffre n'affiche que des initiales et n'accède jamais au réseau."),
            ("Settings.TrackUsageHistory", "Enregistrer l'historique d'utilisation"),
            ("Settings.TrackUsageHistoryTooltip", "Enregistre la date de la dernière copie du mot de passe, de l'identifiant et du code TOTP de chaque identifiant. Désactivez pour arrêter d'enregistrer de nouvelles dates — celles déjà enregistrées restent visibles."),
            ("Settings.CheckUpdates", "Vérifier les mises à jour"),
            ("Settings.CheckUpdatesTooltip", "Consulte les releases GitHub pour signaler une version plus récente. Désactivé par défaut ; rien n'est téléchargé automatiquement et rien d'autre que cette consultation n'est envoyé."),
            ("Update.Available", "Nouvelle version disponible : {0}"),
            ("Update.ConfirmTitle", "Mettre à jour vers la version {0}"),
            ("Update.ConfirmMessage", "Vérifiez ce qui a changé dans la version {0} avant de continuer. La mise à jour sera téléchargée et appliquée automatiquement."),
            ("Update.NoReleaseNotes", "Aucune note de version trouvée pour cette version."),
            ("Update.Now", "Mettre à jour maintenant"),
            ("Update.Downloading", "Téléchargement..."),
            ("Update.Failed", "Impossible de mettre à jour automatiquement. Ouverture de la page des versions pour un téléchargement manuel."),
            ("Update.Error.NoAssets", "Impossible de récupérer les fichiers de cette version."),
            ("Update.Error.ExecutableNotFound", "Impossible de localiser l'exécutable actuel."),
            ("Update.Error.AssetNotFound", "Fichier de mise à jour introuvable pour cette version."),
            ("Update.Error.ChecksumUnavailable", "Impossible de vérifier l'intégrité du fichier."),
            ("Update.Error.ChecksumMismatch", "La vérification d'intégrité du fichier téléchargé a échoué."),
            ("Update.Error.SignatureMissing", "Cette version n'inclut pas la signature de mise à jour. Téléchargez la nouvelle version manuellement depuis la page des versions."),
            ("Update.Error.SignatureInvalid", "La signature de la mise à jour ne correspond pas. Le fichier a peut-être été altéré - ne l'installez pas."),
            ("Update.Dismiss", "Ignorer l'avis de mise à jour"),
            ("Icons.ConsentMessage", "Pour afficher l'icône réelle de chaque service, l'application interroge le service d'icônes de Google en envoyant uniquement le domaine du site (par exemple, github.com). Aucun mot de passe, identifiant ou autre donnée ne quitte votre ordinateur, et les icônes téléchargées sont mises en cache sur le disque pour éviter de nouvelles requêtes.\n\nActiver la récupération d'icônes en ligne ?"),
            ("Privacy.Enable", "Activer le mode confidentialité"), ("Privacy.Disable", "Désactiver le mode confidentialité"),
            ("Settings.LockNow", "Verrouiller maintenant"),
            ("Settings.SectionHelp", "AIDE"),
            ("Settings.KeyboardShortcuts", "Raccourcis clavier..."),
            ("Settings.SectionDanger", "ZONE DE DANGER"),
            ("Settings.ClearVault", "Nettoyer le coffre..."),
            ("Settings.DeleteVault", "Supprimer le coffre..."),
            ("Shortcuts.Title", "Raccourcis clavier"),
            ("Shortcuts.Search", "Rechercher"),
            ("Shortcuts.NewPassword", "Nouveau mot de passe"),
            ("Shortcuts.OpenGenerator", "Ouvrir le générateur"),
            ("Shortcuts.LockNow", "Verrouiller maintenant"),
            ("Shortcuts.PrivacyMode", "Activer/désactiver le mode confidentialité"),
            ("Shortcuts.CopyUser", "Copier l'identifiant de la ligne sélectionnée"),
            ("Shortcuts.CopyPassword", "Copier le mot de passe de la ligne sélectionnée"),
            ("Shortcuts.CloseDialog", "Fermer la boîte de dialogue ou annuler"),
            ("Shortcuts.SelectedRowHint", "La « ligne sélectionnée » est celle qui a le focus clavier ; si aucune ne l'a, les raccourcis de copie utilisent la première ligne de la liste."),
            ("Backup.Title", "Sauvegarde du coffre"),
            ("Backup.Frequency", "Fréquence de la sauvegarde automatique"),
            ("Backup.Manual", "Manuelle uniquement"), ("Backup.Daily", "Quotidienne"), ("Backup.Weekly", "Hebdomadaire"),
            ("Backup.MaxKept", "Nombre maximal de sauvegardes conservées"),
            ("Backup.Now", "Sauvegarder maintenant"),
            ("Backup.NeverDone", "Aucune sauvegarde n'a encore été effectuée."),
            ("Backup.LastDone", "Dernière sauvegarde : {0}"),
            ("Backup.Available", "Sauvegardes disponibles"),
            ("Backup.None", "Aucune sauvegarde disponible pour le moment."),
            ("Backup.Restore", "Restaurer"),
            ("Backup.RestoreFrom", "Restaurer la sauvegarde du {0}"),
            ("Backup.RestoreTitle", "Restaurer une sauvegarde"),
            ("Backup.RestoreConfirm", "Cela remplacera tous les mots de passe du coffre par ceux de la sauvegarde du {0}. Les modifications faites après cette date seront perdues. Continuer ?"),
            ("Backup.RestoreSuccess", "Sauvegarde restaurée avec succès."),
            ("Backup.RestoreDisabledDbConnected", "Déconnectez la base de données pour restaurer une sauvegarde."),
            ("Backup.Success", "Sauvegarde créée avec succès."),
            ("Backup.Error", "Erreur lors du traitement de la sauvegarde : {0}"),

            ("Settings.Sync", "Synchronisation..."),
            ("Sync.Title", "Synchronisation entre appareils"),
            ("Sync.Explanation", "Synchronise le coffre avec d'autres appareils via un dossier partagé (ex. : Dropbox, OneDrive, Google Drive). Les données sont chiffrées de bout en bout avec votre mot de passe principal avant de quitter cet appareil — le fournisseur de cloud ne voit jamais de texte en clair."),
            ("Sync.Enable", "Choisir un dossier et activer"),
            ("Sync.Folder", "Dossier de synchronisation"),
            ("Sync.Frequency", "Synchroniser automatiquement"),
            ("Sync.EveryMinutes", "Toutes les {0} minutes"),
            ("Sync.Now", "Synchroniser maintenant"),
            ("Sync.LastDone", "Dernière synchronisation : {0}"),
            ("Sync.NeverDone", "Pas encore synchronisé."),
            ("Sync.ChooseFolder", "Choisissez le dossier de synchronisation"),
            ("Sync.EnableError", "Erreur lors de l'activation de la synchronisation : {0}"),
            ("Sync.Error.WriteFailed", "Impossible d'écrire le fichier de synchronisation. Vérifiez que le dossier est accessible."),
            ("Sync.Error.ReadFailed", "Impossible de lire le fichier de synchronisation. Réessayez dans un instant."),
            ("Sync.Success", "Synchronisation terminée avec succès."),
            ("Sync.AlreadyInProgress", "Une synchronisation est déjà en cours. Attendez qu'elle se termine avant de réessayer."),
            ("Sync.Error", "Erreur de synchronisation. Vérifiez que le dossier est accessible."),
            ("Sync.Disable", "Désactiver la synchronisation"),
            ("Sync.DisableConfirm", "Désactiver la synchronisation ? Les appareils cessent d'échanger des données entre eux, mais rien n'est supprimé."),
            ("Sync.ConfirmMasterTitle", "Confirmer le mot de passe principal"),
            ("Sync.ConfirmMasterInstruction", "Saisissez le mot de passe principal de ce coffre pour activer la synchronisation. Utilisez le même mot de passe principal sur tous les appareils qui partagent ce dossier."),
            ("Sync.Confirm", "Confirmer"),
            ("Sync.ConflictsTooltip", "Voir l'activité de synchronisation"),
            ("Sync.ConflictsTitle", "Activité de synchronisation"),
            ("Sync.ConflictsExplanation", "Enregistrements mis à jour depuis un autre appareil/client lors de la dernière synchronisation avec la base de données, rejetés suite à un échec de la vérification d'intégrité, ou sans signature d'intégrité enregistrée."),
            ("Sync.ConflictType.ConcurrentEdit", "Mis à jour par un autre appareil"),
            ("Sync.ConflictType.IntegrityViolated", "Donnée rejetée : échec de la vérification d'intégrité"),
            ("Sync.ConflictType.IntegrityMissing", "Aucune signature d'intégrité — vérifiez qu'elle n'a pas été altérée"),
            ("Vault.Header", "Coffre de mots de passe"),
            ("Vault.ImportTooltip", "Importer des mots de passe depuis un fichier"),
            ("Vault.ExportTooltip", "Exporter les mots de passe vers un fichier chiffré"),
            ("Vault.NewPassword", "Nouveau mot de passe"),
            ("Vault.SearchWatermark", "Rechercher par service, utilisateur ou catégorie"),
            ("Vault.BreachTooltip", "Vérifier les mots de passe divulgués (Have I Been Pwned)"),
            ("Vault.AuditTooltip", "Auditer les mots de passe faibles, réutilisés ou anciens"),
            ("Vault.SecurityReportTooltip", "Rapport de sécurité du coffre"),
            ("Vault.FavoritesOnlyTooltip", "Favoris uniquement"),
            ("Vault.TagFilter", "Filtrer par étiquette"),
            ("Vault.Table.Service", "SERVICE"), ("Vault.Table.User", "UTILISATEUR"),
            ("Vault.Table.Category", "CATÉGORIE"),
            ("Vault.Table.Actions", "ACTIONS"),
            ("Vault.Table.Strength", "FORCE"),
            ("Vault.SortTooltip", "Trier"),
            ("Nav.Vault", "Coffre"),
            ("Nav.Favorites", "Favoris"),
            ("Nav.Recent", "Récents"),
            ("Nav.Categories", "CATÉGORIES"),
            ("Nav.Toggle", "Basculer la navigation"),
            ("Details.Title", "Détails"),
            ("Details.Close", "Fermer les détails"),
            ("Details.Save", "Enregistrer les modifications"),
            ("Details.Delete", "Supprimer"),
            ("Details.FullEdit", "Édition complète..."),
            ("Generator.Close", "Fermer le générateur"),
            ("Row.CopyUrl", "Copier l'URL"),
            ("Footer.AutoLockOff", "Verrouillage automatique désactivé"),
            ("Footer.AutoLockCountdown", "{0} min avant le verrouillage automatique"),
            ("Vault.Empty", "Aucun mot de passe dans le coffre.\nCliquez sur \"Nouveau mot de passe\" pour commencer."),
            ("Vault.Filter.All", "Toutes"), ("Vault.Counter.ItemSingular", "{0} élément"),
            ("Vault.Counter.ItemPlural", "{0} éléments"),
            ("Batch.CountSingular", "{0} sélectionné"),
            ("Batch.CountPlural", "{0} sélectionnés"),
            ("Batch.Favorite", "Ajouter aux favoris"),
            ("Batch.AddTag", "Ajouter une étiquette"),
            ("Batch.AddTagWatermark", "Nom de l'étiquette"),
            ("Batch.Trash", "Déplacer vers la corbeille"),
            ("Batch.TrashConfirm", "Déplacer {0} identifiants vers la corbeille ? Vous pourrez les restaurer ou les supprimer définitivement depuis là."),
            ("Batch.CancelSelection", "Annuler la sélection"),
            ("Vault.Status", "{0} {1} • {2} {3}"),
            ("Vault.Status.PasswordSingular", "mot de passe"), ("Vault.Status.PasswordPlural", "mots de passe"),
            ("Vault.Status.FavoriteSingular", "favori"), ("Vault.Status.FavoritePlural", "favoris"),
            ("Vault.Status.AuditOk", "audit OK"), ("Vault.Status.WithAlert", "{0} avec alerte"),
            ("Vault.Connection.Local", "Coffre chiffré"),
            ("Vault.Connection.Connected", "Connecté : {0}"),
            ("Vault.Connection.DatabaseUnavailable", "Base indisponible - coffre local utilisé"),
            ("Generator.Title", "Générateur de mots de passe"), ("Generator.Mode", "Mode"),
            ("Generator.Mode.Password", "Mot de passe"), ("Generator.Mode.Passphrase", "Phrase secrète"),
            ("Generator.Strength", "Robustesse"), ("Generator.Quantity", "Quantité"),
            ("Generator.Length", "Longueur"), ("Generator.Uppercase", "Lettres majuscules (A-Z)"),
            ("Generator.Lowercase", "Lettres minuscules (a-z)"), ("Generator.Numbers", "Chiffres (0-9)"),
            ("Generator.Special", "Caractères spéciaux (!@#)"), ("Generator.Words", "Mots"),
            ("Generator.Separator", "Séparateur"), ("Generator.Separator.Space", "espace"),
            ("Generator.Capitalize", "Capitaliser les mots"), ("Generator.AddNumber", "Ajouter un nombre"),
            ("Generator.GeneratePassword", "Générer un mot de passe"),
            ("Generator.GeneratePassphrase", "Générer une phrase secrète"),
            ("Generator.SaveToVault", "Enregistrer dans le coffre"), ("Generator.Clear", "Effacer"),
            ("Generator.CopyAll", "Tout copier"),
            ("Generator.PasswordsGenerated", "Mots de passe générés ({0})"),
            ("Generator.PassphrasesGenerated", "Phrases secrètes générées ({0})"),
            ("Generator.StrengthWeak", "Faible"), ("Generator.StrengthMedium", "Moyenne"),
            ("Generator.StrengthStrong", "Forte"), ("Generator.StrengthExcellent", "Excellente"),
            ("Generator.Item.Password", "mot de passe"), ("Generator.Item.Passphrase", "phrase secrète"),
            ("Generator.GenerateFirst", "Générez d'abord un(e) {0}"),
            ("Generator.PasswordCopied", "Mot de passe copié !"),
            ("Generator.PassphraseCopied", "Phrase secrète copiée !"),
            ("Generator.PasswordCopiedClearing", "Mot de passe copié ! Il sera effacé du presse-papiers dans {0} secondes."),
            ("Generator.PassphraseCopiedClearing", "Phrase secrète copiée ! Elle sera effacée du presse-papiers dans {0} secondes."),
            ("Login.SubtitleCreate", "Créez un mot de passe maître pour protéger le coffre"),
            ("Login.SubtitleUnlock", "Saisissez votre mot de passe maître pour déverrouiller"),
            ("Login.MasterPassword", "Mot de passe maître"), ("Login.ConfirmPassword", "Confirmer le mot de passe"),
            ("Login.CreateVault", "Créer le coffre"), ("Login.Unlock", "Déverrouiller"),
            ("Login.WindowsHello", "Déverrouiller avec Windows Hello"),
            ("Login.EnableWindowsHello", "Activer Windows Hello"),
            ("Login.WindowsHelloHint", "Utilisez l'empreinte, le visage ou le code PIN pour déverrouiller plus vite."),
            ("Login.FirstRunNotice", "Conservez bien ce mot de passe : il n'est jamais envoyé ni stocké sur un serveur, et il n'existe aucun moyen de récupérer le coffre si vous l'oubliez. L'écran suivant propose une sauvegarde d'urgence par QR code."),
            ("Login.Error.PasswordLength", "Le mot de passe doit contenir au moins 8 caractères."),
            ("Login.Error.PasswordMismatch", "Les mots de passe ne correspondent pas."),
            ("Login.Error.MasterPasswordRequired", "Saisissez le mot de passe maître."),
            ("Login.Error.TooManyAttempts", "Trop de tentatives d'affilée. Attendez un peu avant de réessayer - le délai augmente à chaque nouvelle série d'échecs."),
            ("Login.Error.WrongPassword", "Mot de passe incorrect. Tentative {0} sur 5."),
            ("Login.RestoreFromDatabase", "Restaurer depuis une base de données"),
            ("Login.RestoreTitle", "Restaurer le coffre"),
            ("Login.RestoreInstruction", "Entrez le mot de passe maître de ce coffre pour le restaurer depuis la base de données :"),
            ("Login.RestoreConfirm", "Restaurer"),

            ("Entry.NewTitle", "Nouveau mot de passe"), ("Entry.EditTitle", "Modifier le mot de passe"),
            ("Entry.EditTitleWithService", "Modifier le mot de passe - {0}"),
            ("Entry.ServiceName", "Nom du service"), ("Entry.UserEmail", "Utilisateur / E-mail"),
            ("Entry.Password", "Mot de passe"),
            ("Entry.PasswordKeepCurrent", "Mot de passe  (laisser vide pour conserver l'actuel)"),
            ("Entry.PasswordKeepCurrentFormat", "{0}  (laisser vide pour conserver l'actuel)"),
            ("Entry.TotpOptional", "Authentification à deux facteurs (2FA)  (facultatif)"),
            ("Entry.TotpRemove", "Authentification à deux facteurs (2FA)  (vide pour supprimer)"),
            ("Entry.TotpLabel", "Code de vérification (2FA)"),
            ("Entry.TotpWatermark", "Collez la clé secrète ou le lien otpauth://"),
            ("Entry.TotpExpiresIn", "expire dans {0}s"), ("Entry.Category", "Catégorie"),
            ("Entry.TagsOptional", "Étiquettes  (facultatif)"),
            ("Entry.TagsWatermark", "Ex. : travail, important, client-x"),
            ("Entry.UrlOptional", "URL  (facultatif)"), ("Entry.NotesOptional", "Notes  (facultatif)"),
            ("Entry.Usage.Created", "Créée le {0}"), ("Entry.Usage.Updated", "Modifiée le {0}"),
            ("Entry.Usage.CopyPasswordLabel", "Mot de passe copié : {0}"), ("Entry.Usage.CopyUserLabel", "Identifiant copié : {0}"),
            ("Entry.Usage.CopyTotpLabel", "TOTP copié : {0}"), ("Entry.Usage.Never", "jamais"),
            ("Entry.CreateRequired", "Remplissez les champs obligatoires (nom, utilisateur et mot de passe)."),
            ("Entry.EditRequired", "Remplissez les champs obligatoires."),
            ("Entry.TotpInvalid", "La clé d'authentification à deux facteurs est invalide. Collez la clé secrète (Base32) ou un lien otpauth://."),
            ("Entry.CreateError", "Erreur lors de la création du mot de passe : {0}"),
            ("Entry.UpdateError", "Erreur lors de la mise à jour du mot de passe : {0}"),
            ("Entry.RecoverCurrentPasswordError", "Impossible de récupérer le mot de passe actuel. Saisissez un nouveau mot de passe."),
            ("Entry.Detail.DiscardChangesTitle", "Abandonner les modifications ?"),
            ("Entry.Detail.DiscardChangesConfirm", "Il y a des modifications non enregistrées sur cet identifiant. Si vous continuez, elles seront perdues."),
            ("Entry.Detail.ConcurrentChangeTitle", "Modifié ailleurs"),
            ("Entry.Detail.ConcurrentChangeConfirm", "Cet identifiant a été modifié (par synchronisation ou un autre appareil) pendant que vous l'éditiez. Enregistrer maintenant écrasera cette modification. Continuer quand même ?"),
            ("Entry.HistoryHeader", "Historique des mots de passe ({0})"),
            ("Entry.HistoryReplacedOn", "Remplacé le {0}"),
            ("Entry.HistoryUse", "Utiliser"),
            ("Entry.HistoryUseTooltip", "Remplir le champ avec ce mot de passe"),
            ("A11y.PreviousPassword", "Mot de passe précédent"),

            ("Entry.RecoveryCodes", "Codes de récupération"),
            ("Entry.RecoveryCodesWatermark", "Collez un code par ligne"),
            ("Entry.RecoveryCodesAdd", "Ajouter"),
            ("Entry.RecoveryCodeMarkUsed", "Marquer comme utilisé"),
            ("Entry.RecoveryCodeUnmark", "Annuler le marquage"),
            ("Entry.RecoveryCodeRemove", "Supprimer"),
            ("Entry.RecoveryCodeRemoveConfirm", "Supprimer ce code de récupération ? Cette action est irréversible."),
            ("Entry.RecoveryCodesAddError", "Erreur lors de l'ajout des codes de récupération : {0}"),
            ("Entry.RecoveryCodeMarkError", "Erreur lors de la mise à jour du code de récupération : {0}"),
            ("Entry.RecoveryCodeRemoveError", "Erreur lors de la suppression du code de récupération : {0}"),
            ("Entry.Attachments", "Pièces jointes"),
            ("Entry.AttachmentsAdd", "Ajouter une pièce jointe..."),
            ("Entry.AttachmentDownload", "Télécharger"),
            ("Entry.AttachmentRemove", "Supprimer"),
            ("Entry.AttachmentRemoveConfirm", "Supprimer la pièce jointe « {0} » ? Cette action est irréversible."),
            ("Entry.AttachmentAddError", "Erreur lors de l'ajout de la pièce jointe : {0}"),
            ("Entry.AttachmentDownloadError", "Erreur lors du téléchargement de la pièce jointe : {0}"),
            ("Entry.AttachmentRemoveError", "Erreur lors de la suppression de la pièce jointe : {0}"),
            ("A11y.RecoveryCode", "Code de récupération"),

            ("Entry.Type", "Type d'identifiant"),
            ("CredType.Login", "Connexion"),
            ("CredType.Cartao", "Carte"),
            ("CredType.ChaveLicenca", "Clé de licence"),
            ("CredType.WiFi", "Wi-Fi"),
            ("CredType.Servidor", "Serveur"),
            ("CredType.BancoDados", "Base de données"),
            ("CredField.CardHolder", "Titulaire de la carte"),
            ("CredField.CardNumber", "Numéro de carte"),
            ("CredField.Product", "Produit / Logiciel"),
            ("CredField.LicenseKey", "Clé de licence"),
            ("CredField.Ssid", "Nom du réseau (SSID)"),
            ("CredField.WifiPassword", "Mot de passe du réseau"),
            ("CredField.Validade", "Date d'expiration"),
            ("CredField.Cvv", "CVV"),
            ("CredField.Bandeira", "Réseau de la carte"),
            ("CredField.Seguranca", "Sécurité"),
            ("CredField.Banda", "Bande"),
            ("CredField.Host", "Hôte"),
            ("CredField.Porta", "Port"),
            ("CredField.Protocolo", "Protocole"),
            ("CredField.NomeBanco", "Nom de la base de données"),
            ("CredField.Motor", "Moteur"),
            ("ExportDialog.ExportTitle", "Exporter les mots de passe"),
            ("ExportDialog.ImportTitle", "Importer les mots de passe"),
            ("ExportDialog.ExportPassword", "Mot de passe d'exportation"),
            ("ExportDialog.Password", "Mot de passe"),
            ("ExportDialog.InfoExport", "Définissez un mot de passe pour protéger le fichier. Il sera requis à l'importation - conservez-le bien, car le fichier ne peut pas être ouvert sans lui."),
            ("ExportDialog.OnlyFiltered", "Exporter uniquement les éléments filtrés dans la liste ({0} sur {1})"),
            ("ExportDialog.InfoImport", "Saisissez le mot de passe défini lors de l'exportation du fichier."),
            ("ExportDialog.PasswordRequired", "Saisissez le mot de passe."),
            ("ExportDialog.PasswordLength", "Le mot de passe doit contenir au moins 8 caractères."),
            ("ExportDialog.PasswordMismatch", "Les mots de passe ne correspondent pas."),
            ("Master.ChangeTitle", "Modifier le mot de passe maître"),
            ("Master.KdfUpgradeTitle", "Renforcement de la sécurité"),
            ("Master.CurrentPassword", "Mot de passe maître actuel"),
            ("Master.NewPassword", "Nouveau mot de passe maître"),
            ("Master.ConfirmNewPassword", "Confirmer le nouveau mot de passe"),
            ("Master.ErrorCurrentRequired", "Indiquez le mot de passe maître actuel."),
            ("Master.ErrorNewLength", "Le nouveau mot de passe doit contenir au moins 8 caractères."),
            ("Master.ErrorConfirmMismatch", "La confirmation ne correspond pas au nouveau mot de passe."),
            ("Master.ChangeError", "Erreur lors du changement du mot de passe maître : {0}"),
            ("Master.ChangedRestart", "Mot de passe maître modifié avec succès.\n\nL'application va redémarrer pour appliquer le nouveau mot de passe."),
            ("Master.ItemsDiscardedWarning", "Certains éléments aux données corrompues (historique, champ supplémentaire, code de récupération ou pièce jointe) n'ont pas pu être récupérés et ont été écartés lors du changement."),
            ("Master.OtherDevicesWarning", "Si ce coffre est connecté à une base de données ou à un dossier de synchronisation partagé avec d'autres appareils, mettez également à jour le mot de passe maître sur ceux-ci après le redémarrage — sinon, ils ne pourront plus lire ce que cet appareil synchronise à partir de maintenant."),
            ("Biometric.Title", "Windows Hello"),
            ("Biometric.EnableOffer", "Voulez-vous activer le déverrouillage par Windows Hello sur cet appareil ?\n\nLe mot de passe maître continuera de fonctionner comme solution de secours."),
            ("Biometric.Enabled", "Le déverrouillage par Windows Hello est activé sur cet appareil."),
            ("Biometric.Disabled", "Le déverrouillage par Windows Hello est désactivé sur cet appareil."),
            ("Biometric.DisableConfirm", "Désactiver le déverrouillage par Windows Hello sur cet appareil ?"),
            ("Biometric.DisabledAfterMasterChange", "Le déverrouillage par Windows Hello a été désactivé et pourra être réactivé après le redémarrage."),
            ("Biometric.DisabledAfterKdfUpgrade", "Votre coffre a reçu un renforcement de sécurité de la dérivation de clé. Le déverrouillage par Windows Hello a été désactivé et peut être réactivé dès maintenant depuis le menu des paramètres."),
            ("Biometric.NotEnabled", "Le déverrouillage par Windows Hello n'est pas activé."),
            ("Biometric.InvalidVaultKey", "La clé du coffre n'est pas valide pour activer Windows Hello."),
            ("Biometric.InvalidRegistration", "L'enregistrement Windows Hello ne correspond plus à ce coffre. Connectez-vous avec le mot de passe maître et activez-le à nouveau."),
            ("Biometric.EnableError", "Erreur lors de l'activation de Windows Hello : {0}"),
            ("Biometric.UnlockError", "Erreur lors du déverrouillage avec Windows Hello : {0}"),
            ("Biometric.UnsupportedPlatform", "Windows Hello est disponible uniquement sur Windows 10 ou version ultérieure."),
            ("Biometric.AvailabilityError", "Impossible de vérifier la disponibilité de Windows Hello : {0}"),
            ("Biometric.NotConfigured", "Configurez un PIN, la biométrie ou Windows Hello dans les paramètres Windows."),
            ("Biometric.RetriesExhausted", "Trop de tentatives de vérification. Réessayez plus tard."),
            ("Biometric.Unavailable", "Windows Hello est actuellement indisponible."),
            ("Qr.RegenerateTitle", "Regénérer le code QR"),
            ("Qr.RegenerateInstruction", "Confirmez votre mot de passe maître pour générer un nouveau QR code de sauvegarde."),
            ("Qr.GenerateButton", "Générer le code QR"),
            ("Qr.ErrorMasterRequired", "Saisissez votre mot de passe maître."),
            ("Qr.ErrorMasterIncorrect", "Mot de passe maître incorrect."),
            ("Qr.BackupTitle", "Sauvegarde du mot de passe maître"),
            ("Qr.BackupTitleWithType", "Sauvegarde du mot de passe maître (code QR)"),
            ("Qr.Offer", "Voulez-vous enregistrer un code QR de sauvegarde de votre mot de passe maître ?\n\nATTENTION : le code QR contient la version phrase secrète de votre mot de passe maître. Toute personne qui scanne l'image peut reconstruire le mot de passe et accéder au coffre.\n\nConservez le fichier dans un endroit sûr et hors ligne (ou imprimé) - jamais dans le cloud, par e-mail ou dans des dossiers partagés."),
            ("Qr.SavePickerTitle", "Enregistrer le code QR du mot de passe maître"),
            ("Qr.SaveSuccess", "Code QR enregistré avec succès. Conservez-le dans un endroit sûr."),
            ("Qr.SaveError", "Impossible d'enregistrer le code QR : {0}"),
            ("Qr.CloudFolderWarning", "Ce dossier est synchronisé avec {0}. Enregistrer le code QR ici envoie votre mot de passe maître (sous une forme reconstructible) vers le cloud. Continuer quand même ?"),
            ("Qr.SheetSubtitle", "Sauvegarde du mot de passe maître"),
            ("Qr.SheetWarning1", "Contient la version phrase secrète du mot de passe maître."),
            ("Qr.SheetWarning2", "Conservez dans un endroit sûr et hors ligne."),
            ("Db.SelectTitle", "Connecter une base de données"),
            ("Db.SelectExplanation", "Une fonctionnalité pour un usage self-hosted ou partagé : connecte le coffre à votre propre base de données, utile pour un serveur personnel ou pour partager l'accès avec d'autres personnes de confiance. Pour synchroniser uniquement vos propres appareils sans maintenir de base de données, utilisez la Synchronisation par dossier partagé dans le menu des paramètres."),
            ("Db.ChooseType", "Choisissez le type de base de données à connecter."),
            ("Db.ConnectionTitle", "Connexion"), ("Db.ConnectProviderTitle", "Connecter - {0}"),
            ("Db.TestConnection", "Tester la connexion"), ("Db.DatabaseFile", "Fichier de base (.db)"),
            ("Db.Browse", "Parcourir..."), ("Db.Host", "Hôte"), ("Db.Port", "Port"),
            ("Db.Database", "Base de données"), ("Db.User", "Utilisateur"), ("Db.Password", "Mot de passe"),
            ("Db.RequireValidCertificate", "Exiger un certificat de serveur valide"),
            ("Db.RequireValidCertificateHelp", "Désactivé (par défaut) : la connexion est toujours chiffrée, mais accepte un certificat auto-signé — courant pour une base locale ou sur le réseau interne. Activez pour exiger un certificat validé par une autorité de confiance, recommandé pour une base hors de votre réseau."),
            ("Db.RequireRowIntegrity", "Exiger une signature d'intégrité sur les lignes"),
            ("Db.RequireRowIntegrityHelp", "Activé (par défaut) : les lignes de la base partagée sans signature d'intégrité valide sont écartées de la fusion au lieu d'entrer dans votre coffre, et apparaissent dans l'écran des conflits de synchronisation. Désactivez uniquement si vous partagez cette base avec des appareils utilisant une ancienne version de l'application, qui n'écrivent pas encore cette signature."),
            ("Db.SQLitePickerTitle", "Fichier de base SQLite"),
            ("Db.ConnectionSuccess", "Connexion réussie."),
            ("Db.CreateTableTitle", "Créer la table"),
            ("Db.TableMissing", "La table \"{0}\" n'existe pas dans cette base.\n\nVoulez-vous la créer maintenant ?"),
            ("Db.ConnectionCanceledNoTable", "Connexion annulée : la table n'existe pas."),
            ("Db.RestoreTableMissing", "Cette base de données n'a pas le coffre attendu — la table n'existe pas. Vérifiez les informations de connexion."),
            ("Db.RestoreNoAuthPublished", "Cette base de données n'a pas encore de mot de passe maître publié pour la restauration. Connectez d'abord, sur cette base de données, un appareil qui a déjà ce coffre déverrouillé — la publication se fait automatiquement à sa prochaine connexion."),
            ("Db.RestoreInvalidAuth", "Les paramètres de dérivation de clé enregistrés dans cette base de données sont hors de la plage acceptée. Le coffre ne peut pas en être restauré."),
            ("Db.ErrorFileRequired", "Indiquez le fichier de base."),
            ("Db.ErrorFieldsRequired", "Remplissez hôte, base de données et utilisateur."),
            ("Db.ErrorInvalidPort", "Port invalide."),
            ("Db.ConnectionFailed", "Échec de la connexion : {0}"),
            ("Db.CannotConnect", "Impossible de se connecter : {0}"),
            ("Db.Error.ConnectionFailed", "Impossible de se connecter à la base de données. Vérifiez l'hôte, le port et les identifiants."),
            ("Db.Error.SchemaFailed", "Impossible de créer ou de mettre à jour la table du coffre dans la base de données."),
            ("Db.FeatureUnavailable", "Fonctionnalité indisponible dans cette session."),
            ("Db.ConnectedMessage", "Connecté à la base de données — les données sont désormais reflétées dans cette base de données partagée.\n\n{0}"),
            ("Db.ConnectError", "Erreur de connexion : {0}"),
            ("Message.LoadError", "Erreur de chargement : {0}"),
            ("Message.FavoriteError", "Erreur de favori : {0}"),
            ("Message.PinError", "Erreur d'épinglage : {0}"),
            ("Message.DeleteTitle", "Supprimer le mot de passe"),
            ("Message.MoveToTrash", "L'identifiant sera déplacé vers la corbeille. Vous pourrez le restaurer ou le supprimer définitivement depuis là."),
            ("Message.DeletePrompt", "Supprimer \"{0}\" ?\n\n{1}"),
            ("Message.DeleteError", "Erreur lors de la suppression : {0}"),
            ("Nav.Trash", "Corbeille"),
            ("Trash.Empty", "La corbeille est vide."),
            ("Trash.DeletedOn", "Supprimée le {0}"),
            ("Trash.Restore", "Restaurer"),
            ("Trash.RestoreError", "Erreur lors de la restauration : {0}"),
            ("Trash.DeleteForever", "Supprimer définitivement"),
            ("Trash.DeleteForeverConfirm", "Supprimer définitivement \"{0}\" ?\n\nCette action est irréversible."),
            ("Trash.DeleteForeverError", "Erreur lors de la suppression définitive : {0}"),
            ("Trash.EmptyButton", "Vider la corbeille"),
            ("Trash.EmptyConfirmTitle", "Vider la corbeille"),
            ("Trash.EmptyConfirm", "Supprimer définitivement tous les éléments de la corbeille ?\n\nCette action est irréversible."),
            ("Trash.EmptyError", "Erreur lors du vidage de la corbeille : {0}"),

            ("Vault.ClearTitle", "Nettoyer le coffre"),
            ("Vault.ClearConfirm", "Déplacer tous les mots de passe du coffre vers la corbeille ?\n\nVous pourrez les restaurer depuis la corbeille si besoin."),
            ("Vault.ClearError", "Erreur lors du nettoyage du coffre : {0}"),
            ("Vault.DeleteTitle", "Supprimer le coffre"),
            ("Vault.DeleteReauthInstruction", "Saisissez votre mot de passe maître actuel pour continuer."),
            ("Vault.DeleteReauthButton", "Continuer"),
            ("Vault.DeleteConfirm", "Supprimer le coffre définitivement ?\n\nTous les mots de passe, le mot de passe maître, les sauvegardes et les pièces jointes seront effacés, et le déverrouillage par Windows Hello sera désactivé. Cette action est irréversible."),
            ("Vault.DeleteError", "Erreur lors de la suppression du coffre : {0}"),
            ("Vault.DeletedRestart", "Coffre supprimé. L'application va redémarrer."),
            ("Message.RenameDecryptError", "Impossible de déchiffrer le mot de passe pour enregistrer la modification."),
            ("Message.RenameError", "Erreur lors du renommage du service : {0}"),
            ("Message.AuditTitle", "Audit du coffre"),
            ("Message.AuditNoPasswords", "Aucun mot de passe dans le coffre à auditer."),
            ("Message.AuditSuccess", "Audit terminé : aucun mot de passe faible, réutilisé ou ancien parmi {0} mot(s) de passe."),
            ("Message.AuditIncomplete", "{0} mot(s) de passe n'ont pas pu être analysés complètement."),
            ("Message.AuditFoundHeader", "{0} entrée(s) avec alerte trouvée(s) parmi {1} mot(s) de passe :"),
            ("Message.AuditWeakLine", "- {0} faible(s)"),
            ("Message.AuditRepeatedLine", "- {0} réutilisé(s)"),
            ("Message.AuditOldLine", "- {0} ancien(s)"),
            ("Message.AuditUnreadableLine", "- {0} non audité(s) à cause d'une erreur de lecture"),
            ("Message.AuditMarked", "Les entrées concernées ont été marquées avec ⚠ dans la liste."),
            ("Message.AuditOldDefinition", "Les mots de passe anciens n'ont pas été mis à jour depuis {0} jours ou plus."),
            ("Message.AuditError", "Erreur lors de l'audit du coffre : {0}"),

            ("SecurityReport.Title", "Rapport de sécurité"),
            ("SecurityReport.ScoreLabel", "Score du coffre"),
            ("SecurityReport.TrendLabel", "Tendance du score"),
            ("SecurityReport.ScoreWeak", "À surveiller"),
            ("SecurityReport.ScoreMedium", "Correct"),
            ("SecurityReport.ScoreStrong", "Bon"),
            ("SecurityReport.ScoreExcellent", "Excellent"),
            ("SecurityReport.Weak", "Mots de passe faibles"),
            ("SecurityReport.Repeated", "Mots de passe réutilisés"),
            ("SecurityReport.Old", "Mots de passe anciens"),
            ("SecurityReport.Compromised", "Mots de passe compromis"),
            ("SecurityReport.NoTotp", "Sans authentification à deux facteurs"),
            ("SecurityReport.NoUrl", "Sans URL enregistrée"),
            ("SecurityReport.NoCategory", "Sans catégorie définie"),
            ("SecurityReport.CertNotRequired", "La connexion à la base de données n'exige pas de certificat de serveur valide. Le trafic reste chiffré, mais reste vulnérable à une attaque de l'intercepteur (man-in-the-middle). Activez « Exiger un certificat de serveur valide » dans l'écran de connexion à la base de données."),
            ("SecurityReport.RowAutomationName", "{0} : {1}"),
            ("SecurityReport.CheckBreaches", "Vérifier les fuites maintenant"),
            ("SecurityReport.BreachesNotChecked", "Pas encore vérifié durant cette session"),
            ("SecurityReport.AllGood", "Aucun problème trouvé. Continuez ainsi !"),
            ("SecurityReport.ClearFilter", "Effacer le filtre"),
            ("SecurityReport.FilterActive", "Filtré par : {0}"),
            ("SecurityReport.BreachCheckError", "Erreur lors de la vérification des fuites : {0}"),
            ("Message.BreachTitle", "Vérifier les fuites"),
            ("Message.BreachNoPasswords", "Aucun mot de passe dans le coffre à vérifier."),
            ("Message.BreachDoneTitle", "Vérification terminée"),
            ("Message.BreachSuccess", "Bonne nouvelle ! Aucun des {0} mot(s) de passe vérifiés n'a été trouvé dans des fuites connues."),
            ("Message.BreachWarning", "Attention : {0} sur {1} mot(s) de passe apparaissent dans des fuites connues. Pensez à les changer (marqués avec ⚠)."),
            ("Message.NetworkErrorTitle", "Erreur réseau"),
            ("Message.BreachNetworkError", "Impossible de vérifier les fuites.\nVérifiez votre connexion internet.\n\nDétail : {0}"),
            ("Message.ExportEmpty", "Le coffre est vide. Rien à exporter."),
            ("Message.ExportSuccess", "{0} mot(s) de passe exporté(s) avec succès.\n\nConservez bien le mot de passe d'exportation - sans lui le fichier ne peut pas être ouvert."),
            ("Message.ExportError", "Erreur d'exportation : {0}"),
            ("Message.ImportEmpty", "Aucun mot de passe trouvé dans le fichier."),
            ("Message.ImportSuccess", "{0} mot(s) de passe importé(s) avec succès."),
            ("Message.ImportIgnored", "{0} ignoré(s) (données incomplètes ou invalides)."),
            ("Message.ImportDuplicates", "{0} existaient déjà dans le coffre."),
            ("Message.ImportError", "Erreur d'importation : {0}"),
            ("Message.CsvEmpty", "Aucun identifiant trouvé dans le fichier."),
            ("Message.CsvConfirm", "Fichier au format {0} détecté avec {1} identifiant(s).\n\nLes mots de passe seront ajoutés au coffre (les éléments existants sont ignorés). Continuer ?"),
            ("Message.CsvIgnored", "{0} ignoré(s) (ligne incomplète ou invalide)."),
            ("Message.CsvDuplicates", "{0} existaient déjà dans le coffre."),
            ("Message.CsvSecurity", "Par sécurité, supprimez le fichier CSV - il contient les mots de passe en clair."),
            ("Import.Progress", "Importation de {0} sur {1}…"),
            ("Export.Progress", "Exportation de {0} sur {1}…"),
            ("Row.FavoriteRemove", "Retirer des favoris"), ("Row.FavoriteAdd", "Ajouter aux favoris"),
            ("Row.PinEntry", "Épingler en haut"), ("Row.UnpinEntry", "Détacher"),
            ("Row.CopyUser", "Copier l'utilisateur"), ("Row.EditService", "Modifier le service"),
            ("Row.RevealPassword", "Révéler le mot de passe"), ("Row.HidePassword", "Masquer le mot de passe"),
            ("Row.CopyPassword", "Copier le mot de passe"), ("Row.EditEntry", "Modifier l'entrée"),
            ("Row.DeleteEntry", "Supprimer l'entrée"), ("Row.CopyTotp", "Copier le code 2FA"),
            ("Row.CopyRecoveryCode", "Copier le code de récupération"),
            ("Row.UserCopied", "Utilisateur copié"),
            ("Row.UserCopiedClearing", "Utilisateur copié — effacement dans {0}s"),
            ("Row.PasswordCopiedClearing", "Mot de passe copié — effacement dans {0}s"),
            ("Row.TotpCopiedClearing", "Code 2FA copié — effacement dans {0}s"),
            ("Row.CategoryTooltip", "Catégorie : {0}"), ("Row.TagsTooltip", "Étiquettes : {0}\nCatégorie : {1}"),
            ("Row.PasswordCompromised", "Mot de passe compromis - trouvé dans {0:N0} fuite(s). Changez-le !"),
            ("Row.AuditPrefix", "Audit : {0}"), ("Row.NotFoundInBreaches", " (introuvable dans les fuites)"),
            ("Row.PasswordWeak", "Mot de passe faible"), ("Row.PasswordMedium", "Mot de passe moyen"),
            ("Row.PasswordStrong", "Mot de passe fort"), ("Row.AuditWeak", "mot de passe faible"),
            ("Row.AuditRepeatedWithCount", "mot de passe réutilisé dans {0} entrées"),
            ("Row.AuditRepeated", "mot de passe réutilisé"),
            ("Row.AuditOld", "non mis à jour depuis {0} jours"), ("Row.AuditAlert", "alerte"),
            ("Category.Work", "Travail"), ("Category.Personal", "Personnel"),
            ("Category.Finance", "Finances"), ("Category.Social", "Social"), ("Category.Other", "Autre"),
            ("Access.Title", "Accessibilité"), ("Access.Colorblind", "Daltonisme"), ("Access.None", "Aucun"),
            ("Access.Protanopia", "Protanopie"), ("Access.Deuteranopia", "Deutéranopie"), ("Access.Tritanopia", "Tritanopie"),
            ("Access.Monochromacy", "Monochromatie"),
            ("Access.HighContrast", "Contraste élevé"), ("Access.TextSize", "Taille du texte"),
            ("Access.TextNormal", "Normal"), ("Access.TextLarge", "Grand"), ("Access.TextLarger", "Plus grand"),
            ("Access.ReduceMotion", "Réduire les animations"), ("Access.ScreenReader", "Lecteur d'écran"),
            ("Access.ScreenReaderHelp", "Mode plus descriptif pour les lecteurs d'écran"), ("Access.Minimize", "Réduire"),
            ("Access.Maximize", "Agrandir"), ("Access.Restore", "Restaurer"), ("Access.Close", "Fermer la fenêtre"),

            ("A11y.PasswordFieldHelp", "Champ protégé. Révélez le mot de passe uniquement dans un endroit sûr."),
            ("A11y.GeneratedPassword", "Mot de passe généré"),
            ("A11y.GeneratedPasswordHelp", "La valeur n'est pas annoncée automatiquement. Utilisez copier pour l'envoyer dans le presse-papiers."),
            ("A11y.GeneratedReady", "{0} {1}(s) généré(s). Utilisez copier pour les envoyer dans le presse-papiers."),
            ("A11y.GeneratedList", "Liste des mots de passe générés"),
            ("A11y.CopyGenerated", "Copier l'élément généré"),
            ("A11y.CopyAllGenerated", "Copier tous les éléments générés"),
            ("A11y.Copied", "{0} copié dans le presse-papiers."),
            ("A11y.Restored", "{0} restauré."),
            ("A11y.CopiedWillClear", "{0} copié. Il sera effacé du presse-papiers dans {1} secondes."),
            ("A11y.PasswordVisible", "Mot de passe visible à l'écran."),
            ("A11y.PasswordHidden", "Mot de passe masqué."),
            ("A11y.PrivacyModeOn", "Mode confidentialité activé. Service, utilisateur et catégorie masqués dans la liste."),
            ("A11y.PrivacyModeOff", "Mode confidentialité désactivé."),
            ("A11y.RowHelp", "Utilisez Tab pour accéder aux actions de cette entrée."),
            ("A11y.SortByColumn", "Cliquez pour trier par cette colonne."),
            ("A11y.EditServiceHelp", "Appuyez sur Entrée pour modifier le nom du service."),
            ("A11y.EditServiceMode", "Modification du service. Appuyez sur Entrée pour enregistrer ou Échap pour annuler."),
            ("A11y.SliderHelp", "Utilisez les flèches pour ajuster. Début et Fin vont au minimum et au maximum."),
            ("A11y.ToggleOn", "Activé"),
            ("A11y.ToggleOff", "Désactivé"),
            ("A11y.VaultStatus", "État du coffre"),
            ("A11y.ConnectionStatus", "État de la connexion"),
            ("A11y.ResultsList", "Liste des mots de passe"),
            ("A11y.EmptyList", "Liste vide"),
            ("A11y.OptionalField", "Champ facultatif"),
            ("A11y.TotpPreview", "Aperçu du code 2FA"),
            ("A11y.FilterOn", "Filtre activé"),
            ("A11y.FilterOff", "Filtre désactivé"),
            ("A11y.ScreenReaderEnabled", "Lecteur d'écran activé."),
            ("A11y.ScreenReaderDisabled", "Lecteur d'écran désactivé."),

            ("Entry.FieldDecryptError", "(impossible de déchiffrer ce champ)"),
            ("Entry.Error.ServiceRequired", "Le nom du service ne peut pas être vide"),
            ("Entry.Error.UserRequired", "L'utilisateur ne peut pas être vide"),
            ("Entry.Error.PasswordRequired", "Le mot de passe ne peut pas être vide"),
            ("Entry.Error.ServiceTooLong", "Le nom du service ne peut pas dépasser {0} caractères"),
            ("Entry.Error.UserTooLong", "L'utilisateur ne peut pas dépasser {0} caractères"),
            ("Entry.Error.PasswordTooLong", "Le mot de passe ne peut pas dépasser {0} caractères"),
            ("Entry.Error.UrlTooLong", "L'URL ne peut pas dépasser {0} caractères"),
            ("Entry.Error.NotesTooLong", "Les notes ne peuvent pas dépasser {0} caractères"),
            ("Entry.Error.CustomFieldTooLong", "Le champ personnalisé ne peut pas dépasser {0} caractères"),
            ("Entry.Error.RecoveryCodeTooLong", "Le code de récupération ne peut pas dépasser {0} caractères"),
            ("Entry.Error.RecoveryCodesTooMany", "Une entrée ne peut pas avoir plus de {0} codes de récupération"),
            ("Auth.Error.PasswordRequired", "Le mot de passe maître ne peut pas être vide."),
            ("Auth.Error.PasswordTooShort", "Le mot de passe maître doit comporter au moins {0} caractères."),
            ("Master.Error.NewPasswordTooShort", "Le nouveau mot de passe maître doit comporter au moins {0} caractères."),
            ("Master.Error.CurrentPasswordWrong", "Le mot de passe maître actuel est incorrect."),
            ("Export.Error.PasswordTooShort", "Le mot de passe d'exportation doit comporter au moins {0} caractères."),
            ("Export.Error.FileNotFound", "Fichier d'importation introuvable."),
            ("Export.Error.PasswordRequired", "Indiquez le mot de passe d'exportation."),
            ("Export.Error.InvalidFile", "Fichier d'importation invalide ou corrompu."),
            ("Export.Error.WrongPassword", "Mot de passe d'exportation incorrect ou fichier corrompu."),
            ("Export.Error.InvalidContent", "Contenu du fichier d'importation invalide."),
            ("Import.Error.FileNotFound", "Fichier d'importation introuvable."),
            ("Import.Error.CannotRead", "Impossible de lire le fichier d'importation."),
            ("Import.Error.EmptyFile", "Le fichier est vide."),
            ("Import.Error.NoCredentials", "Le fichier ne contient aucune information à importer."),
            ("Import.Error.NoPasswordColumn", "Impossible d'identifier la colonne du mot de passe. Vérifiez que le fichier a une ligne d'en-tête avec les noms des colonnes."),
            ("Attachment.Error.NameRequired", "Le nom du fichier ne peut pas être vide"),
            ("Attachment.Error.EmptyFile", "Fichier vide"),
            ("Attachment.Error.FileTooLarge", "Fichier supérieur à la limite de {0} Mo par pièce jointe"),
            ("Attachment.Error.MaxPerCredential", "Cette entrée a déjà atteint le maximum de {0} pièces jointes"),
            ("Attachment.Error.VaultLimit", "Le coffre atteindrait la limite de {0} Mo de pièces jointes"),
            ("Generator.Error.LengthRange", "La longueur du mot de passe doit être comprise entre 4 et 1000 caractères."),
            ("Generator.Error.NoCharacterType", "Sélectionnez au moins un type de caractère."),
            ("Generator.Error.PassphraseWordsRange", "La phrase de passe doit comporter entre 3 et 12 mots."),
            ("Generator.Error.SeparatorTooLong", "Le séparateur doit comporter au maximum 3 caractères."),
            ("Generator.Error.NotEnoughWords", "Indiquez une liste d'au moins deux mots."),
            ("Generator.Error.QuantityRange", "La quantité doit être comprise entre 1 et 50."),
            ("Vault.Error.WrongKeyOrCorrupt", "Impossible d'ouvrir le coffre : la clé est incorrecte ou le fichier a été corrompu."),
            ("Vault.Error.CorruptData", "Le contenu du coffre est corrompu."),
            ("Vault.Error.IOFailure", "Impossible d'accéder au fichier du coffre."),
            ("Vault.RestoredCopyTitle", "Le coffre a peut-être été restauré"),
            ("Vault.RestoredCopyWarning", "Le fichier du coffre est une copie identique de l'une des sauvegardes. Cela arrive quand quelqu'un copie une sauvegarde par-dessus le coffre en dehors de l'application, ce qui annule les modifications récentes (mots de passe changés, éléments supprimés). Si ce n'est pas vous, envisagez de changer vos mots de passe et de vérifier l'ordinateur."),
            ("Vault.Error.BackupFailed", "Impossible de créer la sauvegarde du coffre.")
        });
    }
}
